[package]
name = "libxc-kernel-lda"
version = "0.1.0"
edition = "2024"

[dependencies]
libxc-kernel-lda-1 = { path = "../kernel-lda-1" }
libxc-kernel-lda-2 = { path = "../kernel-lda-2" }
libxc-kernel-lda-3 = { path = "../kernel-lda-3" }
libxc-kernel-lda-4 = { path = "../kernel-lda-4" }

[dev-dependencies]
libxc_rs = { path = "../.." }
