[package]
name = "libxc-kernel-mgga"
version = "0.1.0"
edition = "2024"

[dependencies]
cubecl = { version = "0.9.0", default-features = false, features = ["cpu"] }
libxc-kernel-math = { path = "../kernel-math" }
libxc-kernel-mgga-1 = { path = "../kernel-mgga-1" }
libxc-kernel-mgga-2 = { path = "../kernel-mgga-2" }
libxc-kernel-mgga-3 = { path = "../kernel-mgga-3" }
libxc-kernel-mgga-4 = { path = "../kernel-mgga-4" }
libxc-kernel-mgga-5 = { path = "../kernel-mgga-5" }
libxc-kernel-mgga-6 = { path = "../kernel-mgga-6" }
libxc-kernel-mgga-7 = { path = "../kernel-mgga-7" }
libxc-kernel-mgga-8 = { path = "../kernel-mgga-8" }
libxc-kernel-mgga-9 = { path = "../kernel-mgga-9" }
libxc-kernel-mgga-10 = { path = "../kernel-mgga-10" }
libxc-kernel-mgga-11 = { path = "../kernel-mgga-11" }
libxc-kernel-mgga-12 = { path = "../kernel-mgga-12" }
libxc-kernel-mgga-13 = { path = "../kernel-mgga-13" }
libxc-kernel-mgga-14 = { path = "../kernel-mgga-14" }
libxc-kernel-mgga-15 = { path = "../kernel-mgga-15" }
libxc-kernel-mgga-16 = { path = "../kernel-mgga-16" }
libxc-kernel-mgga-17 = { path = "../kernel-mgga-17" }
libxc-kernel-mgga-18 = { path = "../kernel-mgga-18" }
libxc-kernel-mgga-19 = { path = "../kernel-mgga-19" }
libxc-kernel-mgga-20 = { path = "../kernel-mgga-20" }
libxc-kernel-mgga-21 = { path = "../kernel-mgga-21" }
libxc-kernel-mgga-22 = { path = "../kernel-mgga-22" }
libxc-kernel-mgga-23 = { path = "../kernel-mgga-23" }
libxc-kernel-mgga-24 = { path = "../kernel-mgga-24" }
libxc-kernel-mgga-25 = { path = "../kernel-mgga-25" }
libxc-kernel-mgga-26 = { path = "../kernel-mgga-26" }
libxc-kernel-mgga-27 = { path = "../kernel-mgga-27" }
libxc-kernel-mgga-28 = { path = "../kernel-mgga-28" }
libxc-kernel-mgga-29 = { path = "../kernel-mgga-29" }
libxc-kernel-mgga-30 = { path = "../kernel-mgga-30" }
libxc-kernel-mgga-31 = { path = "../kernel-mgga-31" }
libxc-kernel-mgga-32 = { path = "../kernel-mgga-32" }
libxc-kernel-mgga-33 = { path = "../kernel-mgga-33" }
libxc-kernel-mgga-34 = { path = "../kernel-mgga-34" }
libxc-kernel-mgga-35 = { path = "../kernel-mgga-35" }
libxc-kernel-mgga-36 = { path = "../kernel-mgga-36" }
libxc-kernel-mgga-37 = { path = "../kernel-mgga-37" }
