[package]
name = "libxc-kernel-mgga"
version = "0.1.0"
edition = "2024"

[dependencies]
cubecl = { version = "0.9.0", default-features = false, features = ["cpu"] }
libxc-kernel-math = { path = "../kernel-math" }
libxc-kernel-mgga-1a = { path = "../kernel-mgga-1a" }
libxc-kernel-mgga-1b = { path = "../kernel-mgga-1b" }
libxc-kernel-mgga-1c = { path = "../kernel-mgga-1c" }
libxc-kernel-mgga-1d = { path = "../kernel-mgga-1d" }
libxc-kernel-mgga-2a = { path = "../kernel-mgga-2a" }
libxc-kernel-mgga-2b = { path = "../kernel-mgga-2b" }
libxc-kernel-mgga-3a = { path = "../kernel-mgga-3a" }
libxc-kernel-mgga-3b = { path = "../kernel-mgga-3b" }
libxc-kernel-mgga-4a = { path = "../kernel-mgga-4a" }
libxc-kernel-mgga-4b = { path = "../kernel-mgga-4b" }
libxc-kernel-mgga-5 = { path = "../kernel-mgga-5" }
libxc-kernel-mgga-6 = { path = "../kernel-mgga-6" }
libxc-kernel-mgga-7a = { path = "../kernel-mgga-7a" }
libxc-kernel-mgga-7b = { path = "../kernel-mgga-7b" }
libxc-kernel-mgga-7c = { path = "../kernel-mgga-7c" }
libxc-kernel-mgga-7d = { path = "../kernel-mgga-7d" }
libxc-kernel-mgga-7e = { path = "../kernel-mgga-7e" }
libxc-kernel-mgga-8a = { path = "../kernel-mgga-8a" }
libxc-kernel-mgga-8b = { path = "../kernel-mgga-8b" }
libxc-kernel-mgga-8c = { path = "../kernel-mgga-8c" }
libxc-kernel-mgga-8d = { path = "../kernel-mgga-8d" }
libxc-kernel-mgga-8e = { path = "../kernel-mgga-8e" }
libxc-kernel-mgga-8f = { path = "../kernel-mgga-8f" }
libxc-kernel-mgga-9a = { path = "../kernel-mgga-9a" }
libxc-kernel-mgga-9b = { path = "../kernel-mgga-9b" }
libxc-kernel-mgga-10a = { path = "../kernel-mgga-10a" }
libxc-kernel-mgga-10b = { path = "../kernel-mgga-10b" }
libxc-kernel-mgga-11a = { path = "../kernel-mgga-11a" }
libxc-kernel-mgga-11b = { path = "../kernel-mgga-11b" }
libxc-kernel-mgga-11c = { path = "../kernel-mgga-11c" }
libxc-kernel-mgga-12a = { path = "../kernel-mgga-12a" }
libxc-kernel-mgga-12b = { path = "../kernel-mgga-12b" }
libxc-kernel-mgga-12c = { path = "../kernel-mgga-12c" }
libxc-kernel-mgga-12d = { path = "../kernel-mgga-12d" }
libxc-kernel-mgga-13a = { path = "../kernel-mgga-13a" }
libxc-kernel-mgga-13b = { path = "../kernel-mgga-13b" }
libxc-kernel-mgga-14a = { path = "../kernel-mgga-14a" }
libxc-kernel-mgga-14b = { path = "../kernel-mgga-14b" }
libxc-kernel-mgga-14c = { path = "../kernel-mgga-14c" }
libxc-kernel-mgga-14d = { path = "../kernel-mgga-14d" }
libxc-kernel-mgga-14e = { path = "../kernel-mgga-14e" }
libxc-kernel-mgga-14f = { path = "../kernel-mgga-14f" }
libxc-kernel-mgga-14g = { path = "../kernel-mgga-14g" }
libxc-kernel-mgga-14h = { path = "../kernel-mgga-14h" }
libxc-kernel-mgga-14i = { path = "../kernel-mgga-14i" }
libxc-kernel-mgga-14j = { path = "../kernel-mgga-14j" }
libxc-kernel-mgga-14k = { path = "../kernel-mgga-14k" }
libxc-kernel-mgga-14l = { path = "../kernel-mgga-14l" }
libxc-kernel-mgga-15a = { path = "../kernel-mgga-15a" }
libxc-kernel-mgga-15b = { path = "../kernel-mgga-15b" }
libxc-kernel-mgga-15c = { path = "../kernel-mgga-15c" }
libxc-kernel-mgga-15d = { path = "../kernel-mgga-15d" }
libxc-kernel-mgga-15e = { path = "../kernel-mgga-15e" }
libxc-kernel-mgga-15f = { path = "../kernel-mgga-15f" }
libxc-kernel-mgga-15g = { path = "../kernel-mgga-15g" }
libxc-kernel-mgga-15h = { path = "../kernel-mgga-15h" }
libxc-kernel-mgga-16 = { path = "../kernel-mgga-16" }
libxc-kernel-mgga-17 = { path = "../kernel-mgga-17" }
libxc-kernel-mgga-18a = { path = "../kernel-mgga-18a" }
libxc-kernel-mgga-18b = { path = "../kernel-mgga-18b" }
libxc-kernel-mgga-18c = { path = "../kernel-mgga-18c" }
libxc-kernel-mgga-19a = { path = "../kernel-mgga-19a" }
libxc-kernel-mgga-19b = { path = "../kernel-mgga-19b" }
libxc-kernel-mgga-19c = { path = "../kernel-mgga-19c" }
libxc-kernel-mgga-19d = { path = "../kernel-mgga-19d" }
libxc-kernel-mgga-19e = { path = "../kernel-mgga-19e" }
libxc-kernel-mgga-19f = { path = "../kernel-mgga-19f" }
libxc-kernel-mgga-19g = { path = "../kernel-mgga-19g" }
libxc-kernel-mgga-20a = { path = "../kernel-mgga-20a" }
libxc-kernel-mgga-20b = { path = "../kernel-mgga-20b" }
libxc-kernel-mgga-20c = { path = "../kernel-mgga-20c" }
libxc-kernel-mgga-20d = { path = "../kernel-mgga-20d" }
libxc-kernel-mgga-20e = { path = "../kernel-mgga-20e" }
libxc-kernel-mgga-20f = { path = "../kernel-mgga-20f" }
libxc-kernel-mgga-20g = { path = "../kernel-mgga-20g" }
libxc-kernel-mgga-20h = { path = "../kernel-mgga-20h" }
libxc-kernel-mgga-20i = { path = "../kernel-mgga-20i" }
libxc-kernel-mgga-20j = { path = "../kernel-mgga-20j" }
libxc-kernel-mgga-20k = { path = "../kernel-mgga-20k" }
libxc-kernel-mgga-20l = { path = "../kernel-mgga-20l" }
libxc-kernel-mgga-21 = { path = "../kernel-mgga-21" }
libxc-kernel-mgga-22a = { path = "../kernel-mgga-22a" }
libxc-kernel-mgga-22b = { path = "../kernel-mgga-22b" }
libxc-kernel-mgga-22c = { path = "../kernel-mgga-22c" }
libxc-kernel-mgga-22d = { path = "../kernel-mgga-22d" }
libxc-kernel-mgga-23 = { path = "../kernel-mgga-23" }
libxc-kernel-mgga-24a = { path = "../kernel-mgga-24a" }
libxc-kernel-mgga-24b = { path = "../kernel-mgga-24b" }
libxc-kernel-mgga-25a = { path = "../kernel-mgga-25a" }
libxc-kernel-mgga-25b = { path = "../kernel-mgga-25b" }
libxc-kernel-mgga-26a = { path = "../kernel-mgga-26a" }
libxc-kernel-mgga-26b = { path = "../kernel-mgga-26b" }
libxc-kernel-mgga-27a = { path = "../kernel-mgga-27a" }
libxc-kernel-mgga-27b = { path = "../kernel-mgga-27b" }
libxc-kernel-mgga-27c = { path = "../kernel-mgga-27c" }
libxc-kernel-mgga-28 = { path = "../kernel-mgga-28" }
libxc-kernel-mgga-29 = { path = "../kernel-mgga-29" }
libxc-kernel-mgga-30 = { path = "../kernel-mgga-30" }
libxc-kernel-mgga-31 = { path = "../kernel-mgga-31" }
libxc-kernel-mgga-32a = { path = "../kernel-mgga-32a" }
libxc-kernel-mgga-32b = { path = "../kernel-mgga-32b" }
libxc-kernel-mgga-33 = { path = "../kernel-mgga-33" }
libxc-kernel-mgga-34 = { path = "../kernel-mgga-34" }
libxc-kernel-mgga-35 = { path = "../kernel-mgga-35" }
libxc-kernel-mgga-36a = { path = "../kernel-mgga-36a" }
libxc-kernel-mgga-36b = { path = "../kernel-mgga-36b" }
libxc-kernel-mgga-37a = { path = "../kernel-mgga-37a" }
libxc-kernel-mgga-37b = { path = "../kernel-mgga-37b" }
