[package]
name = "libxc-kernel-mgga"
version = "0.1.0"
edition = "2024"

[dependencies]
cubecl = { version = "0.10.0", default-features = false, features = ["cpu"] }
libxc-kernel-math = { path = "../kernel-math" }
libxc-kernel-mgga-1 = { path = "../kernel-mgga-1" }
libxc-kernel-mgga-2 = { path = "../kernel-mgga-2" }
libxc-kernel-mgga-3 = { path = "../kernel-mgga-3" }
libxc-kernel-mgga-4 = { path = "../kernel-mgga-4" }
libxc-kernel-mgga-5 = { path = "../kernel-mgga-5" }
libxc-kernel-mgga-6 = { path = "../kernel-mgga-6" }
libxc-kernel-mgga-7 = { path = "../kernel-mgga-7" }
libxc-kernel-mgga-8 = { path = "../kernel-mgga-8" }
