//! Auto-generated by xtask generate-metadata. DO NOT EDIT.
#![allow(non_upper_case_globals)]

use super::PropagationRule;

#[allow(dead_code)]
pub(crate) const PROPAGATION_RULES: &[PropagationRule] = &[
    // Populated by cargo xtask generate-metadata
];
