//! Auto-generated by xtask generate-metadata. DO NOT EDIT.
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use super::PropagationRule;
use crate::model::FunctionalId;

pub(crate) const PROPAGATION_RULES: &[PropagationRule] = &[
    PropagationRule { parent_id: FunctionalId(433), parent_param_name: "_omega", parent_param_index: 3, aux_slot: 1, aux_param_name: "_omega" },
    PropagationRule { parent_id: FunctionalId(470), parent_param_name: "_omega", parent_param_index: 3, aux_slot: 1, aux_param_name: "_omega" },
    PropagationRule { parent_id: FunctionalId(395), parent_param_name: "_omega", parent_param_index: 5, aux_slot: 1, aux_param_name: "_omega" },
    PropagationRule { parent_id: FunctionalId(614), parent_param_name: "_omega", parent_param_index: 3, aux_slot: 1, aux_param_name: "_omega" },
    PropagationRule { parent_id: FunctionalId(682), parent_param_name: "_omega", parent_param_index: 2, aux_slot: 1, aux_param_name: "_omega" },
    PropagationRule { parent_id: FunctionalId(490), parent_param_name: "_omega", parent_param_index: 3, aux_slot: 1, aux_param_name: "_omega" },
    PropagationRule { parent_id: FunctionalId(482), parent_param_name: "_omega", parent_param_index: 3, aux_slot: 1, aux_param_name: "_omega" },
    PropagationRule { parent_id: FunctionalId(491), parent_param_name: "_omega", parent_param_index: 3, aux_slot: 1, aux_param_name: "_omega" },
    PropagationRule { parent_id: FunctionalId(478), parent_param_name: "_omega", parent_param_index: 2, aux_slot: 1, aux_param_name: "_omega" },
];
