//! FUSED_PBEH vxc pol -- explicit SIMD (bit-exact): fused composite kernel (gga_x_pbe, gga_c_pbe).
//!
//! GENERATED by tools/translate_rayon/fuse.py from the auxiliaries'
//! maple2c bodies -- do not hand-edit. Shared subexpressions are
//! value-numbered across legs and the mix accumulation
//! (`out += w_k * (0.0 + v_k)`, in auxiliary order) is emitted inline, so
//! the result is bit-identical to `evaluate_mixed_gga` on the same legs.

#![allow(unused_imports, unused_variables, non_snake_case, clippy::excessive_precision, clippy::too_many_arguments, clippy::needless_return)]
use libxc_rkernel_math::constants::*;
use libxc_rkernel_math::simd;
use libxc_rkernel_math::wide::{f64x8, CmpEq, CmpGe, CmpGt, CmpLe, CmpLt, CmpNe};

const V_ZERO: f64x8 = f64x8::new([0.0; 8]);
const V_ONE: f64x8 = f64x8::new([1.0; 8]);

// Transcendentals in exact mode come from `libxc_rkernel_math::simd`,
// which is bit-identical / correctly-rounded per lane to the scalar calls
// the scalar kernel makes. In exact mode, the SIMD kernel produces output
// bit-identical to its scalar form.

/// Load 8 consecutive grid points.
///
/// The tail is padded by repeating the last element, not by zero-filling:
/// these formulas divide by rho, so a zero lane would raise inf/NaN in lanes
/// whose results are then discarded -- harmless to the answer, but it makes
/// any real NaN impossible to spot while debugging.
#[inline(always)]
fn load(s: &[f64], ip: usize, np: usize) -> f64x8 {
    if ip + 8 <= np {
        let mut b = [0.0f64; 8];
        b.copy_from_slice(&s[ip..ip + 8]);
        f64x8::new(b)
    } else {
        let mut b = [s[np - 1]; 8];
        b[..np - ip].copy_from_slice(&s[ip..np]);
        f64x8::new(b)
    }
}

/// Accumulate 8 consecutive grid points into an output array.
///
/// `+=`, not `=`. The scalar kernel writes `out[ip] += v`; a plain store is a
/// different operation in two ways. It keeps the sign of a negative zero where
/// `0.0 + -0.0` gives `+0.0` -- a bit difference the fingerprint gate reports
/// as a rejection even though no value changed (`gga_x_pbepow fxc` was
/// rejected on exactly this, 273 of 200,000 `v2sigma2` elements) -- and it
/// would discard whatever a caller had already put in the buffer.
#[inline(always)]
fn store_add(s: &mut [f64], ip: usize, m: usize, acc: f64x8) {
    let a: [f64; 8] = acc.into();
    if m == 8 {
        let mut b = [0.0f64; 8];
        b.copy_from_slice(&s[ip..ip + 8]);
        let r: [f64; 8] = (f64x8::new(b) + acc).into();
        s[ip..ip + 8].copy_from_slice(&r);
    } else {
        for k in 0..m {
            s[ip + k] += a[k];
        }
    }
}

/// Load 8 elements with a given stride and offset.
#[inline(always)]
fn load_strided(s: &[f64], ip: usize, np: usize, stride: usize, offset: usize) -> f64x8 {
    let mut b = [0.0f64; 8];
    if ip + 8 <= np {
        let base = ip * stride + offset;
        b[0] = s[base];
        b[1] = s[base + stride];
        b[2] = s[base + 2 * stride];
        b[3] = s[base + 3 * stride];
        b[4] = s[base + 4 * stride];
        b[5] = s[base + 5 * stride];
        b[6] = s[base + 6 * stride];
        b[7] = s[base + 7 * stride];
    } else {
        for k in 0..8 {
            let p = (ip + k).min(np - 1);
            b[k] = s[p * stride + offset];
        }
    }
    f64x8::new(b)
}

/// Accumulate 8 elements with a given stride and offset.
///
/// `+=`, not `=`: the scalar kernel this was translated from writes
/// `out[ip * stride + offset] += v`, and a plain store is not the same
/// operation. It differs on the sign of zero -- `0.0 + -0.0` is `+0.0`
/// while a store of `-0.0` keeps the sign -- which is a bit difference
/// the fingerprint gate sees, and it would silently drop a caller's
/// existing contribution if one were ever there.
///
/// The read is not free on this path: a polarized `kxc`/`lxc` kernel
/// writes many strided outputs per point, and `lda_c_pw_erf kxc pol`
/// measured 84 -> 114 ns/pt (1.36x). It is charged anyway, because the
/// scalar kernel this is compared against does the same read. Gathering
/// into a vector, adding once and scattering back was tried and is no
/// faster (117 ns/pt), so the cost is the load itself, not scheduling.
#[inline(always)]
fn store_strided(s: &mut [f64], ip: usize, m: usize, stride: usize, offset: usize, acc: f64x8) {
    let a: [f64; 8] = acc.into();
    if m == 8 {
        let base = ip * stride + offset;
        s[base] += a[0];
        s[base + stride] += a[1];
        s[base + 2 * stride] += a[2];
        s[base + 3 * stride] += a[3];
        s[base + 4 * stride] += a[4];
        s[base + 5 * stride] += a[5];
        s[base + 6 * stride] += a[6];
        s[base + 7 * stride] += a[7];
    } else {
        for k in 0..m {
            s[(ip + k) * stride + offset] += a[k];
        }
    }
}

#[allow(unused_variables, non_snake_case)]
pub fn fused_pbeh_vxc_pol(
    rho: &[f64],
    sigma: &[f64],
    zk: &mut [f64],
    vrho: &mut [f64],
    vsigma: &mut [f64],
    w0: f64,
    w1: f64,
    l0_param_kappa: f64,
    l0_param_mu: f64,
    l1_param_gamma: f64,
    l1_param_BB: f64,
    l1_param_beta: f64,
    dens_threshold: f64,
    zeta_threshold: f64,
) {
    let np = zk.len();
    let w0 = f64x8::splat(w0);
    let w1 = f64x8::splat(w1);
    let l0_param_kappa = f64x8::splat(l0_param_kappa);
    let l0_param_mu = f64x8::splat(l0_param_mu);
    let l1_param_gamma = f64x8::splat(l1_param_gamma);
    let l1_param_BB = f64x8::splat(l1_param_BB);
    let l1_param_beta = f64x8::splat(l1_param_beta);
    let dens_threshold = f64x8::splat(dens_threshold);
    let zeta_threshold = f64x8::splat(zeta_threshold);
    // Loop-invariant bindings (constants, parameters, thresholds):
    // the same statements maple2c emits per point, evaluated once.
    let l0_t2 = f64x8::splat(M_CBRT3);
    let l0_t3 = f64x8::splat(M_CBRTPI);
    let l0_t5 = l0_t2 / l0_t3;
    let l0_t11 = zeta_threshold - f64x8::splat(1.0);
    let l0_t15 = -l0_t11;
    let l0_t21 = (simd::cbrt(zeta_threshold));
    let l0_t22 = l0_t21 * zeta_threshold;
    let l0_t28 = f64x8::splat(M_CBRT6);
    let l0_t29 = l0_param_mu * l0_t28;
    let l0_t30 = f64x8::splat(M_PI) * f64x8::splat(M_PI);
    let l0_t31 = (simd::cbrt(l0_t30));
    let l0_t32 = l0_t31 * l0_t31;
    let l0_t33 = f64x8::splat(1.0) / l0_t32;
    let l0_t100 = l0_param_kappa * l0_param_kappa;
    let l0_t171 = l0_t28 * l0_t33;
    let l0_tvsigma1 = f64x8::splat(0.0);
    let l1_t2 = f64x8::splat(1.0) / f64x8::splat(M_PI);
    let l1_t3 = (simd::cbrt(l1_t2));
    let l1_t4 = l0_t2 * l1_t3;
    let l1_t5 = f64x8::splat(M_CBRT4);
    let l1_t6 = l1_t5 * l1_t5;
    let l1_t19 = l0_t2 * l0_t2;
    let l1_t20 = l1_t3 * l1_t3;
    let l1_t21 = l1_t19 * l1_t20;
    let l1_t56 = f64x8::splat(M_CBRT2);
    let l1_t59 = f64x8::splat(1.0) / (f64x8::splat(2.0) * l1_t56 - f64x8::splat(2.0));
    let l1_t92 = l0_t21 * l0_t21;
    let l1_t110 = f64x8::splat(1.0) / l1_t3;
    let l1_t111 = l1_t110 * l1_t5;
    let l1_t115 = l1_param_BB * l1_param_beta;
    let l1_t116 = f64x8::splat(1.0) / l1_param_gamma;
    let l1_t130 = l1_t56 * l1_t56;
    let l1_t135 = f64x8::splat(1.0) / l1_t20;
    let l1_t136 = l0_t2 * l1_t135;
    let l1_t137 = l1_t136 * l1_t6;
    let l1_t143 = l1_param_beta * l1_t116;
    let l1_t164 = l1_t3 * l1_t6;
    let l1_t275 = l1_t19 * l1_t110;
    let l1_t280 = l1_t115 * l1_t116;
    let l1_t288 = l1_t135 * l1_t6;
    let l1_t404 = l1_t275 * l1_t5;
    let l1_t414 = l1_param_beta * l1_param_beta;
    let l1_t416 = l1_param_gamma * l1_param_gamma;
    let l1_t417 = f64x8::splat(1.0) / l1_t416;
    let mut ip = 0usize;
    while ip < np {
        let m = (np - ip).min(8);
        let v_rho0 = load_strided(rho, ip, np, 2, 0);
        let v_rho1 = load_strided(rho, ip, np, 2, 1);
        let v_sigma0 = load_strided(sigma, ip, np, 3, 0);
        let v_sigma1 = load_strided(sigma, ip, np, 3, 1);
        let v_sigma2 = load_strided(sigma, ip, np, 3, 2);
        let mut acc_zk = V_ZERO;
        let mut acc_vrho_0 = V_ZERO;
        let mut acc_vrho_1 = V_ZERO;
        let mut acc_vsigma_0 = V_ZERO;
        let mut acc_vsigma_1 = V_ZERO;
        let mut acc_vsigma_2 = V_ZERO;
        {
            let l0_t1 = (v_rho0).simd_le(dens_threshold);
            let l0_t6 = v_rho0 + v_rho1;
            let l0_t7 = f64x8::splat(1.0) / l0_t6;
            let l0_t10 = (f64x8::splat(2.0) * v_rho0 * l0_t7).simd_le(zeta_threshold);
            let l0_t14 = (f64x8::splat(2.0) * v_rho1 * l0_t7).simd_le(zeta_threshold);
            let l0_t16 = v_rho0 - v_rho1;
            let l0_t18 = ((l0_t10).select(l0_t11, (l0_t14).select(l0_t15, l0_t16 * l0_t7)));
            let l0_t19 = f64x8::splat(1.0) + l0_t18;
            let l0_t20 = (l0_t19).simd_le(zeta_threshold);
            let l0_t23 = (simd::cbrt(l0_t19));
            let l0_t25 = ((l0_t20).select(l0_t22, l0_t23 * l0_t19));
            let l0_t26 = (simd::cbrt(l0_t6));
            let l0_t27 = l0_t25 * l0_t26;
            let l0_t34 = l0_t33 * v_sigma0;
            let l0_t35 = v_rho0 * v_rho0;
            let l0_t36 = (simd::cbrt(v_rho0));
            let l0_t37 = l0_t36 * l0_t36;
            let l0_t39 = f64x8::splat(1.0) / l0_t37 / l0_t35;
            let l0_t43 = l0_param_kappa + l0_t29 * l0_t34 * l0_t39 / f64x8::splat(24.0);
            let l0_t48 = f64x8::splat(1.0) + l0_param_kappa * (f64x8::splat(1.0) - l0_param_kappa / l0_t43);
            let l0_t52 = ((l0_t1).select(f64x8::splat(0.0), -f64x8::splat(3.0) * f64x8::splat(0.125) * l0_t5 * l0_t27 * l0_t48));
            let l0_t53 = (v_rho1).simd_le(dens_threshold);
            let l0_t54 = -l0_t16;
            let l0_t56 = ((l0_t14).select(l0_t11, (l0_t10).select(l0_t15, l0_t54 * l0_t7)));
            let l0_t57 = f64x8::splat(1.0) + l0_t56;
            let l0_t58 = (l0_t57).simd_le(zeta_threshold);
            let l0_t59 = (simd::cbrt(l0_t57));
            let l0_t61 = ((l0_t58).select(l0_t22, l0_t59 * l0_t57));
            let l0_t62 = l0_t61 * l0_t26;
            let l0_t63 = l0_t33 * v_sigma2;
            let l0_t64 = v_rho1 * v_rho1;
            let l0_t65 = (simd::cbrt(v_rho1));
            let l0_t66 = l0_t65 * l0_t65;
            let l0_t68 = f64x8::splat(1.0) / l0_t66 / l0_t64;
            let l0_t72 = l0_param_kappa + l0_t29 * l0_t63 * l0_t68 / f64x8::splat(24.0);
            let l0_t77 = f64x8::splat(1.0) + l0_param_kappa * (f64x8::splat(1.0) - l0_param_kappa / l0_t72);
            let l0_t81 = ((l0_t53).select(f64x8::splat(0.0), -f64x8::splat(3.0) * f64x8::splat(0.125) * l0_t5 * l0_t62 * l0_t77));
            let l0_tzk0 = l0_t52 + l0_t81;
            let l0_t82 = l0_t6 * l0_t6;
            let l0_t83 = f64x8::splat(1.0) / l0_t82;
            let l0_t84 = l0_t16 * l0_t83;
            let l0_t86 = ((l0_t10).select(f64x8::splat(0.0), (l0_t14).select(f64x8::splat(0.0), l0_t7 - l0_t84)));
            let l0_t89 = ((l0_t20).select(f64x8::splat(0.0), f64x8::splat(4.0) / f64x8::splat(3.0) * l0_t23 * l0_t86));
            let l0_t90 = l0_t89 * l0_t26;
            let l0_t94 = l0_t26 * l0_t26;
            let l0_t95 = f64x8::splat(1.0) / l0_t94;
            let l0_t96 = l0_t25 * l0_t95;
            let l0_t99 = l0_t5 * l0_t96 * l0_t48 * f64x8::splat(0.125);
            let l0_t101 = l0_t27 * l0_t100;
            let l0_t102 = l0_t5 * l0_t101;
            let l0_t103 = l0_t43 * l0_t43;
            let l0_t105 = f64x8::splat(1.0) / l0_t103 * l0_param_mu;
            let l0_t106 = l0_t105 * l0_t28;
            let l0_t107 = l0_t35 * v_rho0;
            let l0_t109 = f64x8::splat(1.0) / l0_t37 / l0_t107;
            let l0_t111 = l0_t106 * l0_t34 * l0_t109;
            let l0_t115 = ((l0_t1).select(f64x8::splat(0.0), -f64x8::splat(3.0) * f64x8::splat(0.125) * l0_t5 * l0_t90 * l0_t48 - l0_t99 + l0_t102 * l0_t111 / f64x8::splat(24.0)));
            let l0_t116 = l0_t54 * l0_t83;
            let l0_t118 = ((l0_t14).select(f64x8::splat(0.0), (l0_t10).select(f64x8::splat(0.0), -l0_t7 - l0_t116)));
            let l0_t121 = ((l0_t58).select(f64x8::splat(0.0), f64x8::splat(4.0) / f64x8::splat(3.0) * l0_t59 * l0_t118));
            let l0_t122 = l0_t121 * l0_t26;
            let l0_t126 = l0_t61 * l0_t95;
            let l0_t129 = l0_t5 * l0_t126 * l0_t77 * f64x8::splat(0.125);
            let l0_t131 = ((l0_t53).select(f64x8::splat(0.0), -f64x8::splat(3.0) * f64x8::splat(0.125) * l0_t5 * l0_t122 * l0_t77 - l0_t129));
            let l0_tvrho0 = l0_t52 + l0_t81 + l0_t6 * (l0_t115 + l0_t131);
            let l0_t135 = ((l0_t10).select(f64x8::splat(0.0), (l0_t14).select(f64x8::splat(0.0), -l0_t7 - l0_t84)));
            let l0_t138 = ((l0_t20).select(f64x8::splat(0.0), f64x8::splat(4.0) / f64x8::splat(3.0) * l0_t23 * l0_t135));
            let l0_t139 = l0_t138 * l0_t26;
            let l0_t144 = ((l0_t1).select(f64x8::splat(0.0), -f64x8::splat(3.0) * f64x8::splat(0.125) * l0_t5 * l0_t139 * l0_t48 - l0_t99));
            let l0_t146 = ((l0_t14).select(f64x8::splat(0.0), (l0_t10).select(f64x8::splat(0.0), l0_t7 - l0_t116)));
            let l0_t149 = ((l0_t58).select(f64x8::splat(0.0), f64x8::splat(4.0) / f64x8::splat(3.0) * l0_t59 * l0_t146));
            let l0_t150 = l0_t149 * l0_t26;
            let l0_t154 = l0_t62 * l0_t100;
            let l0_t155 = l0_t5 * l0_t154;
            let l0_t156 = l0_t72 * l0_t72;
            let l0_t158 = f64x8::splat(1.0) / l0_t156 * l0_param_mu;
            let l0_t159 = l0_t158 * l0_t28;
            let l0_t160 = l0_t64 * v_rho1;
            let l0_t162 = f64x8::splat(1.0) / l0_t66 / l0_t160;
            let l0_t164 = l0_t159 * l0_t63 * l0_t162;
            let l0_t168 = ((l0_t53).select(f64x8::splat(0.0), -f64x8::splat(3.0) * f64x8::splat(0.125) * l0_t5 * l0_t150 * l0_t77 - l0_t129 + l0_t155 * l0_t164 / f64x8::splat(24.0)));
            let l0_tvrho1 = l0_t52 + l0_t81 + l0_t6 * (l0_t144 + l0_t168);
            let l0_t173 = l0_t105 * l0_t171 * l0_t39;
            let l0_t176 = ((l0_t1).select(f64x8::splat(0.0), -l0_t102 * l0_t173 * f64x8::splat(0.015625)));
            let l0_tvsigma0 = l0_t6 * l0_t176;
            let l0_t178 = l0_t158 * l0_t171 * l0_t68;
            let l0_t181 = ((l0_t53).select(f64x8::splat(0.0), -l0_t155 * l0_t178 * f64x8::splat(0.015625)));
            let l0_tvsigma2 = l0_t6 * l0_t181;
            let l1_t11 = l1_t4 * l1_t6 / l0_t26;
            let l1_t13 = f64x8::splat(1.0) + f64x8::splat(0.053425) * l1_t11;
            let l1_t14 = ((l1_t11).sqrt());
            let l1_t17 = ((l1_t11) * (l1_t11).sqrt());
            let l1_t25 = l1_t21 * l1_t5 / l0_t94;
            let l1_t27 = f64x8::splat(3.79785) * l1_t14 + f64x8::splat(0.8969) * l1_t11 + f64x8::splat(0.204775) * l1_t17 + f64x8::splat(0.123235) * l1_t25;
            let l1_t30 = f64x8::splat(1.0) + f64x8::splat(16.081979498692537) / l1_t27;
            let l1_t31 = (simd::ln(l1_t30));
            let l1_t33 = f64x8::splat(0.0621814) * l1_t13 * l1_t31;
            let l1_t35 = l0_t16 * l0_t16;
            let l1_t36 = l1_t35 * l1_t35;
            let l1_t38 = l0_t82 * l0_t82;
            let l1_t39 = f64x8::splat(1.0) / l1_t38;
            let l1_t40 = l1_t36 * l1_t39;
            let l1_t42 = l0_t16 * l0_t7;
            let l1_t43 = f64x8::splat(1.0) + l1_t42;
            let l1_t44 = (l1_t43).simd_le(zeta_threshold);
            let l1_t47 = (simd::cbrt(l1_t43));
            let l1_t48 = l1_t47 * l1_t43;
            let l1_t49 = ((l1_t44).select(l0_t22, l1_t48));
            let l1_t50 = f64x8::splat(1.0) - l1_t42;
            let l1_t51 = (l1_t50).simd_le(zeta_threshold);
            let l1_t52 = (simd::cbrt(l1_t50));
            let l1_t53 = l1_t52 * l1_t50;
            let l1_t54 = ((l1_t51).select(l0_t22, l1_t53));
            let l1_t55 = l1_t49 + l1_t54 - f64x8::splat(2.0);
            let l1_t60 = l1_t55 * l1_t59;
            let l1_t62 = f64x8::splat(1.0) + f64x8::splat(0.05137) * l1_t11;
            let l1_t67 = f64x8::splat(7.05945) * l1_t14 + f64x8::splat(1.549425) * l1_t11 + f64x8::splat(0.420775) * l1_t17 + f64x8::splat(0.1562925) * l1_t25;
            let l1_t70 = f64x8::splat(1.0) + f64x8::splat(32.16395899738507) / l1_t67;
            let l1_t71 = (simd::ln(l1_t70));
            let l1_t75 = f64x8::splat(1.0) + f64x8::splat(0.0278125) * l1_t11;
            let l1_t80 = f64x8::splat(5.1785) * l1_t14 + f64x8::splat(0.905775) * l1_t11 + f64x8::splat(0.1100325) * l1_t17 + f64x8::splat(0.1241775) * l1_t25;
            let l1_t83 = f64x8::splat(1.0) + f64x8::splat(29.608749977793437) / l1_t80;
            let l1_t84 = (simd::ln(l1_t83));
            let l1_t85 = l1_t75 * l1_t84;
            let l1_t87 = -f64x8::splat(0.0310907) * l1_t62 * l1_t71 + l1_t33 - f64x8::splat(0.0197516734986138) * l1_t85;
            let l1_t88 = l1_t60 * l1_t87;
            let l1_t89 = l1_t40 * l1_t88;
            let l1_t91 = f64x8::splat(0.0197516734986138) * l1_t60 * l1_t85;
            let l1_t93 = l1_t47 * l1_t47;
            let l1_t94 = ((l1_t44).select(l1_t92, l1_t93));
            let l1_t95 = l1_t52 * l1_t52;
            let l1_t96 = ((l1_t51).select(l1_t92, l1_t95));
            let l1_t98 = l1_t94 * f64x8::splat(0.5) + l1_t96 * f64x8::splat(0.5);
            let l1_t99 = l1_t98 * l1_t98;
            let l1_t100 = l1_t99 * l1_t98;
            let l1_t101 = l1_param_gamma * l1_t100;
            let l1_t103 = v_sigma0 + f64x8::splat(2.0) * v_sigma1 + v_sigma2;
            let l1_t105 = f64x8::splat(1.0) / l0_t26 / l0_t82;
            let l1_t106 = l1_t103 * l1_t105;
            let l1_t108 = f64x8::splat(1.0) / l1_t99;
            let l1_t112 = l1_t108 * l1_t19 * l1_t111;
            let l1_t118 = (-l1_t33 + l1_t89 + l1_t91) * l1_t116;
            let l1_t119 = f64x8::splat(1.0) / l1_t100;
            let l1_t121 = (simd::exp(-l1_t118 * l1_t119));
            let l1_t122 = l1_t121 - f64x8::splat(1.0);
            let l1_t123 = f64x8::splat(1.0) / l1_t122;
            let l1_t124 = l1_t116 * l1_t123;
            let l1_t125 = l1_t103 * l1_t103;
            let l1_t127 = l1_t115 * l1_t124 * l1_t125;
            let l1_t129 = f64x8::splat(1.0) / l0_t94 / l1_t38;
            let l1_t131 = l1_t129 * l1_t130;
            let l1_t132 = l1_t99 * l1_t99;
            let l1_t133 = f64x8::splat(1.0) / l1_t132;
            let l1_t134 = l1_t131 * l1_t133;
            let l1_t138 = l1_t134 * l1_t137;
            let l1_t141 = l1_t106 * l1_t56 * l1_t112 / f64x8::splat(96.0) + l1_t127 * l1_t138 / f64x8::splat(3072.0);
            let l1_t142 = l1_param_beta * l1_t141;
            let l1_t146 = l1_t143 * l1_t123 * l1_t141 + f64x8::splat(1.0);
            let l1_t147 = f64x8::splat(1.0) / l1_t146;
            let l1_t148 = l1_t116 * l1_t147;
            let l1_t150 = l1_t142 * l1_t148 + f64x8::splat(1.0);
            let l1_t151 = (simd::ln(l1_t150));
            let l1_t152 = l1_t101 * l1_t151;
            let l1_tzk0 = -l1_t33 + l1_t89 + l1_t91 + l1_t152;
            let l1_t154 = f64x8::splat(1.0) / l0_t26 / l0_t6;
            let l1_t155 = l1_t6 * l1_t154;
            let l1_t157 = l1_t4 * l1_t155 * l1_t31;
            let l1_t158 = f64x8::splat(0.0011073470983333333) * l1_t157;
            let l1_t159 = l1_t27 * l1_t27;
            let l1_t160 = f64x8::splat(1.0) / l1_t159;
            let l1_t161 = l1_t13 * l1_t160;
            let l1_t163 = f64x8::splat(1.0) / l1_t14 * l0_t2;
            let l1_t165 = l1_t164 * l1_t154;
            let l1_t166 = l1_t163 * l1_t165;
            let l1_t168 = l1_t4 * l1_t155;
            let l1_t171 = l1_t14 * l0_t2;
            let l1_t172 = l1_t171 * l1_t165;
            let l1_t177 = l1_t21 * l1_t5 / l0_t94 / l0_t6;
            let l1_t179 = -f64x8::splat(0.632975) * l1_t166 - f64x8::splat(0.29896666666666666) * l1_t168 - f64x8::splat(0.1023875) * l1_t172 - f64x8::splat(0.08215666666666667) * l1_t177;
            let l1_t180 = f64x8::splat(1.0) / l1_t30;
            let l1_t181 = l1_t179 * l1_t180;
            let l1_t182 = l1_t161 * l1_t181;
            let l1_t183 = f64x8::splat(1.0) * l1_t182;
            let l1_t184 = l1_t35 * l0_t16;
            let l1_t185 = l1_t184 * l1_t39;
            let l1_t186 = l1_t185 * l1_t88;
            let l1_t187 = f64x8::splat(4.0) * l1_t186;
            let l1_t188 = l1_t38 * l0_t6;
            let l1_t189 = f64x8::splat(1.0) / l1_t188;
            let l1_t190 = l1_t36 * l1_t189;
            let l1_t191 = l1_t190 * l1_t88;
            let l1_t192 = f64x8::splat(4.0) * l1_t191;
            let l1_t195 = l0_t7 - l0_t84;
            let l1_t198 = ((l1_t44).select(f64x8::splat(0.0), f64x8::splat(4.0) / f64x8::splat(3.0) * l1_t47 * l1_t195));
            let l1_t199 = -l1_t195;
            let l1_t202 = ((l1_t51).select(f64x8::splat(0.0), f64x8::splat(4.0) / f64x8::splat(3.0) * l1_t52 * l1_t199));
            let l1_t204 = (l1_t198 + l1_t202) * l1_t59;
            let l1_t205 = l1_t204 * l1_t87;
            let l1_t206 = l1_t40 * l1_t205;
            let l1_t210 = l1_t67 * l1_t67;
            let l1_t211 = f64x8::splat(1.0) / l1_t210;
            let l1_t212 = l1_t62 * l1_t211;
            let l1_t217 = -f64x8::splat(1.176575) * l1_t166 - f64x8::splat(0.516475) * l1_t168 - f64x8::splat(0.2103875) * l1_t172 - f64x8::splat(0.104195) * l1_t177;
            let l1_t218 = f64x8::splat(1.0) / l1_t70;
            let l1_t219 = l1_t217 * l1_t218;
            let l1_t225 = l1_t80 * l1_t80;
            let l1_t226 = f64x8::splat(1.0) / l1_t225;
            let l1_t227 = l1_t75 * l1_t226;
            let l1_t232 = -f64x8::splat(0.8630833333333333) * l1_t166 - f64x8::splat(0.301925) * l1_t168 - f64x8::splat(0.05501625) * l1_t172 - f64x8::splat(0.082785) * l1_t177;
            let l1_t233 = f64x8::splat(1.0) / l1_t83;
            let l1_t234 = l1_t232 * l1_t233;
            let l1_t237 = f64x8::splat(0.0005323764196666666) * l1_t4 * l1_t155 * l1_t71 + f64x8::splat(1.0) * l1_t212 * l1_t219 - l1_t158 - l1_t183 + f64x8::splat(0.00018311447306006544) * l1_t4 * l1_t155 * l1_t84 + f64x8::splat(0.5848223622634646) * l1_t227 * l1_t234;
            let l1_t238 = l1_t60 * l1_t237;
            let l1_t239 = l1_t40 * l1_t238;
            let l1_t240 = l1_t204 * l1_t85;
            let l1_t241 = f64x8::splat(0.0197516734986138) * l1_t240;
            let l1_t242 = l1_t60 * l0_t2;
            let l1_t244 = l1_t164 * l1_t154 * l1_t84;
            let l1_t245 = l1_t242 * l1_t244;
            let l1_t246 = f64x8::splat(0.00018311447306006544) * l1_t245;
            let l1_t247 = l1_t60 * l1_t75;
            let l1_t249 = l1_t226 * l1_t232 * l1_t233;
            let l1_t250 = l1_t247 * l1_t249;
            let l1_t251 = f64x8::splat(0.5848223622634646) * l1_t250;
            let l1_t252 = l1_param_gamma * l1_t99;
            let l1_t253 = f64x8::splat(1.0) / l1_t47;
            let l1_t256 = ((l1_t44).select(f64x8::splat(0.0), f64x8::splat(2.0) / f64x8::splat(3.0) * l1_t253 * l1_t195));
            let l1_t257 = f64x8::splat(1.0) / l1_t52;
            let l1_t260 = ((l1_t51).select(f64x8::splat(0.0), f64x8::splat(2.0) / f64x8::splat(3.0) * l1_t257 * l1_t199));
            let l1_t262 = l1_t256 * f64x8::splat(0.5) + l1_t260 * f64x8::splat(0.5);
            let l1_t263 = l1_t151 * l1_t262;
            let l1_t264 = l1_t252 * l1_t263;
            let l1_t265 = f64x8::splat(3.0) * l1_t264;
            let l1_t266 = l0_t82 * l0_t6;
            let l1_t268 = f64x8::splat(1.0) / l0_t26 / l1_t266;
            let l1_t269 = l1_t103 * l1_t268;
            let l1_t272 = f64x8::splat(7.0) / f64x8::splat(288.0) * l1_t269 * l1_t56 * l1_t112;
            let l1_t273 = l1_t56 * l1_t119;
            let l1_t274 = l1_t106 * l1_t273;
            let l1_t276 = l1_t5 * l1_t262;
            let l1_t277 = l1_t275 * l1_t276;
            let l1_t281 = l1_t122 * l1_t122;
            let l1_t282 = f64x8::splat(1.0) / l1_t281;
            let l1_t283 = l1_t282 * l1_t125;
            let l1_t285 = l1_t280 * l1_t283 * l1_t129;
            let l1_t286 = l1_t130 * l1_t133;
            let l1_t287 = l1_t286 * l0_t2;
            let l1_t290 = (l1_t158 + l1_t183 + l1_t187 - l1_t192 + l1_t206 + l1_t239 + l1_t241 - l1_t246 - l1_t251) * l1_t116;
            let l1_t292 = l1_t133 * l1_t262;
            let l1_t295 = f64x8::splat(3.0) * l1_t118 * l1_t292 - l1_t290 * l1_t119;
            let l1_t296 = l1_t295 * l1_t121;
            let l1_t297 = l1_t288 * l1_t296;
            let l1_t298 = l1_t287 * l1_t297;
            let l1_t302 = f64x8::splat(1.0) / l0_t94 / l1_t188;
            let l1_t303 = l1_t302 * l1_t130;
            let l1_t304 = l1_t303 * l1_t133;
            let l1_t305 = l1_t304 * l1_t137;
            let l1_t307 = f64x8::splat(7.0) / f64x8::splat(4608.0) * l1_t127 * l1_t305;
            let l1_t308 = l1_t123 * l1_t125;
            let l1_t310 = l1_t280 * l1_t308 * l1_t129;
            let l1_t312 = f64x8::splat(1.0) / l1_t132 / l1_t98;
            let l1_t313 = l1_t130 * l1_t312;
            let l1_t314 = l1_t313 * l0_t2;
            let l1_t316 = l1_t314 * l1_t288 * l1_t262;
            let l1_t319 = -l1_t272 - l1_t274 * l1_t277 / f64x8::splat(48.0) - l1_t285 * l1_t298 / f64x8::splat(3072.0) - l1_t307 - l1_t310 * l1_t316 / f64x8::splat(768.0);
            let l1_t320 = l1_param_beta * l1_t319;
            let l1_t322 = l1_t146 * l1_t146;
            let l1_t323 = f64x8::splat(1.0) / l1_t322;
            let l1_t324 = l1_t116 * l1_t323;
            let l1_t325 = l1_t143 * l1_t282;
            let l1_t326 = l1_t141 * l1_t295;
            let l1_t331 = -l1_t325 * l1_t326 * l1_t121 + l1_t143 * l1_t123 * l1_t319;
            let l1_t332 = l1_t324 * l1_t331;
            let l1_t334 = -l1_t142 * l1_t332 + l1_t320 * l1_t148;
            let l1_t335 = f64x8::splat(1.0) / l1_t150;
            let l1_t336 = l1_t334 * l1_t335;
            let l1_t337 = l1_t101 * l1_t336;
            let l1_t338 = l1_t158 + l1_t183 + l1_t187 - l1_t192 + l1_t206 + l1_t239 + l1_t241 - l1_t246 - l1_t251 + l1_t265 + l1_t337;
            let l1_tvrho0 = l0_t6 * l1_t338 + l1_t152 - l1_t33 + l1_t89 + l1_t91;
            let l1_t340 = -l0_t7 - l0_t84;
            let l1_t343 = ((l1_t44).select(f64x8::splat(0.0), f64x8::splat(4.0) / f64x8::splat(3.0) * l1_t47 * l1_t340));
            let l1_t344 = -l1_t340;
            let l1_t347 = ((l1_t51).select(f64x8::splat(0.0), f64x8::splat(4.0) / f64x8::splat(3.0) * l1_t52 * l1_t344));
            let l1_t349 = (l1_t343 + l1_t347) * l1_t59;
            let l1_t350 = l1_t349 * l1_t87;
            let l1_t351 = l1_t40 * l1_t350;
            let l1_t352 = l1_t349 * l1_t85;
            let l1_t353 = f64x8::splat(0.0197516734986138) * l1_t352;
            let l1_t356 = ((l1_t44).select(f64x8::splat(0.0), f64x8::splat(2.0) / f64x8::splat(3.0) * l1_t253 * l1_t340));
            let l1_t359 = ((l1_t51).select(f64x8::splat(0.0), f64x8::splat(2.0) / f64x8::splat(3.0) * l1_t257 * l1_t344));
            let l1_t361 = l1_t356 * f64x8::splat(0.5) + l1_t359 * f64x8::splat(0.5);
            let l1_t362 = l1_t151 * l1_t361;
            let l1_t363 = l1_t252 * l1_t362;
            let l1_t364 = f64x8::splat(3.0) * l1_t363;
            let l1_t365 = l1_t5 * l1_t361;
            let l1_t366 = l1_t275 * l1_t365;
            let l1_t370 = (l1_t158 + l1_t183 - l1_t187 - l1_t192 + l1_t351 + l1_t239 + l1_t353 - l1_t246 - l1_t251) * l1_t116;
            let l1_t372 = l1_t133 * l1_t361;
            let l1_t375 = f64x8::splat(3.0) * l1_t118 * l1_t372 - l1_t370 * l1_t119;
            let l1_t376 = l1_t375 * l1_t121;
            let l1_t377 = l1_t288 * l1_t376;
            let l1_t378 = l1_t287 * l1_t377;
            let l1_t382 = l1_t314 * l1_t288 * l1_t361;
            let l1_t385 = -l1_t272 - l1_t274 * l1_t366 / f64x8::splat(48.0) - l1_t285 * l1_t378 / f64x8::splat(3072.0) - l1_t307 - l1_t310 * l1_t382 / f64x8::splat(768.0);
            let l1_t386 = l1_param_beta * l1_t385;
            let l1_t388 = l1_t141 * l1_t375;
            let l1_t393 = -l1_t325 * l1_t388 * l1_t121 + l1_t143 * l1_t123 * l1_t385;
            let l1_t394 = l1_t324 * l1_t393;
            let l1_t396 = -l1_t142 * l1_t394 + l1_t386 * l1_t148;
            let l1_t397 = l1_t396 * l1_t335;
            let l1_t398 = l1_t101 * l1_t397;
            let l1_t399 = l1_t158 + l1_t183 - l1_t187 - l1_t192 + l1_t351 + l1_t239 + l1_t353 - l1_t246 - l1_t251 + l1_t364 + l1_t398;
            let l1_tvrho1 = l0_t6 * l1_t399 + l1_t152 - l1_t33 + l1_t89 + l1_t91;
            let l1_t401 = l0_t6 * l1_param_gamma;
            let l1_t402 = l1_t105 * l1_t56;
            let l1_t405 = l1_t402 * l1_t108 * l1_t404;
            let l1_t408 = l1_t115 * l1_t124 * l1_t103;
            let l1_t409 = l1_t408 * l1_t138;
            let l1_t411 = l1_t405 / f64x8::splat(96.0) + l1_t409 / f64x8::splat(1536.0);
            let l1_t412 = l1_param_beta * l1_t411;
            let l1_t415 = l1_t414 * l1_t141;
            let l1_t418 = l1_t415 * l1_t417;
            let l1_t419 = l1_t323 * l1_t123;
            let l1_t420 = l1_t419 * l1_t411;
            let l1_t422 = l1_t412 * l1_t148 - l1_t418 * l1_t420;
            let l1_tvsigma0 = l1_t401 * l1_t100 * l1_t422 * l1_t335;
            let l1_t427 = l1_t405 / f64x8::splat(48.0) + l1_t409 / f64x8::splat(768.0);
            let l1_t428 = l1_param_beta * l1_t427;
            let l1_t430 = l1_t419 * l1_t427;
            let l1_t432 = l1_t428 * l1_t148 - l1_t418 * l1_t430;
            let l1_t433 = l1_t100 * l1_t432;
            let l1_tvsigma1 = l1_t401 * l1_t433 * l1_t335;
            let l1_tvsigma2 = l1_tvsigma0;
            acc_zk = acc_zk + (w0 * (f64x8::splat(0.0) + l0_tzk0));
            acc_vrho_0 = acc_vrho_0 + (w0 * (f64x8::splat(0.0) + l0_tvrho0));
            acc_vrho_1 = acc_vrho_1 + (w0 * (f64x8::splat(0.0) + l0_tvrho1));
            acc_vsigma_0 = acc_vsigma_0 + (w0 * (f64x8::splat(0.0) + l0_tvsigma0));
            acc_vsigma_1 = acc_vsigma_1 + (w0 * (f64x8::splat(0.0) + l0_tvsigma1));
            acc_vsigma_2 = acc_vsigma_2 + (w0 * (f64x8::splat(0.0) + l0_tvsigma2));
            acc_zk = acc_zk + (w1 * (f64x8::splat(0.0) + l1_tzk0));
            acc_vrho_0 = acc_vrho_0 + (w1 * (f64x8::splat(0.0) + l1_tvrho0));
            acc_vrho_1 = acc_vrho_1 + (w1 * (f64x8::splat(0.0) + l1_tvrho1));
            acc_vsigma_0 = acc_vsigma_0 + (w1 * (f64x8::splat(0.0) + l1_tvsigma0));
            acc_vsigma_1 = acc_vsigma_1 + (w1 * (f64x8::splat(0.0) + l1_tvsigma1));
            acc_vsigma_2 = acc_vsigma_2 + (w1 * (f64x8::splat(0.0) + l1_tvsigma2));
        }
        store_add(zk, ip, m, acc_zk);
        store_strided(vrho, ip, m, 2, 0, acc_vrho_0);
        store_strided(vrho, ip, m, 2, 1, acc_vrho_1);
        store_strided(vsigma, ip, m, 3, 0, acc_vsigma_0);
        store_strided(vsigma, ip, m, 3, 1, acc_vsigma_1);
        store_strided(vsigma, ip, m, 3, 2, acc_vsigma_2);
        ip += 8;
    }
}
