//! FUSED_PBEH vxc unpol -- explicit SIMD (bit-exact): fused composite kernel (gga_x_pbe, gga_c_pbe).
//!
//! GENERATED by tools/translate_rayon/fuse.py from the auxiliaries'
//! maple2c bodies -- do not hand-edit. Shared subexpressions are
//! value-numbered across legs and the mix accumulation
//! (`out += w_k * (0.0 + v_k)`, in auxiliary order) is emitted inline, so
//! the result is bit-identical to `evaluate_mixed_gga` on the same legs.

#![allow(unused_imports, unused_variables, non_snake_case, clippy::excessive_precision, clippy::too_many_arguments, clippy::needless_return)]
use libxc_rkernel_math::constants::*;
use libxc_rkernel_math::simd;
use libxc_rkernel_math::wide::{f64x8, CmpEq, CmpGe, CmpGt, CmpLe, CmpLt, CmpNe};

const V_ZERO: f64x8 = f64x8::new([0.0; 8]);
const V_ONE: f64x8 = f64x8::new([1.0; 8]);

// Transcendentals in exact mode come from `libxc_rkernel_math::simd`,
// which is bit-identical / correctly-rounded per lane to the scalar calls
// the scalar kernel makes. In exact mode, the SIMD kernel produces output
// bit-identical to its scalar form.

/// Load 8 consecutive grid points.
///
/// The tail is padded by repeating the last element, not by zero-filling:
/// these formulas divide by rho, so a zero lane would raise inf/NaN in lanes
/// whose results are then discarded -- harmless to the answer, but it makes
/// any real NaN impossible to spot while debugging.
#[inline(always)]
fn load(s: &[f64], ip: usize, np: usize) -> f64x8 {
    if ip + 8 <= np {
        let mut b = [0.0f64; 8];
        b.copy_from_slice(&s[ip..ip + 8]);
        f64x8::new(b)
    } else {
        let mut b = [s[np - 1]; 8];
        b[..np - ip].copy_from_slice(&s[ip..np]);
        f64x8::new(b)
    }
}

/// Accumulate 8 consecutive grid points into an output array.
///
/// `+=`, not `=`. The scalar kernel writes `out[ip] += v`; a plain store is a
/// different operation in two ways. It keeps the sign of a negative zero where
/// `0.0 + -0.0` gives `+0.0` -- a bit difference the fingerprint gate reports
/// as a rejection even though no value changed (`gga_x_pbepow fxc` was
/// rejected on exactly this, 273 of 200,000 `v2sigma2` elements) -- and it
/// would discard whatever a caller had already put in the buffer.
#[inline(always)]
fn store_add(s: &mut [f64], ip: usize, m: usize, acc: f64x8) {
    let a: [f64; 8] = acc.into();
    if m == 8 {
        let mut b = [0.0f64; 8];
        b.copy_from_slice(&s[ip..ip + 8]);
        let r: [f64; 8] = (f64x8::new(b) + acc).into();
        s[ip..ip + 8].copy_from_slice(&r);
    } else {
        for k in 0..m {
            s[ip + k] += a[k];
        }
    }
}

#[allow(unused_variables, non_snake_case)]
pub fn fused_pbeh_vxc_unpol(
    rho: &[f64],
    sigma: &[f64],
    zk: &mut [f64],
    vrho: &mut [f64],
    vsigma: &mut [f64],
    w0: f64,
    w1: f64,
    l0_param_kappa: f64,
    l0_param_mu: f64,
    l1_param_gamma: f64,
    l1_param_BB: f64,
    l1_param_beta: f64,
    dens_threshold_0: f64,
    dens_threshold_1: f64,
    zeta_threshold: f64,
) {
    let np = zk.len();
    let w0 = f64x8::splat(w0);
    let w1 = f64x8::splat(w1);
    let l0_param_kappa = f64x8::splat(l0_param_kappa);
    let l0_param_mu = f64x8::splat(l0_param_mu);
    let l1_param_gamma = f64x8::splat(l1_param_gamma);
    let l1_param_BB = f64x8::splat(l1_param_BB);
    let l1_param_beta = f64x8::splat(l1_param_beta);
    let dens_threshold_0 = f64x8::splat(dens_threshold_0);
    let dens_threshold_1 = f64x8::splat(dens_threshold_1);
    let zeta_threshold = f64x8::splat(zeta_threshold);
    // Loop-invariant bindings (constants, parameters, thresholds):
    // the same statements maple2c emits per point, evaluated once.
    let l0_t3 = f64x8::splat(M_CBRT3);
    let l0_t4 = f64x8::splat(M_CBRTPI);
    let l0_t6 = l0_t3 / l0_t4;
    let l0_t7 = (f64x8::splat(1.0)).simd_le(zeta_threshold);
    let l0_t8 = zeta_threshold - f64x8::splat(1.0);
    let l0_t10 = ((l0_t7).select(l0_t8, (l0_t7).select(-l0_t8, f64x8::splat(0.0))));
    let l0_t11 = f64x8::splat(1.0) + l0_t10;
    let l0_t13 = (simd::cbrt(zeta_threshold));
    let l0_t15 = (simd::cbrt(l0_t11));
    let l0_t17 = (((l0_t11).simd_le(zeta_threshold)).select(l0_t13 * zeta_threshold, l0_t15 * l0_t11));
    let l0_t20 = f64x8::splat(M_CBRT6);
    let l0_t22 = f64x8::splat(M_PI) * f64x8::splat(M_PI);
    let l0_t23 = (simd::cbrt(l0_t22));
    let l0_t24 = l0_t23 * l0_t23;
    let l0_t25 = f64x8::splat(1.0) / l0_t24;
    let l0_t27 = f64x8::splat(M_CBRT2);
    let l0_t28 = l0_t27 * l0_t27;
    let l0_t56 = l0_param_kappa * l0_param_kappa;
    let l0_t78 = l0_t20 * l0_t25 * l0_t28;
    let l1_t2 = f64x8::splat(1.0) / f64x8::splat(M_PI);
    let l1_t3 = (simd::cbrt(l1_t2));
    let l1_t4 = l0_t3 * l1_t3;
    let l1_t5 = f64x8::splat(M_CBRT4);
    let l1_t6 = l1_t5 * l1_t5;
    let l1_t18 = l0_t3 * l0_t3;
    let l1_t19 = l1_t3 * l1_t3;
    let l1_t20 = l1_t18 * l1_t19;
    let l1_t36 = ((l0_t7).select(l0_t13 * zeta_threshold, f64x8::splat(1.0)));
    let l1_t43 = (f64x8::splat(2.0) * l1_t36 - f64x8::splat(2.0)) / (f64x8::splat(2.0) * l0_t27 - f64x8::splat(2.0));
    let l1_t58 = l0_t13 * l0_t13;
    let l1_t59 = ((l0_t7).select(l1_t58, f64x8::splat(1.0)));
    let l1_t60 = l1_t59 * l1_t59;
    let l1_t61 = l1_t60 * l1_t59;
    let l1_t62 = l1_param_gamma * l1_t61;
    let l1_t68 = f64x8::splat(1.0) / l1_t60;
    let l1_t70 = f64x8::splat(1.0) / l1_t3;
    let l1_t72 = l1_t68 * l1_t18 * l1_t70 * l1_t5;
    let l1_t75 = l1_param_BB * l1_param_beta;
    let l1_t76 = f64x8::splat(1.0) / l1_param_gamma;
    let l1_t79 = f64x8::splat(1.0) / l1_t61;
    let l1_t93 = l1_t60 * l1_t60;
    let l1_t94 = f64x8::splat(1.0) / l1_t93;
    let l1_t96 = f64x8::splat(1.0) / l1_t19;
    let l1_t97 = l0_t3 * l1_t96;
    let l1_t98 = l1_t97 * l1_t6;
    let l1_t104 = l1_param_beta * l1_t76;
    let l1_t125 = l1_t3 * l1_t6;
    let l1_t145 = l1_t43 * l0_t3;
    let l1_t170 = l1_param_gamma * l1_param_gamma;
    let l1_t171 = f64x8::splat(1.0) / l1_t170;
    let l1_t172 = l1_t75 * l1_t171;
    let l1_t179 = f64x8::splat(1.0) / l1_t93 / l1_t61;
    let l1_t180 = l0_t28 * l1_t179;
    let l1_t181 = l1_t180 * l0_t3;
    let l1_t182 = l1_t96 * l1_t6;
    let l1_t224 = l1_t18 * l1_t70 * l1_t5;
    let l1_t234 = l1_param_beta * l1_param_beta;
    let mut ip = 0usize;
    while ip < np {
        let m = (np - ip).min(8);
        let v_rho = load(rho, ip, np);
        let v_sigma = load(sigma, ip, np);
        let mut acc_zk = V_ZERO;
        let mut acc_vrho = V_ZERO;
        let mut acc_vsigma = V_ZERO;
        {
            let l0_t2 = (v_rho * f64x8::splat(0.5)).simd_le(dens_threshold_0);
            let l0_t18 = (simd::cbrt(v_rho));
            let l0_t30 = v_rho * v_rho;
            let l0_t31 = l0_t18 * l0_t18;
            let l0_t33 = f64x8::splat(1.0) / l0_t31 / l0_t30;
            let l0_t37 = l0_param_kappa + l0_param_mu * l0_t20 * l0_t25 * v_sigma * l0_t28 * l0_t33 / f64x8::splat(24.0);
            let l0_t42 = f64x8::splat(1.0) + l0_param_kappa * (f64x8::splat(1.0) - l0_param_kappa / l0_t37);
            let l0_t46 = ((l0_t2).select(f64x8::splat(0.0), -f64x8::splat(3.0) * f64x8::splat(0.125) * l0_t6 * l0_t17 * l0_t18 * l0_t42));
            let l0_tzk0 = f64x8::splat(2.0) * l0_t46;
            let l0_t52 = l0_t30 * v_rho;
            let l0_t58 = l0_t6 * l0_t17 / l0_t18 / l0_t52 * l0_t56;
            let l0_t59 = l0_t37 * l0_t37;
            let l0_t61 = f64x8::splat(1.0) / l0_t59 * l0_param_mu;
            let l0_t64 = l0_t25 * v_sigma * l0_t28;
            let l0_t65 = l0_t61 * l0_t20 * l0_t64;
            let l0_t69 = ((l0_t2).select(f64x8::splat(0.0), -l0_t6 * l0_t17 / l0_t31 * l0_t42 * f64x8::splat(0.125) + l0_t58 * l0_t65 / f64x8::splat(24.0)));
            let l0_tvrho0 = f64x8::splat(2.0) * v_rho * l0_t69 + f64x8::splat(2.0) * l0_t46;
            let l0_t79 = l0_t61 * l0_t78;
            let l0_t82 = ((l0_t2).select(f64x8::splat(0.0), -l0_t6 * l0_t17 / l0_t18 / l0_t30 * l0_t56 * l0_t79 * f64x8::splat(0.015625)));
            let l0_tvsigma0 = f64x8::splat(2.0) * v_rho * l0_t82;
            let l1_t10 = l1_t4 * l1_t6 / l0_t18;
            let l1_t12 = f64x8::splat(1.0) + f64x8::splat(0.053425) * l1_t10;
            let l1_t13 = ((l1_t10).sqrt());
            let l1_t16 = ((l1_t10) * (l1_t10).sqrt());
            let l1_t24 = l1_t20 * l1_t5 / l0_t31;
            let l1_t26 = f64x8::splat(3.79785) * l1_t13 + f64x8::splat(0.8969) * l1_t10 + f64x8::splat(0.204775) * l1_t16 + f64x8::splat(0.123235) * l1_t24;
            let l1_t29 = f64x8::splat(1.0) + f64x8::splat(16.081979498692537) / l1_t26;
            let l1_t30 = (simd::ln(l1_t29));
            let l1_t32 = f64x8::splat(0.0621814) * l1_t12 * l1_t30;
            let l1_t45 = f64x8::splat(1.0) + f64x8::splat(0.0278125) * l1_t10;
            let l1_t50 = f64x8::splat(5.1785) * l1_t13 + f64x8::splat(0.905775) * l1_t10 + f64x8::splat(0.1100325) * l1_t16 + f64x8::splat(0.1241775) * l1_t24;
            let l1_t53 = f64x8::splat(1.0) + f64x8::splat(29.608749977793437) / l1_t50;
            let l1_t54 = (simd::ln(l1_t53));
            let l1_t57 = f64x8::splat(0.0197516734986138) * l1_t43 * l1_t45 * l1_t54;
            let l1_t65 = f64x8::splat(1.0) / l0_t18 / l0_t30;
            let l1_t81 = (simd::exp(-(-l1_t32 + l1_t57) * l1_t76 * l1_t79));
            let l1_t82 = l1_t81 - f64x8::splat(1.0);
            let l1_t83 = f64x8::splat(1.0) / l1_t82;
            let l1_t84 = l1_t76 * l1_t83;
            let l1_t85 = v_sigma * v_sigma;
            let l1_t87 = l1_t75 * l1_t84 * l1_t85;
            let l1_t88 = l0_t30 * l0_t30;
            let l1_t90 = f64x8::splat(1.0) / l0_t31 / l1_t88;
            let l1_t92 = l1_t90 * l0_t28;
            let l1_t95 = l1_t92 * l1_t94;
            let l1_t99 = l1_t95 * l1_t98;
            let l1_t102 = v_sigma * l1_t65 * l0_t27 * l1_t72 / f64x8::splat(96.0) + l1_t87 * l1_t99 / f64x8::splat(3072.0);
            let l1_t103 = l1_param_beta * l1_t102;
            let l1_t107 = l1_t104 * l1_t83 * l1_t102 + f64x8::splat(1.0);
            let l1_t108 = f64x8::splat(1.0) / l1_t107;
            let l1_t109 = l1_t76 * l1_t108;
            let l1_t111 = l1_t103 * l1_t109 + f64x8::splat(1.0);
            let l1_t112 = (simd::ln(l1_t111));
            let l1_t113 = l1_t62 * l1_t112;
            let l1_tzk0 = -l1_t32 + l1_t57 + l1_t113;
            let l1_t115 = f64x8::splat(1.0) / l0_t18 / v_rho;
            let l1_t116 = l1_t6 * l1_t115;
            let l1_t118 = l1_t4 * l1_t116 * l1_t30;
            let l1_t119 = f64x8::splat(0.0011073470983333333) * l1_t118;
            let l1_t120 = l1_t26 * l1_t26;
            let l1_t121 = f64x8::splat(1.0) / l1_t120;
            let l1_t122 = l1_t12 * l1_t121;
            let l1_t124 = f64x8::splat(1.0) / l1_t13 * l0_t3;
            let l1_t126 = l1_t125 * l1_t115;
            let l1_t127 = l1_t124 * l1_t126;
            let l1_t129 = l1_t4 * l1_t116;
            let l1_t132 = l1_t13 * l0_t3;
            let l1_t133 = l1_t132 * l1_t126;
            let l1_t138 = l1_t20 * l1_t5 / l0_t31 / v_rho;
            let l1_t140 = -f64x8::splat(0.632975) * l1_t127 - f64x8::splat(0.29896666666666666) * l1_t129 - f64x8::splat(0.1023875) * l1_t133 - f64x8::splat(0.08215666666666667) * l1_t138;
            let l1_t141 = f64x8::splat(1.0) / l1_t29;
            let l1_t142 = l1_t140 * l1_t141;
            let l1_t143 = l1_t122 * l1_t142;
            let l1_t144 = f64x8::splat(1.0) * l1_t143;
            let l1_t148 = l1_t145 * l1_t125 * l1_t115 * l1_t54;
            let l1_t149 = f64x8::splat(0.00018311447306006544) * l1_t148;
            let l1_t150 = l1_t43 * l1_t45;
            let l1_t151 = l1_t50 * l1_t50;
            let l1_t152 = f64x8::splat(1.0) / l1_t151;
            let l1_t157 = -f64x8::splat(0.8630833333333333) * l1_t127 - f64x8::splat(0.301925) * l1_t129 - f64x8::splat(0.05501625) * l1_t133 - f64x8::splat(0.082785) * l1_t138;
            let l1_t159 = f64x8::splat(1.0) / l1_t53;
            let l1_t160 = l1_t152 * l1_t157 * l1_t159;
            let l1_t161 = l1_t150 * l1_t160;
            let l1_t162 = f64x8::splat(0.5848223622634646) * l1_t161;
            let l1_t165 = f64x8::splat(1.0) / l0_t18 / l0_t52;
            let l1_t173 = l1_t82 * l1_t82;
            let l1_t174 = f64x8::splat(1.0) / l1_t173;
            let l1_t175 = l1_t174 * l1_t85;
            let l1_t176 = l1_t175 * l1_t90;
            let l1_t177 = l1_t172 * l1_t176;
            let l1_t183 = l1_t119 + l1_t144 - l1_t149 - l1_t162;
            let l1_t184 = l1_t183 * l1_t81;
            let l1_t185 = l1_t182 * l1_t184;
            let l1_t186 = l1_t181 * l1_t185;
            let l1_t189 = l1_t88 * v_rho;
            let l1_t191 = f64x8::splat(1.0) / l0_t31 / l1_t189;
            let l1_t192 = l1_t191 * l0_t28;
            let l1_t193 = l1_t192 * l1_t94;
            let l1_t194 = l1_t193 * l1_t98;
            let l1_t197 = -f64x8::splat(7.0) / f64x8::splat(288.0) * v_sigma * l1_t165 * l0_t27 * l1_t72 + l1_t177 * l1_t186 / f64x8::splat(3072.0) - f64x8::splat(7.0) / f64x8::splat(4608.0) * l1_t87 * l1_t194;
            let l1_t198 = l1_param_beta * l1_t197;
            let l1_t200 = l1_t107 * l1_t107;
            let l1_t201 = f64x8::splat(1.0) / l1_t200;
            let l1_t202 = l1_t76 * l1_t201;
            let l1_t204 = l1_param_beta * l1_t171 * l1_t174;
            let l1_t206 = l1_t79 * l1_t81;
            let l1_t211 = l1_t204 * l1_t102 * l1_t183 * l1_t206 + l1_t104 * l1_t83 * l1_t197;
            let l1_t212 = l1_t202 * l1_t211;
            let l1_t214 = -l1_t103 * l1_t212 + l1_t198 * l1_t109;
            let l1_t215 = f64x8::splat(1.0) / l1_t111;
            let l1_t217 = l1_t62 * l1_t214 * l1_t215;
            let l1_tvrho0 = -l1_t32 + l1_t57 + l1_t113 + v_rho * (l1_t119 + l1_t144 - l1_t149 - l1_t162 + l1_t217);
            let l1_t220 = v_rho * l1_param_gamma;
            let l1_t228 = l1_t75 * l1_t84 * v_sigma;
            let l1_t231 = l1_t65 * l0_t27 * l1_t68 * l1_t224 / f64x8::splat(96.0) + l1_t228 * l1_t99 / f64x8::splat(1536.0);
            let l1_t232 = l1_param_beta * l1_t231;
            let l1_t235 = l1_t234 * l1_t102;
            let l1_t236 = l1_t235 * l1_t171;
            let l1_t237 = l1_t201 * l1_t83;
            let l1_t238 = l1_t237 * l1_t231;
            let l1_t240 = l1_t232 * l1_t109 - l1_t236 * l1_t238;
            let l1_tvsigma0 = l1_t220 * l1_t61 * l1_t240 * l1_t215;
            acc_zk = acc_zk + (w0 * (((v_rho).simd_lt(dens_threshold_0)).select(f64x8::splat(0.0), f64x8::splat(0.0) + l0_tzk0)));
            acc_vrho = acc_vrho + (w0 * (((v_rho).simd_lt(dens_threshold_0)).select(f64x8::splat(0.0), f64x8::splat(0.0) + l0_tvrho0)));
            acc_vsigma = acc_vsigma + (w0 * (((v_rho).simd_lt(dens_threshold_0)).select(f64x8::splat(0.0), f64x8::splat(0.0) + l0_tvsigma0)));
            acc_zk = acc_zk + (w1 * (((v_rho).simd_lt(dens_threshold_1)).select(f64x8::splat(0.0), f64x8::splat(0.0) + l1_tzk0)));
            acc_vrho = acc_vrho + (w1 * (((v_rho).simd_lt(dens_threshold_1)).select(f64x8::splat(0.0), f64x8::splat(0.0) + l1_tvrho0)));
            acc_vsigma = acc_vsigma + (w1 * (((v_rho).simd_lt(dens_threshold_1)).select(f64x8::splat(0.0), f64x8::splat(0.0) + l1_tvsigma0)));
        }
        store_add(zk, ip, m, acc_zk);
        store_add(vrho, ip, m, acc_vrho);
        store_add(vsigma, ip, m, acc_vsigma);
        ip += 8;
    }
}
