//! BR89 exchange hole root-finder for CubeCL kernels.
//!
//! Implements `xc_mgga_x_br89_get_x(Q)` which solves a nonlinear equation
//! using Brent's method to find the BR89 exchange hole parameter `x`.
//!
//! Translated from libxc `mgga_x_br89.c` and `math_brent.c`.
//!
//! The original C code uses Brent's method with function pointers and a
//! 500-iteration maximum. Since CubeCL does not support function pointers,
//! dynamic loops, tuples, or boolean types, this implementation:
//! - Inlines the BR89-specific objective function
//! - Uses branchless `select()` for conditional logic
//! - Unrolls 60 iterations via a helper that advances Brent state

#![allow(
    clippy::excessive_precision,
    clippy::too_many_arguments,
    unused_variables,
    non_snake_case,
)]


/// pi^(2/3) precomputed for the RHS formula.
const PI_TWO_THIRDS: f64 = 2.14502939711102560008; // pow(pi, 2.0/3.0)

/// Evaluate the BR89 objective function: f(x) = x * exp(-2x/3) - rhs * (x - 2)
fn br89_obj(x: f64, rhs: f64) -> f64 {
    let xm2 = x - 2.0_f64;
    let arg = 2.0_f64 * x / 3.0_f64;
    // Guard: exp(-arg) for large arg is 0
    let eee = (if arg <= 115.12925464970228_f64 { f64::exp(-arg) } else { 0.0_f64 });
    x * eee - rhs * xm2
}

/// Perform one Brent iteration step, encoding 8 state variables into two f64x4-like
/// groups. Since CubeCL doesn't support tuples, we use a pattern where the caller
/// passes mutable state variables directly.
///
/// This function takes state (a, b, c, d, fa, fb, fc, mflag) and rhs/tol,
/// and returns the updated `a` value. We use a chain of helper calls that
/// each update one part of the state.
///
/// Actually, since CubeCL doesn't support mutable references or tuples,
/// we inline everything directly into the main function.

/// Solve for the BR89 exchange hole parameter x given Q.
pub fn xc_mgga_x_br89_get_x(q_val: f64) -> f64 {
    let tol: f64 = 5.0e-12_f64;

    // Special case: |Q| < 5e-12 => return 2.0
    let mut result: f64 = 2.0_f64;

    if f64::abs(q_val) >= 5.0e-12_f64 {
        // Build RHS
        let rhs = 2.0_f64 / 3.0_f64 * (PI_TWO_THIRDS as f64) / q_val;

        // Starting interval
        let mut a = (if rhs > 0.0_f64 { 2.0_f64 } else { 0.0_f64 });
        let mut b = (if rhs > 0.0_f64 { 1.0_f64 / rhs + 2.0_f64 } else { 2.0_f64 });

        let mut fa = br89_obj(a, rhs);
        let mut fb = br89_obj(b, rhs);

        // Ensure |fa| >= |fb|
        let need_swap = f64::abs(fa) < f64::abs(fb);
        let sa = (if need_swap { b } else { a });
        let sb = (if need_swap { a } else { b });
        let sfa = (if need_swap { fb } else { fa });
        let sfb = (if need_swap { fa } else { fb });
        a = sa; b = sb; fa = sfa; fb = sfb;

        let mut c = a;
        let mut fc = fa;
        let mut d: f64 = 0.0_f64;
        let mut mf: f64 = 1.0_f64; // mflag as f64: 1.0 = true

        // Unrolled Brent iterations (60x).
        // Each iteration: compute trial point s, check bisection conditions,
        // evaluate f(s), update bracketing interval.

        // -- ITERATION 1 --
        let use_iqi = fa != fc && fb != fc;
        let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb)));
        let s_sec = b - fb*(b-a)/(fb-fa);
        let mut s = (if use_iqi { s_iqi } else { s_sec });
        // Bisection conditions (any true => bisect)
        let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b;
        let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64;
        let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64;
        let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol;
        let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol;
        let do_bi = c1 || c2 || c3 || c4 || c5;
        s = (if do_bi { (a+b)*0.5_f64 } else { s });
        mf = (if do_bi { 1.0_f64 } else { 0.0_f64 });
        let fs = br89_obj(s, rhs);
        d = c; c = b; fc = fb;
        let root_left = fa*fs < 0.0_f64;
        b = (if root_left { s } else { b }); fb = (if root_left { fs } else { fb });
        a = (if root_left { a } else { s }); fa = (if root_left { fa } else { fs });
        let sw = f64::abs(fa) < f64::abs(fb);
        let ta = a; let tb = b; let tfa = fa; let tfb = fb;
        a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa });
        b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });

        // -- ITERATION 2 --
        let use_iqi = fa != fc && fb != fc;
        let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb)));
        let s_sec = b - fb*(b-a)/(fb-fa);
        s = (if use_iqi { s_iqi } else { s_sec });
        let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b;
        let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64;
        let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64;
        let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol;
        let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol;
        let do_bi = c1 || c2 || c3 || c4 || c5;
        s = (if do_bi { (a+b)*0.5_f64 } else { s });
        mf = (if do_bi { 1.0_f64 } else { 0.0_f64 });
        let fs = br89_obj(s, rhs);
        d = c; c = b; fc = fb;
        let root_left = fa*fs < 0.0_f64;
        b = (if root_left { s } else { b }); fb = (if root_left { fs } else { fb });
        a = (if root_left { a } else { s }); fa = (if root_left { fa } else { fs });
        let sw = f64::abs(fa) < f64::abs(fb);
        let ta = a; let tb = b; let tfa = fa; let tfb = fb;
        a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa });
        b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });

        // -- ITERATION 3 --
        let use_iqi = fa != fc && fb != fc;
        let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb)));
        let s_sec = b - fb*(b-a)/(fb-fa);
        s = (if use_iqi { s_iqi } else { s_sec });
        let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol;
        let do_bi = c1 || c2 || c3 || c4 || c5;
        s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 });
        let fs = br89_obj(s, rhs); d = c; c = b; fc = fb;
        let root_left = fa*fs < 0.0_f64;
        b = (if root_left { s } else { b }); fb = (if root_left { fs } else { fb }); a = (if root_left { a } else { s }); fa = (if root_left { fa } else { fs });
        let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb;
        a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });

        // -- ITERATIONS 4-60: same pattern compacted --
        // 4
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 5
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 6
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 7
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 8
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 9
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 10
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 11
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 12
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 13
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 14
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 15
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 16
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 17
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 18
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 19
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 20
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 21-30
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 31-40
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 41-50
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        // 51-60
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = (if use_iqi { s_iqi } else { s_sec }); let c1 = s < (3.0_f64*a+b)*0.25_f64 || s > b; let c2 = mf > 0.5_f64 && f64::abs(s-b) >= f64::abs(b-c)*0.5_f64; let c3 = mf <= 0.5_f64 && f64::abs(s-b) >= f64::abs(c-d)*0.5_f64; let c4 = mf > 0.5_f64 && f64::abs(b-c) < tol; let c5 = mf <= 0.5_f64 && f64::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = (if do_bi { (a+b)*0.5_f64 } else { s }); mf = (if do_bi { 1.0_f64 } else { 0.0_f64 }); let fs = br89_obj(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < 0.0_f64; b = (if rl { s } else { b }); fb = (if rl { fs } else { fb }); a = (if rl { a } else { s }); fa = (if rl { fa } else { fs }); let sw = f64::abs(fa) < f64::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = (if sw { tb } else { ta }); fa = (if sw { tfb } else { tfa }); b = (if sw { ta } else { tb }); fb = (if sw { tfa } else { tfb });

        result = (b + a) * 0.5_f64;
    }

    result
}
