//! MGGA_C_TPSSLOC shard sub-crate mgga_c_tpssloc_p5 (parts 40..=53).
//!
//! Auto-generated by tools/split_per_functional_subcrate.py — do not hand-edit.

#![allow(unused_imports, unused_variables, non_snake_case, clippy::excessive_precision, clippy::too_many_arguments, clippy::needless_return)]

pub mod lxc_pol;

pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part40_v4rho3tau_4;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part41_v4rho3tau_5;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part42_v4rho3tau_6;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part43_v4rho3tau_7;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part44_v4rho2sigma2_0;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part45_v4rho2sigma2_1;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part46_v4rho2sigma2_2;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part47_v4rho2sigma2_3;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part48_v4rho2sigma2_4;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part49_v4rho2sigma2_5;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part50_v4rho2sigma2_6;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part51_v4rho2sigma2_7;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part52_v4rho2sigma2_8;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part53_v4rho2sigma2_9;
