[package]
name = "libxc-kernel-mgga_c_rmggac"
version = "0.1.0"
edition = "2024"

[dependencies]
cubecl = { version = "0.10.0", default-features = false, features = ["cpu"] }
libxc-kernel-math = { path = "../../math" }
libxc-kernel-mgga_c_rmggac_p0 = { path = "../mgga_c_rmggac_p0" }
libxc-kernel-mgga_c_rmggac_p1 = { path = "../mgga_c_rmggac_p1" }
libxc-kernel-mgga_c_rmggac_p2 = { path = "../mgga_c_rmggac_p2" }
libxc-kernel-mgga_c_rmggac_p3 = { path = "../mgga_c_rmggac_p3" }
libxc-kernel-mgga_c_rmggac_p4 = { path = "../mgga_c_rmggac_p4" }
libxc-kernel-mgga_c_rmggac_p5 = { path = "../mgga_c_rmggac_p5" }
libxc-kernel-mgga_c_rmggac_p6 = { path = "../mgga_c_rmggac_p6" }
libxc-kernel-mgga_c_rmggac_p7 = { path = "../mgga_c_rmggac_p7" }
libxc-kernel-mgga_c_rmggac_p8 = { path = "../mgga_c_rmggac_p8" }
libxc-kernel-mgga_c_rmggac_p9 = { path = "../mgga_c_rmggac_p9" }
libxc-kernel-mgga_c_rmggac_p10 = { path = "../mgga_c_rmggac_p10" }
libxc-kernel-mgga_c_rmggac_p11 = { path = "../mgga_c_rmggac_p11" }
libxc-kernel-mgga_c_rmggac_p12 = { path = "../mgga_c_rmggac_p12" }
