//! MGGA_C_TPSSLOC shard sub-crate mgga_c_tpssloc_p4 (parts 32..=39).
//!
//! Auto-generated by tools/split_per_functional_subcrate.py — do not hand-edit.

#![allow(unused_imports, unused_variables, non_snake_case, clippy::excessive_precision, clippy::too_many_arguments, clippy::needless_return)]

pub mod lxc_pol;

pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part32_v4rho3sigma_8;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part33_v4rho3sigma_9;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part34_v4rho3sigma_10;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part35_v4rho3sigma_11;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part36_v4rho3lapl_v4rho3tau_0;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part37_v4rho3tau_1;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part38_v4rho3tau_2;
pub use lxc_pol::mgga_c_tpssloc_lxc_pol_part39_v4rho3tau_3;
