[package]
name = "libxc-kernel-gga"
version = "0.1.0"
edition = "2024"

[features]
order-kxc = ["libxc-kernel-gga-1/order-kxc", "libxc-kernel-gga-2/order-kxc", "libxc-kernel-gga-4/order-kxc", "libxc-kernel-gga-7/order-kxc", "libxc-kernel-gga-8/order-kxc", "libxc-kernel-gga-9/order-kxc", "libxc-kernel-gga-10/order-kxc", "libxc-kernel-gga-16/order-kxc", "libxc-kernel-gga-17/order-kxc", "libxc-kernel-gga-18/order-kxc", "libxc-kernel-gga-19/order-kxc", "libxc-kernel-gga-20/order-kxc", "libxc-kernel-gga-21/order-kxc", "libxc-kernel-gga-22/order-kxc"]
order-lxc = ["order-kxc", "libxc-kernel-gga-1/order-lxc", "libxc-kernel-gga-2/order-lxc", "libxc-kernel-gga-4/order-lxc", "libxc-kernel-gga-7/order-lxc", "libxc-kernel-gga-8/order-lxc", "libxc-kernel-gga-9/order-lxc", "libxc-kernel-gga-10/order-lxc", "libxc-kernel-gga-16/order-lxc", "libxc-kernel-gga-17/order-lxc", "libxc-kernel-gga-18/order-lxc", "libxc-kernel-gga-19/order-lxc", "libxc-kernel-gga-20/order-lxc", "libxc-kernel-gga-21/order-lxc", "libxc-kernel-gga-22/order-lxc"]
all-orders = ["order-lxc"]

[dependencies]
cubecl = { version = "0.9.0", default-features = false, features = ["cpu"] }
libxc-kernel-math = { path = "../kernel-math" }
libxc-kernel-gga-1 = { path = "../kernel-gga-1" }
libxc-kernel-gga-2 = { path = "../kernel-gga-2" }
libxc-kernel-gga-3 = { path = "../kernel-gga-3" }
libxc-kernel-gga-4 = { path = "../kernel-gga-4" }
libxc-kernel-gga-5 = { path = "../kernel-gga-5" }
libxc-kernel-gga-6 = { path = "../kernel-gga-6" }
libxc-kernel-gga-7 = { path = "../kernel-gga-7" }
libxc-kernel-gga-8 = { path = "../kernel-gga-8" }
libxc-kernel-gga-9 = { path = "../kernel-gga-9" }
libxc-kernel-gga-10 = { path = "../kernel-gga-10" }
libxc-kernel-gga-11 = { path = "../kernel-gga-11" }
libxc-kernel-gga-12 = { path = "../kernel-gga-12" }
libxc-kernel-gga-13 = { path = "../kernel-gga-13" }
libxc-kernel-gga-14 = { path = "../kernel-gga-14" }
libxc-kernel-gga-15 = { path = "../kernel-gga-15" }
libxc-kernel-gga-16 = { path = "../kernel-gga-16" }
libxc-kernel-gga-17 = { path = "../kernel-gga-17" }
libxc-kernel-gga-18 = { path = "../kernel-gga-18" }
libxc-kernel-gga-19 = { path = "../kernel-gga-19" }
libxc-kernel-gga-20 = { path = "../kernel-gga-20" }
libxc-kernel-gga-21 = { path = "../kernel-gga-21" }
libxc-kernel-gga-22 = { path = "../kernel-gga-22" }
