//! Raw FFI bindings to C libxc 7.0.0, generated by bindgen at build time.
#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/libxc_bindings.rs"));
