[package]
name = "libxc-rkernel-mgga_c_tpssloc"
version = "0.1.0"
edition = "2024"

[dependencies]
libxc-rkernel-math = { path = "../../math" }
libxc-rkernel-mgga_c_tpssloc_p0 = { path = "../../mgga/mgga_c_tpssloc_p0" }
libxc-rkernel-mgga_c_tpssloc_p1 = { path = "../../mgga/mgga_c_tpssloc_p1" }
libxc-rkernel-mgga_c_tpssloc_p2 = { path = "../../mgga/mgga_c_tpssloc_p2" }
libxc-rkernel-mgga_c_tpssloc_p3 = { path = "../../mgga/mgga_c_tpssloc_p3" }
libxc-rkernel-mgga_c_tpssloc_p4 = { path = "../../mgga/mgga_c_tpssloc_p4" }
libxc-rkernel-mgga_c_tpssloc_p5 = { path = "../../mgga/mgga_c_tpssloc_p5" }
libxc-rkernel-mgga_c_tpssloc_p6 = { path = "../../mgga/mgga_c_tpssloc_p6" }
