[package]
name = "libxc-compat"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
libxc-core = { path = "../libxc-core" }
libxc-eval = { path = "../libxc-eval", default-features = false }
libxc-reval = { path = "../libxc-reval" }

[features]
default = []
c-abi = []
