//! MGGA_C_TPSS shard sub-crate mgga_c_tpss_p1 (parts 22..=22).
//!
//! Auto-generated by tools/split_per_functional_subcrate.py — do not hand-edit.

#![allow(unused_imports, unused_variables, non_snake_case, clippy::excessive_precision, clippy::too_many_arguments, clippy::needless_return)]

pub mod lxc_pol;

pub use lxc_pol::mgga_c_tpss_lxc_pol_part22_v4rho3sigma_4;
