//! Dispatch for `gga_x_gam` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_x_n12 as k;

/// libxc default for `param_CC_0_1`.
pub const PARAM_CC_0_1: f64 = 0.886102;
/// libxc default for `param_CC_0_2`.
pub const PARAM_CC_0_2: f64 = -5.73833;
/// libxc default for `param_CC_0_3`.
pub const PARAM_CC_0_3: f64 = 8.60197;
/// libxc default for `param_CC_1_1`.
pub const PARAM_CC_1_1: f64 = -4.78787;
/// libxc default for `param_CC_1_2`.
pub const PARAM_CC_1_2: f64 = 3.90989;
/// libxc default for `param_CC_1_3`.
pub const PARAM_CC_1_3: f64 = -2.11611;
/// libxc default for `param_CC_1_0`.
pub const PARAM_CC_1_0: f64 = -0.786018;
/// libxc default for `param_CC_2_1`.
pub const PARAM_CC_2_1: f64 = 14.4363;
/// libxc default for `param_CC_2_2`.
pub const PARAM_CC_2_2: f64 = 8.42735;
/// libxc default for `param_CC_2_3`.
pub const PARAM_CC_2_3: f64 = -6.21552;
/// libxc default for `param_CC_2_0`.
pub const PARAM_CC_2_0: f64 = 0.802575;
/// libxc default for `param_CC_3_1`.
pub const PARAM_CC_3_1: f64 = -13.4598;
/// libxc default for `param_CC_3_2`.
pub const PARAM_CC_3_2: f64 = 1.52355;
/// libxc default for `param_CC_3_3`.
pub const PARAM_CC_3_3: f64 = -10.0530;
/// libxc default for `param_CC_3_0`.
pub const PARAM_CC_3_0: f64 = -0.142331;
/// libxc default for `param_CC_0_0`.
pub const PARAM_CC_0_0: f64 = 1.32730;

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_x_n12_exc_unpol],
        [k::vxc_unpol::gga_x_n12_vxc_unpol],
        [k::fxc_unpol::gga_x_n12_fxc_unpol],
        [k::kxc_unpol::gga_x_n12_kxc_unpol],
        [k::lxc_unpol::gga_x_n12_lxc_unpol],
        [k::exc_pol::gga_x_n12_exc_pol],
        [k::vxc_pol::gga_x_n12_vxc_pol],
        [k::fxc_pol::gga_x_n12_fxc_pol],
        [k::kxc_pol::gga_x_n12_kxc_pol],
        [k::lxc_pol::gga_x_n12_lxc_pol],
        params = (PARAM_CC_0_1, PARAM_CC_0_2, PARAM_CC_0_3, PARAM_CC_1_1, PARAM_CC_1_2, PARAM_CC_1_3, PARAM_CC_1_0, PARAM_CC_2_1, PARAM_CC_2_2, PARAM_CC_2_3, PARAM_CC_2_0, PARAM_CC_3_1, PARAM_CC_3_2, PARAM_CC_3_3, PARAM_CC_3_0, PARAM_CC_0_0)
    )
}
