//! Dispatch for `gga_c_p86vwn` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_c_p86vwn as k;

/// libxc default for `param_aa`.
pub const PARAM_AA: f64 = 0.001667;
/// libxc default for `param_bb`.
pub const PARAM_BB: f64 = 0.002568;
/// libxc default for `param_ftilde`.
pub const PARAM_FTILDE: f64 = 0.19195;
/// libxc default for `param_malpha`.
pub const PARAM_MALPHA: f64 = 0.023266;
/// libxc default for `param_mbeta`.
pub const PARAM_MBETA: f64 = 7.389e-6;
/// libxc default for `param_mgamma`.
pub const PARAM_MGAMMA: f64 = 8.723;
/// libxc default for `param_mdelta`.
pub const PARAM_MDELTA: f64 = 0.472;

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_c_p86vwn_exc_unpol],
        [k::vxc_unpol::gga_c_p86vwn_vxc_unpol],
        [k::fxc_unpol::gga_c_p86vwn_fxc_unpol],
        [k::kxc_unpol::gga_c_p86vwn_kxc_unpol],
        [k::lxc_unpol::gga_c_p86vwn_lxc_unpol],
        [k::exc_pol::gga_c_p86vwn_exc_pol],
        [k::vxc_pol::gga_c_p86vwn_vxc_pol],
        [k::fxc_pol::gga_c_p86vwn_fxc_pol],
        [k::kxc_pol::gga_c_p86vwn_kxc_pol],
        [k::lxc_pol::gga_c_p86vwn_lxc_pol],
        params = (PARAM_AA, PARAM_BB, PARAM_FTILDE, PARAM_MALPHA, PARAM_MBETA, PARAM_MGAMMA, PARAM_MDELTA)
    )
}
