//! Dispatch for `gga_c_chachiyo` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_c_chachiyo as k;

/// libxc default for `param_af`.
pub const PARAM_AF: f64 = -0.007772675;
/// libxc default for `param_ap`.
pub const PARAM_AP: f64 = -0.01554535;
/// libxc default for `param_bf`.
pub const PARAM_BF: f64 = 27.4203609;
/// libxc default for `param_bp`.
pub const PARAM_BP: f64 = 20.4562557;
/// libxc default for `param_cf`.
pub const PARAM_CF: f64 = 27.4203609;
/// libxc default for `param_cp`.
pub const PARAM_CP: f64 = 20.4562557;
/// libxc default for `param_h`.
pub const PARAM_H: f64 = 0.06672632;

pub fn dispatch<'a>(
    input: &'a GgaInput<'a>,
    output: &'a mut GgaOutput<'a>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_c_chachiyo_exc_unpol],
        [k::vxc_unpol::gga_c_chachiyo_vxc_unpol],
        [k::fxc_unpol::gga_c_chachiyo_fxc_unpol],
        [k::kxc_unpol::gga_c_chachiyo_kxc_unpol],
        [k::lxc_unpol::gga_c_chachiyo_lxc_unpol],
        [k::exc_pol::gga_c_chachiyo_exc_pol],
        [k::vxc_pol::gga_c_chachiyo_vxc_pol],
        [k::fxc_pol::gga_c_chachiyo_fxc_pol],
        [k::kxc_pol::gga_c_chachiyo_kxc_pol],
        [k::lxc_pol::gga_c_chachiyo_lxc_pol],
        params = (PARAM_AF, PARAM_AP, PARAM_BF, PARAM_BP, PARAM_CF, PARAM_CP, PARAM_H)
    )
}
