//! Dispatch for `gga_c_lypr` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_c_lypr as k;

/// libxc default for `param_m1`.
pub const PARAM_M1: f64 = 0.15283842794759825;
/// libxc default for `param_omega`.
pub const PARAM_OMEGA: f64 = 0.33;
/// libxc default for `param_d`.
pub const PARAM_D: f64 = 0.349;
/// libxc default for `param_m2`.
pub const PARAM_M2: f64 = 0.8733624454148472;
/// libxc default for `param_b`.
pub const PARAM_B: f64 = 0.132;
/// libxc default for `param_c`.
pub const PARAM_C: f64 = 0.2533;
/// libxc default for `param_a`.
pub const PARAM_A: f64 = 0.04918;

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_c_lypr_exc_unpol],
        [k::vxc_unpol::gga_c_lypr_vxc_unpol],
        [k::fxc_unpol::gga_c_lypr_fxc_unpol],
        [k::kxc_unpol::gga_c_lypr_kxc_unpol],
        [k::lxc_unpol::gga_c_lypr_lxc_unpol],
        [k::exc_pol::gga_c_lypr_exc_pol],
        [k::vxc_pol::gga_c_lypr_vxc_pol],
        [k::fxc_pol::gga_c_lypr_fxc_pol],
        [k::kxc_pol::gga_c_lypr_kxc_pol],
        [k::lxc_pol::gga_c_lypr_lxc_pol],
        params = (PARAM_M1, PARAM_OMEGA, PARAM_D, PARAM_M2, PARAM_B, PARAM_C, PARAM_A)
    )
}
