//! Dispatch for `gga_c_p86vwn_ft` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_c_p86vwn as k;

/// libxc's raw integer id for this functional.
pub const ID: u16 = 253;

/// libxc default for `param_aa`.
pub const PARAM_AA: f64 = 0.001667;
/// libxc default for `param_bb`.
pub const PARAM_BB: f64 = 0.002568;
/// libxc default for `param_ftilde`.
pub const PARAM_FTILDE: f64 = 0.19199566167376364;
/// libxc default for `param_malpha`.
pub const PARAM_MALPHA: f64 = 0.023266;
/// libxc default for `param_mbeta`.
pub const PARAM_MBETA: f64 = 7.389e-6;
/// libxc default for `param_mgamma`.
pub const PARAM_MGAMMA: f64 = 8.723;
/// libxc default for `param_mdelta`.
pub const PARAM_MDELTA: f64 = 0.472;

/// Number of libxc `ext_params` this dispatch accepts at runtime.
pub const N_EXT_PARAMS: usize = 7;

/// libxc `ext_params` names, in libxc's own order.
pub const EXT_PARAM_NAMES: [&str; 7] = ["_malpha", "_mbeta", "_mgamma", "_mdelta", "_aa", "_bb", "_ftilde"];

/// Permutation: libxc `ext_params` index -> this kernel's argument slot.
///
/// `usize::MAX` marks an ext_param the kernel does not consume. Built by
/// *name* in `extract_params.py`, not by position -- the two orders differ for
/// most functionals, because libxc's order is its C params-struct order
/// (`util.c::copy_params` writes `ext_params[i]` into struct slot `i`) while
/// the kernel's is the maple2c argument order.
/// | libxc `ext_params` name | kernel argument |
/// |---|---|
/// | `_malpha` | `param_malpha` |
/// | `_mbeta` | `param_mbeta` |
/// | `_mgamma` | `param_mgamma` |
/// | `_mdelta` | `param_mdelta` |
/// | `_aa` | `param_aa` |
/// | `_bb` | `param_bb` |
/// | `_ftilde` | `param_ftilde` |
pub const EXT_TO_KERNEL: [usize; 7] = [3, 4, 5, 6, 0, 1, 2];

/// Compiled-in libxc defaults, in kernel argument order.
pub const DEFAULTS: [f64; 7] = [PARAM_AA, PARAM_BB, PARAM_FTILDE, PARAM_MALPHA, PARAM_MBETA, PARAM_MGAMMA, PARAM_MDELTA];

/// Same as [`dispatch`], with an optional caller-supplied `ext_params` array
/// in libxc's own order.
///
/// `None` is exactly [`dispatch`] -- same constants, same bits. `Some(e)`
/// starts from those defaults and overwrites only the slots `e` actually
/// feeds, so an ext_param the kernel ignores cannot disturb one it uses.
pub fn dispatch_with(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
    ext: Option<&[f64]>,
) -> Result<(), LibxcRsError> {
    let mut p = DEFAULTS;
    if let Some(e) = ext {
        if e.len() != N_EXT_PARAMS {
            return Err(LibxcRsError::ExtParamCountMismatch {
                id: libxc_core::model::FunctionalId(ID),
                expected: N_EXT_PARAMS,
                actual: e.len(),
            });
        }
        for (i, &slot) in EXT_TO_KERNEL.iter().enumerate() {
            if slot != usize::MAX {
                p[slot] = e[i];
            }
        }
    }
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_c_p86vwn_exc_unpol],
        [k::vxc_unpol::gga_c_p86vwn_vxc_unpol],
        [k::fxc_unpol::gga_c_p86vwn_fxc_unpol],
        [k::kxc_unpol::gga_c_p86vwn_kxc_unpol],
        [k::lxc_unpol::gga_c_p86vwn_lxc_unpol],
        [k::exc_pol::gga_c_p86vwn_exc_pol],
        [k::vxc_pol::gga_c_p86vwn_vxc_pol],
        [k::fxc_pol::gga_c_p86vwn_fxc_pol],
        [k::kxc_pol::gga_c_p86vwn_kxc_pol],
        [k::lxc_pol::gga_c_p86vwn_lxc_pol],
        params = (p[0], p[1], p[2], p[3], p[4], p[5], p[6])
    )
}

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_c_p86vwn_exc_unpol],
        [k::vxc_unpol::gga_c_p86vwn_vxc_unpol],
        [k::fxc_unpol::gga_c_p86vwn_fxc_unpol],
        [k::kxc_unpol::gga_c_p86vwn_kxc_unpol],
        [k::lxc_unpol::gga_c_p86vwn_lxc_unpol],
        [k::exc_pol::gga_c_p86vwn_exc_pol],
        [k::vxc_pol::gga_c_p86vwn_vxc_pol],
        [k::fxc_pol::gga_c_p86vwn_fxc_pol],
        [k::kxc_pol::gga_c_p86vwn_kxc_pol],
        [k::lxc_pol::gga_c_p86vwn_lxc_pol],
        params = (PARAM_AA, PARAM_BB, PARAM_FTILDE, PARAM_MALPHA, PARAM_MBETA, PARAM_MGAMMA, PARAM_MDELTA)
    )
}
