//! Dispatch for `gga_x_ol2` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_x_ol2 as k;

/// libxc default for `param_bb`.
pub const PARAM_BB: f64 = 0.09564574034649151285038696952714226444963;
/// libxc default for `param_cc`.
pub const PARAM_CC: f64 = 4.098833606342553442039881031486386917472;
/// libxc default for `param_aa`.
pub const PARAM_AA: f64 = 0.09564574034649151285038696952714226444963;

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_x_ol2_exc_unpol],
        [k::vxc_unpol::gga_x_ol2_vxc_unpol],
        [k::fxc_unpol::gga_x_ol2_fxc_unpol],
        [k::kxc_unpol::gga_x_ol2_kxc_unpol],
        [k::lxc_unpol::gga_x_ol2_lxc_unpol],
        [k::exc_pol::gga_x_ol2_exc_pol],
        [k::vxc_pol::gga_x_ol2_vxc_pol],
        [k::fxc_pol::gga_x_ol2_fxc_pol],
        [k::kxc_pol::gga_x_ol2_kxc_pol],
        [k::lxc_pol::gga_x_ol2_lxc_pol],
        params = (PARAM_BB, PARAM_CC, PARAM_AA)
    )
}
