//! Dispatch for `gga_xc_th_fl` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_xc_th1 as k;

/// libxc default for `param_omega_0`.
pub const PARAM_OMEGA_0: f64 = -0.106141e01;
/// libxc default for `param_omega_1`.
pub const PARAM_OMEGA_1: f64 = 0.898203e00;
/// libxc default for `param_omega_2`.
pub const PARAM_OMEGA_2: f64 = -0.134439e01;
/// libxc default for `param_omega_3`.
pub const PARAM_OMEGA_3: f64 = 0.302369e00;
/// libxc default for `param_omega_4`.
pub const PARAM_OMEGA_4: f64 = 0.0;
/// libxc default for `param_omega_5`.
pub const PARAM_OMEGA_5: f64 = 0.0;
/// libxc default for `param_omega_6`.
pub const PARAM_OMEGA_6: f64 = 0.0;
/// libxc default for `param_omega_7`.
pub const PARAM_OMEGA_7: f64 = 0.0;
/// libxc default for `param_omega_8`.
pub const PARAM_OMEGA_8: f64 = 0.0;
/// libxc default for `param_omega_9`.
pub const PARAM_OMEGA_9: f64 = 0.0;
/// libxc default for `param_omega_10`.
pub const PARAM_OMEGA_10: f64 = 0.0;
/// libxc default for `param_omega_11`.
pub const PARAM_OMEGA_11: f64 = 0.0;
/// libxc default for `param_omega_12`.
pub const PARAM_OMEGA_12: f64 = 0.0;
/// libxc default for `param_omega_13`.
pub const PARAM_OMEGA_13: f64 = 0.0;
/// libxc default for `param_omega_14`.
pub const PARAM_OMEGA_14: f64 = 0.0;
/// libxc default for `param_omega_15`.
pub const PARAM_OMEGA_15: f64 = 0.0;
/// libxc default for `param_omega_20`.
pub const PARAM_OMEGA_20: f64 = 0.0;
/// libxc default for `param_omega_16`.
pub const PARAM_OMEGA_16: f64 = 0.0;
/// libxc default for `param_omega_17`.
pub const PARAM_OMEGA_17: f64 = 0.0;
/// libxc default for `param_omega_18`.
pub const PARAM_OMEGA_18: f64 = 0.0;
/// libxc default for `param_omega_19`.
pub const PARAM_OMEGA_19: f64 = 0.0;

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_xc_th1_exc_unpol],
        [k::vxc_unpol::gga_xc_th1_vxc_unpol],
        [k::fxc_unpol::gga_xc_th1_fxc_unpol],
        [k::kxc_unpol::gga_xc_th1_kxc_unpol],
        [k::lxc_unpol::gga_xc_th1_lxc_unpol],
        [k::exc_pol::gga_xc_th1_exc_pol],
        [k::vxc_pol::gga_xc_th1_vxc_pol],
        [k::fxc_pol::gga_xc_th1_fxc_pol],
        [k::kxc_pol::gga_xc_th1_kxc_pol],
        [k::lxc_pol::gga_xc_th1_lxc_pol],
        params = (PARAM_OMEGA_0, PARAM_OMEGA_1, PARAM_OMEGA_2, PARAM_OMEGA_3, PARAM_OMEGA_4, PARAM_OMEGA_5, PARAM_OMEGA_6, PARAM_OMEGA_7, PARAM_OMEGA_8, PARAM_OMEGA_9, PARAM_OMEGA_10, PARAM_OMEGA_11, PARAM_OMEGA_12, PARAM_OMEGA_13, PARAM_OMEGA_14, PARAM_OMEGA_15, PARAM_OMEGA_20, PARAM_OMEGA_16, PARAM_OMEGA_17, PARAM_OMEGA_18, PARAM_OMEGA_19)
    )
}
