//! Dispatch for `gga_x_pbefe` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_x_pbe as k;

/// libxc default for `param_kappa`.
pub const PARAM_KAPPA: f64 = 0.437;
/// libxc default for `param_mu`.
pub const PARAM_MU: f64 = 0.346;

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_x_pbe_exc_unpol],
        [k::vxc_unpol::gga_x_pbe_vxc_unpol],
        [k::fxc_unpol::gga_x_pbe_fxc_unpol],
        [k::kxc_unpol::gga_x_pbe_kxc_unpol],
        [k::lxc_unpol::gga_x_pbe_lxc_unpol],
        [k::exc_pol::gga_x_pbe_exc_pol],
        [k::vxc_pol::gga_x_pbe_vxc_pol],
        [k::fxc_pol::gga_x_pbe_fxc_pol],
        [k::kxc_pol::gga_x_pbe_kxc_pol],
        [k::lxc_pol::gga_x_pbe_lxc_pol],
        params = (PARAM_KAPPA, PARAM_MU)
    )
}
