//! Dispatch for `gga_c_optc` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_c_optc as k;

/// libxc default for `param_c1`.
pub const PARAM_C1: f64 = 1.1015;
/// libxc default for `param_c2`.
pub const PARAM_C2: f64 = 0.6625;

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_c_optc_exc_unpol],
        [k::vxc_unpol::gga_c_optc_vxc_unpol],
        [k::fxc_unpol::gga_c_optc_fxc_unpol],
        [k::kxc_unpol::gga_c_optc_kxc_unpol],
        [k::lxc_unpol::gga_c_optc_lxc_unpol],
        [k::exc_pol::gga_c_optc_exc_pol],
        [k::vxc_pol::gga_c_optc_vxc_pol],
        [k::fxc_pol::gga_c_optc_fxc_pol],
        [k::kxc_pol::gga_c_optc_kxc_pol],
        [k::lxc_pol::gga_c_optc_lxc_pol],
        params = (PARAM_C1, PARAM_C2)
    )
}
