//! Dispatch for `gga_k_dk` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_k_dk as k;

/// libxc's raw integer id for this functional.
pub const ID: u16 = 516;

/// libxc default for `param_aa_1`.
pub const PARAM_AA_1: f64 = 0.002894915269207321;
/// libxc default for `param_aa_2`.
pub const PARAM_AA_2: f64 = 0.00013261312158741373;
/// libxc default for `param_aa_3`.
pub const PARAM_AA_3: f64 = -5.540398637453735e-07;
/// libxc default for `param_aa_4`.
pub const PARAM_AA_4: f64 = 2.297777234019837e-09;
/// libxc default for `param_aa_0`.
pub const PARAM_AA_0: f64 = 1.0;
/// libxc default for `param_bb_1`.
pub const PARAM_BB_1: f64 = -0.00015236396153722742;
/// libxc default for `param_bb_2`.
pub const PARAM_BB_2: f64 = 9.284072099806483e-05;
/// libxc default for `param_bb_3`.
pub const PARAM_BB_3: f64 = 8.398620696364157e-08;
/// libxc default for `param_bb_4`.
pub const PARAM_BB_4: f64 = 0.0;
/// libxc default for `param_bb_0`.
pub const PARAM_BB_0: f64 = 1.0;

/// Number of libxc `ext_params` this dispatch accepts at runtime.
pub const N_EXT_PARAMS: usize = 10;

/// libxc `ext_params` names, in libxc's own order.
pub const EXT_PARAM_NAMES: [&str; 10] = ["_a0", "_a1", "_a2", "_a3", "_a4", "_b0", "_b1", "_b2", "_b3", "_b4"];

/// Permutation: libxc `ext_params` index -> this kernel's argument slot.
///
/// `usize::MAX` marks an ext_param the kernel does not consume. Built by
/// *name* in `extract_params.py`, not by position -- the two orders differ for
/// most functionals, because libxc's order is its C params-struct order
/// (`util.c::copy_params` writes `ext_params[i]` into struct slot `i`) while
/// the kernel's is the maple2c argument order.
/// | libxc `ext_params` name | kernel argument |
/// |---|---|
/// | `_a0` | `param_aa_0` |
/// | `_a1` | `param_aa_1` |
/// | `_a2` | `param_aa_2` |
/// | `_a3` | `param_aa_3` |
/// | `_a4` | `param_aa_4` |
/// | `_b0` | `param_bb_0` |
/// | `_b1` | `param_bb_1` |
/// | `_b2` | `param_bb_2` |
/// | `_b3` | `param_bb_3` |
/// | `_b4` | `param_bb_4` |
pub const EXT_TO_KERNEL: [usize; 10] = [4, 0, 1, 2, 3, 9, 5, 6, 7, 8];

/// Compiled-in libxc defaults, in kernel argument order.
pub const DEFAULTS: [f64; 10] = [PARAM_AA_1, PARAM_AA_2, PARAM_AA_3, PARAM_AA_4, PARAM_AA_0, PARAM_BB_1, PARAM_BB_2, PARAM_BB_3, PARAM_BB_4, PARAM_BB_0];

/// Same as [`dispatch`], with an optional caller-supplied `ext_params` array
/// in libxc's own order.
///
/// `None` is exactly [`dispatch`] -- same constants, same bits. `Some(e)`
/// starts from those defaults and overwrites only the slots `e` actually
/// feeds, so an ext_param the kernel ignores cannot disturb one it uses.
pub fn dispatch_with(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
    ext: Option<&[f64]>,
) -> Result<(), LibxcRsError> {
    let mut p = DEFAULTS;
    if let Some(e) = ext {
        if e.len() != N_EXT_PARAMS {
            return Err(LibxcRsError::ExtParamCountMismatch {
                id: libxc_core::model::FunctionalId(ID),
                expected: N_EXT_PARAMS,
                actual: e.len(),
            });
        }
        for (i, &slot) in EXT_TO_KERNEL.iter().enumerate() {
            if slot != usize::MAX {
                p[slot] = e[i];
            }
        }
    }
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_k_dk_exc_unpol],
        [k::vxc_unpol::gga_k_dk_vxc_unpol],
        [k::fxc_unpol::gga_k_dk_fxc_unpol],
        [k::kxc_unpol::gga_k_dk_kxc_unpol],
        [k::lxc_unpol::gga_k_dk_lxc_unpol],
        [k::exc_pol::gga_k_dk_exc_pol],
        [k::vxc_pol::gga_k_dk_vxc_pol],
        [k::fxc_pol::gga_k_dk_fxc_pol],
        [k::kxc_pol::gga_k_dk_kxc_pol],
        [k::lxc_pol::gga_k_dk_lxc_pol],
        params = (p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9])
    )
}

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_k_dk_exc_unpol],
        [k::vxc_unpol::gga_k_dk_vxc_unpol],
        [k::fxc_unpol::gga_k_dk_fxc_unpol],
        [k::kxc_unpol::gga_k_dk_kxc_unpol],
        [k::lxc_unpol::gga_k_dk_lxc_unpol],
        [k::exc_pol::gga_k_dk_exc_pol],
        [k::vxc_pol::gga_k_dk_vxc_pol],
        [k::fxc_pol::gga_k_dk_fxc_pol],
        [k::kxc_pol::gga_k_dk_kxc_pol],
        [k::lxc_pol::gga_k_dk_lxc_pol],
        params = (PARAM_AA_1, PARAM_AA_2, PARAM_AA_3, PARAM_AA_4, PARAM_AA_0, PARAM_BB_1, PARAM_BB_2, PARAM_BB_3, PARAM_BB_4, PARAM_BB_0)
    )
}
