//! Dispatch for `gga_c_ccdf` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_c_ccdf as k;

/// libxc default for `param_c1`.
pub const PARAM_C1: f64 = -0.0468;
/// libxc default for `param_c2`.
pub const PARAM_C2: f64 = 0.023;
/// libxc default for `param_c3`.
pub const PARAM_C3: f64 = 0.544;
/// libxc default for `param_c4`.
pub const PARAM_C4: f64 = 23.401;
/// libxc default for `param_c5`.
pub const PARAM_C5: f64 = 0.479;

pub fn dispatch<'a>(
    input: &'a GgaInput<'a>,
    output: &'a mut GgaOutput<'a>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_c_ccdf_exc_unpol],
        [k::vxc_unpol::gga_c_ccdf_vxc_unpol],
        [k::fxc_unpol::gga_c_ccdf_fxc_unpol],
        [k::kxc_unpol::gga_c_ccdf_kxc_unpol],
        [k::lxc_unpol::gga_c_ccdf_lxc_unpol],
        [k::exc_pol::gga_c_ccdf_exc_pol],
        [k::vxc_pol::gga_c_ccdf_vxc_pol],
        [k::fxc_pol::gga_c_ccdf_fxc_pol],
        [k::kxc_pol::gga_c_ccdf_kxc_pol],
        [k::lxc_pol::gga_c_ccdf_lxc_pol],
        params = (PARAM_C1, PARAM_C2, PARAM_C3, PARAM_C4, PARAM_C5)
    )
}
