//! Dispatch for `gga_x_pbe_erf_gws` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_x_pbe_erf_gws as k;

/// libxc default for `param_ax`.
pub const PARAM_AX: f64 = 19.0;
/// libxc default for `param_b_PBE`.
pub const PARAM_B_PBE: f64 = 0.2195149727645171;
/// libxc default for `param_kappa`.
pub const PARAM_KAPPA: f64 = 0.8040;
/// libxc default for `param_hyb_omega_0`.
pub const PARAM_HYB_OMEGA_0: f64 = 0.5;

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_x_pbe_erf_gws_exc_unpol],
        [k::vxc_unpol::gga_x_pbe_erf_gws_vxc_unpol],
        [k::fxc_unpol::gga_x_pbe_erf_gws_fxc_unpol],
        [k::kxc_unpol::gga_x_pbe_erf_gws_kxc_unpol],
        [k::lxc_unpol::gga_x_pbe_erf_gws_lxc_unpol],
        [k::exc_pol::gga_x_pbe_erf_gws_exc_pol],
        [k::vxc_pol::gga_x_pbe_erf_gws_vxc_pol],
        [k::fxc_pol::gga_x_pbe_erf_gws_fxc_pol],
        [k::kxc_pol::gga_x_pbe_erf_gws_kxc_pol],
        [k::lxc_pol::gga_x_pbe_erf_gws_lxc_pol],
        params = (PARAM_AX, PARAM_B_PBE, PARAM_KAPPA, PARAM_HYB_OMEGA_0)
    )
}
