//! Dispatch for `gga_c_acgga` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_c_acgga as k;



pub fn dispatch<'a>(
    input: &'a GgaInput<'a>,
    output: &'a mut GgaOutput<'a>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_c_acgga_exc_unpol],
        [k::vxc_unpol::gga_c_acgga_vxc_unpol],
        [k::fxc_unpol::gga_c_acgga_fxc_unpol],
        [k::kxc_unpol::gga_c_acgga_kxc_unpol],
        [k::lxc_unpol::gga_c_acgga_lxc_unpol],
        [k::exc_pol::gga_c_acgga_exc_pol],
        [k::vxc_pol::gga_c_acgga_vxc_pol],
        [k::fxc_pol::gga_c_acgga_fxc_pol],
        [k::kxc_pol::gga_c_acgga_kxc_pol],
        [k::lxc_pol::gga_c_acgga_lxc_pol],
        params = ()
    )
}
