//! Dispatch for `gga_c_pbe_erf_gws` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_c_pbe_erf_gws as k;

/// libxc default for `param_gamma`.
pub const PARAM_GAMMA: f64 = 0.031090690869654895034;
/// libxc default for `param_a_c`.
pub const PARAM_A_C: f64 = 2.78;
/// libxc default for `param_beta`.
pub const PARAM_BETA: f64 = 0.06672455060314922;
/// libxc default for `param_hyb_omega_0`.
pub const PARAM_HYB_OMEGA_0: f64 = 0.5;

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_c_pbe_erf_gws_exc_unpol],
        [k::vxc_unpol::gga_c_pbe_erf_gws_vxc_unpol],
        [k::fxc_unpol::gga_c_pbe_erf_gws_fxc_unpol],
        [k::kxc_unpol::gga_c_pbe_erf_gws_kxc_unpol],
        [k::lxc_unpol::gga_c_pbe_erf_gws_lxc_unpol],
        [k::exc_pol::gga_c_pbe_erf_gws_exc_pol],
        [k::vxc_pol::gga_c_pbe_erf_gws_vxc_pol],
        [k::fxc_pol::gga_c_pbe_erf_gws_fxc_pol],
        [k::kxc_pol::gga_c_pbe_erf_gws_kxc_pol],
        [k::lxc_pol::gga_c_pbe_erf_gws_lxc_pol],
        params = (PARAM_GAMMA, PARAM_A_C, PARAM_BETA, PARAM_HYB_OMEGA_0)
    )
}
