//! Dispatch for `gga_c_am05` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_c_am05 as k;

/// libxc's raw integer id for this functional.
pub const ID: u16 = 135;

/// libxc default for `param_alpha`.
pub const PARAM_ALPHA: f64 = 2.804;
/// libxc default for `param_gamma`.
pub const PARAM_GAMMA: f64 = 0.8098;

/// Number of libxc `ext_params` this dispatch accepts at runtime.
pub const N_EXT_PARAMS: usize = 2;

/// libxc `ext_params` names, in libxc's own order.
pub const EXT_PARAM_NAMES: [&str; 2] = ["_alpha", "_gamma"];

/// Permutation: libxc `ext_params` index -> this kernel's argument slot.
///
/// `usize::MAX` marks an ext_param the kernel does not consume. Built by
/// *name* in `extract_params.py`, not by position -- the two orders differ for
/// most functionals, because libxc's order is its C params-struct order
/// (`util.c::copy_params` writes `ext_params[i]` into struct slot `i`) while
/// the kernel's is the maple2c argument order.
/// | libxc `ext_params` name | kernel argument |
/// |---|---|
/// | `_alpha` | `param_alpha` |
/// | `_gamma` | `param_gamma` |
pub const EXT_TO_KERNEL: [usize; 2] = [0, 1];

/// Compiled-in libxc defaults, in kernel argument order.
pub const DEFAULTS: [f64; 2] = [PARAM_ALPHA, PARAM_GAMMA];

/// Same as [`dispatch`], with an optional caller-supplied `ext_params` array
/// in libxc's own order.
///
/// `None` is exactly [`dispatch`] -- same constants, same bits. `Some(e)`
/// starts from those defaults and overwrites only the slots `e` actually
/// feeds, so an ext_param the kernel ignores cannot disturb one it uses.
pub fn dispatch_with(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
    ext: Option<&[f64]>,
) -> Result<(), LibxcRsError> {
    let mut p = DEFAULTS;
    if let Some(e) = ext {
        if e.len() != N_EXT_PARAMS {
            return Err(LibxcRsError::ExtParamCountMismatch {
                id: libxc_core::model::FunctionalId(ID),
                expected: N_EXT_PARAMS,
                actual: e.len(),
            });
        }
        for (i, &slot) in EXT_TO_KERNEL.iter().enumerate() {
            if slot != usize::MAX {
                p[slot] = e[i];
            }
        }
    }
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_c_am05_exc_unpol],
        [k::vxc_unpol::gga_c_am05_vxc_unpol],
        [k::fxc_unpol::gga_c_am05_fxc_unpol],
        [k::kxc_unpol::gga_c_am05_kxc_unpol],
        [k::lxc_unpol::gga_c_am05_lxc_unpol],
        [k::exc_pol::gga_c_am05_exc_pol],
        [k::vxc_pol::gga_c_am05_vxc_pol],
        [k::fxc_pol::gga_c_am05_fxc_pol],
        [k::kxc_pol::gga_c_am05_kxc_pol],
        [k::lxc_pol::gga_c_am05_lxc_pol],
        params = (p[0], p[1])
    )
}

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_c_am05_exc_unpol],
        [k::vxc_unpol::gga_c_am05_vxc_unpol],
        [k::fxc_unpol::gga_c_am05_fxc_unpol],
        [k::kxc_unpol::gga_c_am05_kxc_unpol],
        [k::lxc_unpol::gga_c_am05_lxc_unpol],
        [k::exc_pol::gga_c_am05_exc_pol],
        [k::vxc_pol::gga_c_am05_vxc_pol],
        [k::fxc_pol::gga_c_am05_fxc_pol],
        [k::kxc_pol::gga_c_am05_kxc_pol],
        [k::lxc_pol::gga_c_am05_lxc_pol],
        params = (PARAM_ALPHA, PARAM_GAMMA)
    )
}
