//! Dispatch for `gga_x_lb` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_x_lb as k;

/// libxc's raw integer id for this functional.
pub const ID: u16 = 160;


/// libxc default for `param_beta`.
pub const PARAM_BETA: f64 = 0.05;
/// libxc default for `param_gamma`.
pub const PARAM_GAMMA: f64 = 1.0;
/// libxc default for `param_alpha`.
pub const PARAM_ALPHA: f64 = 1.0;

/// The derivative orders libxc implements for this functional (its
/// `XC_FLAGS_HAVE_*`). libxc ships a maple2c function for exactly these, so
/// this kernel tree has fewer than the usual ten modules; any other order is
/// refused, as libxc refuses it.
pub const CLAIMED: &[DerivativeOrder] = &[DerivativeOrder::Vxc, DerivativeOrder::Fxc, DerivativeOrder::Kxc, DerivativeOrder::Lxc];

/// `XC_FLAGS_HAVE_EXC`. Clear for a potential-only functional (`XC_NO_EXC`):
/// its kernels take no `zk`, so `zk` is neither demanded nor written.
pub const HAVE_EXC: bool = false;

/// `crate::ten_arm_dispatch_rgga` for a tree with only the [`CLAIMED`]
/// modules. Same invocation; the slot list is for the reader, and each arm
/// names its kernel directly.
macro_rules! partial_dispatch {
    (
        $input:expr, $output:expr, $order:expr, $spin:expr, $thresholds:expr,
        needs_tau = $needs_tau:expr, zero_tau = $zero_tau:expr,
        $( [ $($slot:tt)* ], )*
        params = ( $( $scalar:expr ),* $(,)? )
    ) => {{
        use crate::sweep_gga::{min_chunk, par_sweep};
        use libxc_core::dims::Dimensions;

        // Refused before `prepare` takes the caller's buffers.
        if !CLAIMED.contains(&$order) {
            return Err(LibxcRsError::UnsupportedDerivativeOrder {
                id: libxc_core::model::FunctionalId(ID),
                order: $order,
                max: CLAIMED[CLAIMED.len() - 1],
            });
        }
        let d = Dimensions::gga($spin);
        let dt = $thresholds.density;
        let zt = $thresholds.zeta;
        // libxc screens and clamps every point before the maple2c body sees
        // it (`work_gga_inc.c`), potential-only functionals included.
        let sc = crate::screen::Screen::new($thresholds, $needs_tau, $zero_tau);
        let chunk = crate::gga::prepare_for($input, $output, $order, &d, HAVE_EXC)?;

        match ($order, $spin) {
            (DerivativeOrder::Vxc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), &sc, &|c: &mut crate::sweep_gga::GgaChunk<'_, '_>| {
                k::vxc_unpol::gga_x_lb_vxc_unpol(
                        c.rho, c.sigma,
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    );
            }),
            (DerivativeOrder::Fxc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), &sc, &|c: &mut crate::sweep_gga::GgaChunk<'_, '_>| {
                k::fxc_unpol::gga_x_lb_fxc_unpol(
                        c.rho, c.sigma,
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    );
            }),
            (DerivativeOrder::Kxc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), &sc, &|c: &mut crate::sweep_gga::GgaChunk<'_, '_>| {
                k::kxc_unpol::gga_x_lb_kxc_unpol(
                        c.rho, c.sigma,
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2sigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma3.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    );
            }),
            (DerivativeOrder::Lxc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), &sc, &|c: &mut crate::sweep_gga::GgaChunk<'_, '_>| {
                k::lxc_unpol::gga_x_lb_lxc_unpol(
                        c.rho, c.sigma,
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2sigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho4.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho3sigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rhosigma3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigma4.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    );
            }),
            (DerivativeOrder::Vxc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), &sc, &|c: &mut crate::sweep_gga::GgaChunk<'_, '_>| {
                k::vxc_pol::gga_x_lb_vxc_pol(
                        c.rho, c.sigma,
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    );
            }),
            (DerivativeOrder::Fxc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), &sc, &|c: &mut crate::sweep_gga::GgaChunk<'_, '_>| {
                k::fxc_pol::gga_x_lb_fxc_pol(
                        c.rho, c.sigma,
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    );
            }),
            (DerivativeOrder::Kxc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), &sc, &|c: &mut crate::sweep_gga::GgaChunk<'_, '_>| {
                k::kxc_pol::gga_x_lb_kxc_pol(
                        c.rho, c.sigma,
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2sigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma3.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    );
            }),
            (DerivativeOrder::Lxc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), &sc, &|c: &mut crate::sweep_gga::GgaChunk<'_, '_>| {
                k::lxc_pol::gga_x_lb_lxc_pol(
                        c.rho, c.sigma,
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2sigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho4.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho3sigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rhosigma3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigma4.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    );
            }),
            _ => unreachable!("CLAIMED is exactly the set of arms above"),
        }
        Ok(())
    }};
}


/// Number of libxc `ext_params` this dispatch accepts at runtime: none,
/// because its libxc ext_params could not be put in correspondence with the kernel's arguments; see extract_params.py.
pub const N_EXT_PARAMS: usize = 0;

/// Number of kernel arguments (compiled-in constants).
pub const N_PARAMS: usize = 3;

/// Compiled-in libxc defaults, in kernel argument order.
pub const DEFAULTS: [f64; 3] = [PARAM_BETA, PARAM_GAMMA, PARAM_ALPHA];

/// The kernel's parameters for a caller-supplied `ext_params` array: always
/// [`DEFAULTS`] here, and a non-empty `ext` is rejected rather than guessed
/// at (its libxc ext_params could not be put in correspondence with the kernel's arguments; see extract_params.py). The fused composite dispatch (`crate::fused`) uses this to
/// hand an auxiliary's constants to a kernel that evaluates several
/// auxiliaries in one loop.
pub fn kernel_params(ext: Option<&[f64]>) -> Result<[f64; N_PARAMS], LibxcRsError> {
    if let Some(e) = ext
        && !e.is_empty()
    {
        return Err(LibxcRsError::ExtParamCountMismatch {
            id: libxc_core::model::FunctionalId(ID),
            expected: 0,
            actual: e.len(),
        });
    }
    Ok(DEFAULTS)
}

/// Same as [`dispatch`], with an optional caller-supplied `ext_params` array
/// in libxc's own order.
///
/// This functional does not accept runtime ext_params (its libxc ext_params could not be put in correspondence with the kernel's arguments; see extract_params.py), so a non-empty
/// `ext` is rejected rather than guessed at.
pub fn dispatch_with(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
    ext: Option<&[f64]>,
) -> Result<(), LibxcRsError> {
    kernel_params(ext)?;
    dispatch(input, output, order, spin, thresholds)
}

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    partial_dispatch!(
        input, output, order, spin, thresholds,
        needs_tau = false, zero_tau = false,
        [k::vxc_unpol::gga_x_lb_vxc_unpol],
        [k::fxc_unpol::gga_x_lb_fxc_unpol],
        [k::kxc_unpol::gga_x_lb_kxc_unpol],
        [k::lxc_unpol::gga_x_lb_lxc_unpol],
        [k::vxc_pol::gga_x_lb_vxc_pol],
        [k::fxc_pol::gga_x_lb_fxc_pol],
        [k::kxc_pol::gga_x_lb_kxc_pol],
        [k::lxc_pol::gga_x_lb_lxc_pol],
        params = (PARAM_BETA, PARAM_GAMMA, PARAM_ALPHA)
    )
}
