//! Dispatch for `gga_x_s12g` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_x_s12 as k;

/// libxc's raw integer id for this functional.
pub const ID: u16 = 495;

/// libxc default for `param_bx`.
pub const PARAM_BX: f64 = 1.0;
/// libxc default for `param_C`.
pub const PARAM_C: f64 = 0.00403198;
/// libxc default for `param_D`.
pub const PARAM_D: f64 = 0.00104596;
/// libxc default for `param_B`.
pub const PARAM_B: f64 = 0.7185796799999999;
/// libxc default for `param_E`.
pub const PARAM_E: f64 = 0.00594635;
/// libxc default for `param_A`.
pub const PARAM_A: f64 = 1.03842032;

/// Number of libxc `ext_params` this dispatch accepts at runtime.
pub const N_EXT_PARAMS: usize = 5;

/// libxc `ext_params` names, in libxc's own order.
pub const EXT_PARAM_NAMES: [&str; 5] = ["_A", "_B", "_C", "_D", "_E"];

/// Permutation: libxc `ext_params` index -> this kernel's argument slot.
///
/// `usize::MAX` marks an ext_param the kernel does not consume. Built by
/// *name* in `extract_params.py`, not by position -- the two orders differ for
/// most functionals, because libxc's order is its C params-struct order
/// (`util.c::copy_params` writes `ext_params[i]` into struct slot `i`) while
/// the kernel's is the maple2c argument order.
/// | libxc `ext_params` name | kernel argument |
/// |---|---|
/// | `_A` | `param_A` |
/// | `_B` | `param_B` |
/// | `_C` | `param_C` |
/// | `_D` | `param_D` |
/// | `_E` | `param_E` |
pub const EXT_TO_KERNEL: [usize; 5] = [5, 3, 1, 2, 4];

/// Compiled-in libxc defaults, in kernel argument order.
pub const DEFAULTS: [f64; 6] = [PARAM_BX, PARAM_C, PARAM_D, PARAM_B, PARAM_E, PARAM_A];

/// Same as [`dispatch`], with an optional caller-supplied `ext_params` array
/// in libxc's own order.
///
/// `None` is exactly [`dispatch`] -- same constants, same bits. `Some(e)`
/// starts from those defaults and overwrites only the slots `e` actually
/// feeds, so an ext_param the kernel ignores cannot disturb one it uses.
pub fn dispatch_with(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
    ext: Option<&[f64]>,
) -> Result<(), LibxcRsError> {
    let mut p = DEFAULTS;
    if let Some(e) = ext {
        if e.len() != N_EXT_PARAMS {
            return Err(LibxcRsError::ExtParamCountMismatch {
                id: libxc_core::model::FunctionalId(ID),
                expected: N_EXT_PARAMS,
                actual: e.len(),
            });
        }
        for (i, &slot) in EXT_TO_KERNEL.iter().enumerate() {
            if slot != usize::MAX {
                p[slot] = e[i];
            }
        }
    }
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_x_s12_exc_unpol],
        [k::vxc_unpol::gga_x_s12_vxc_unpol],
        [k::fxc_unpol::gga_x_s12_fxc_unpol],
        [k::kxc_unpol::gga_x_s12_kxc_unpol],
        [k::lxc_unpol::gga_x_s12_lxc_unpol],
        [k::exc_pol::gga_x_s12_exc_pol],
        [k::vxc_pol::gga_x_s12_vxc_pol],
        [k::fxc_pol::gga_x_s12_fxc_pol],
        [k::kxc_pol::gga_x_s12_kxc_pol],
        [k::lxc_pol::gga_x_s12_lxc_pol],
        params = (p[0], p[1], p[2], p[3], p[4], p[5])
    )
}

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_x_s12_exc_unpol],
        [k::vxc_unpol::gga_x_s12_vxc_unpol],
        [k::fxc_unpol::gga_x_s12_fxc_unpol],
        [k::kxc_unpol::gga_x_s12_kxc_unpol],
        [k::lxc_unpol::gga_x_s12_lxc_unpol],
        [k::exc_pol::gga_x_s12_exc_pol],
        [k::vxc_pol::gga_x_s12_vxc_pol],
        [k::fxc_pol::gga_x_s12_fxc_pol],
        [k::kxc_pol::gga_x_s12_kxc_pol],
        [k::lxc_pol::gga_x_s12_lxc_pol],
        params = (PARAM_BX, PARAM_C, PARAM_D, PARAM_B, PARAM_E, PARAM_A)
    )
}
