//! Dispatch for `gga_c_zvpbeint` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_c_zvpbeint as k;

/// libxc default for `param_alpha`.
pub const PARAM_ALPHA: f64 = 1.0;
/// libxc default for `param_omega`.
pub const PARAM_OMEGA: f64 = 4.5;
/// libxc default for `param_beta`.
pub const PARAM_BETA: f64 = 0.052;

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_c_zvpbeint_exc_unpol],
        [k::vxc_unpol::gga_c_zvpbeint_vxc_unpol],
        [k::fxc_unpol::gga_c_zvpbeint_fxc_unpol],
        [k::kxc_unpol::gga_c_zvpbeint_kxc_unpol],
        [k::lxc_unpol::gga_c_zvpbeint_lxc_unpol],
        [k::exc_pol::gga_c_zvpbeint_exc_pol],
        [k::vxc_pol::gga_c_zvpbeint_vxc_pol],
        [k::fxc_pol::gga_c_zvpbeint_fxc_pol],
        [k::kxc_pol::gga_c_zvpbeint_kxc_pol],
        [k::lxc_pol::gga_c_zvpbeint_lxc_pol],
        params = (PARAM_ALPHA, PARAM_OMEGA, PARAM_BETA)
    )
}
