//! Dispatch for `gga_x_hjs_pbe_sol` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_x_hjs as k;

/// libxc default for `param_a_0`.
pub const PARAM_A_0: f64 = 0.0047333;
/// libxc default for `param_a_1`.
pub const PARAM_A_1: f64 = 0.0403304;
/// libxc default for `param_a_2`.
pub const PARAM_A_2: f64 = -0.0574615;
/// libxc default for `param_a_3`.
pub const PARAM_A_3: f64 = 0.0435395;
/// libxc default for `param_a_4`.
pub const PARAM_A_4: f64 = -0.0216251;
/// libxc default for `param_a_5`.
pub const PARAM_A_5: f64 = 0.0063721;
/// libxc default for `param_b_0`.
pub const PARAM_B_0: f64 = 8.52056;
/// libxc default for `param_b_1`.
pub const PARAM_B_1: f64 = -13.9885;
/// libxc default for `param_b_2`.
pub const PARAM_B_2: f64 = 9.28583;
/// libxc default for `param_b_3`.
pub const PARAM_B_3: f64 = -3.27287;
/// libxc default for `param_b_4`.
pub const PARAM_B_4: f64 = 0.843499;
/// libxc default for `param_b_5`.
pub const PARAM_B_5: f64 = -0.235543;
/// libxc default for `param_b_6`.
pub const PARAM_B_6: f64 = 0.0847074;
/// libxc default for `param_b_7`.
pub const PARAM_B_7: f64 = -0.0171561;
/// libxc default for `param_b_8`.
pub const PARAM_B_8: f64 = 0.0050552;
/// libxc default for `param_hyb_omega_0`.
pub const PARAM_HYB_OMEGA_0: f64 = 0.11;

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_x_hjs_exc_unpol],
        [k::vxc_unpol::gga_x_hjs_vxc_unpol],
        [k::fxc_unpol::gga_x_hjs_fxc_unpol],
        [k::kxc_unpol::gga_x_hjs_kxc_unpol],
        [k::lxc_unpol::gga_x_hjs_lxc_unpol],
        [k::exc_pol::gga_x_hjs_exc_pol],
        [k::vxc_pol::gga_x_hjs_vxc_pol],
        [k::fxc_pol::gga_x_hjs_fxc_pol],
        [k::kxc_pol::gga_x_hjs_kxc_pol],
        [k::lxc_pol::gga_x_hjs_lxc_pol],
        params = (PARAM_A_0, PARAM_A_1, PARAM_A_2, PARAM_A_3, PARAM_A_4, PARAM_A_5, PARAM_B_0, PARAM_B_1, PARAM_B_2, PARAM_B_3, PARAM_B_4, PARAM_B_5, PARAM_B_6, PARAM_B_7, PARAM_B_8, PARAM_HYB_OMEGA_0)
    )
}
