//! Dispatch for `gga_xc_hcth_120` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_xc_b97 as k;

/// libxc default for `param_c_x_1`.
pub const PARAM_C_X_1: f64 = -0.747215;
/// libxc default for `param_c_x_2`.
pub const PARAM_C_X_2: f64 = 5.07833;
/// libxc default for `param_c_x_3`.
pub const PARAM_C_X_3: f64 = -4.10746;
/// libxc default for `param_c_x_4`.
pub const PARAM_C_X_4: f64 = 1.17173;
/// libxc default for `param_c_x_0`.
pub const PARAM_C_X_0: f64 = 1.09163;
/// libxc default for `param_c_ss_1`.
pub const PARAM_C_SS_1: f64 = -0.260699;
/// libxc default for `param_c_ss_2`.
pub const PARAM_C_SS_2: f64 = 0.432917;
/// libxc default for `param_c_ss_3`.
pub const PARAM_C_SS_3: f64 = -1.99247;
/// libxc default for `param_c_ss_4`.
pub const PARAM_C_SS_4: f64 = 2.48531;
/// libxc default for `param_c_ss_0`.
pub const PARAM_C_SS_0: f64 = 0.489508;
/// libxc default for `param_c_ab_1`.
pub const PARAM_C_AB_1: f64 = 6.92982;
/// libxc default for `param_c_ab_2`.
pub const PARAM_C_AB_2: f64 = -24.7073;
/// libxc default for `param_c_ab_3`.
pub const PARAM_C_AB_3: f64 = 23.1098;
/// libxc default for `param_c_ab_4`.
pub const PARAM_C_AB_4: f64 = -11.3234;
/// libxc default for `param_c_ab_0`.
pub const PARAM_C_AB_0: f64 = 0.51473;

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_xc_b97_exc_unpol],
        [k::vxc_unpol::gga_xc_b97_vxc_unpol],
        [k::fxc_unpol::gga_xc_b97_fxc_unpol],
        [k::kxc_unpol::gga_xc_b97_kxc_unpol],
        [k::lxc_unpol::gga_xc_b97_lxc_unpol],
        [k::exc_pol::gga_xc_b97_exc_pol],
        [k::vxc_pol::gga_xc_b97_vxc_pol],
        [k::fxc_pol::gga_xc_b97_fxc_pol],
        [k::kxc_pol::gga_xc_b97_kxc_pol],
        [k::lxc_pol::gga_xc_b97_lxc_pol],
        params = (PARAM_C_X_1, PARAM_C_X_2, PARAM_C_X_3, PARAM_C_X_4, PARAM_C_X_0, PARAM_C_SS_1, PARAM_C_SS_2, PARAM_C_SS_3, PARAM_C_SS_4, PARAM_C_SS_0, PARAM_C_AB_1, PARAM_C_AB_2, PARAM_C_AB_3, PARAM_C_AB_4, PARAM_C_AB_0)
    )
}
