//! Dispatch for `gga_x_ev93` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_x_ev93 as k;

/// libxc default for `param_a1`.
pub const PARAM_A1: f64 = 1.647127;
/// libxc default for `param_a2`.
pub const PARAM_A2: f64 = 0.980118;
/// libxc default for `param_a3`.
pub const PARAM_A3: f64 = 0.017399;
/// libxc default for `param_b1`.
pub const PARAM_B1: f64 = 1.523671;
/// libxc default for `param_b2`.
pub const PARAM_B2: f64 = 0.367229;
/// libxc default for `param_b3`.
pub const PARAM_B3: f64 = 0.011282;

pub fn dispatch<'a>(
    input: &'a GgaInput<'a>,
    output: &'a mut GgaOutput<'a>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_x_ev93_exc_unpol],
        [k::vxc_unpol::gga_x_ev93_vxc_unpol],
        [k::fxc_unpol::gga_x_ev93_fxc_unpol],
        [k::kxc_unpol::gga_x_ev93_kxc_unpol],
        [k::lxc_unpol::gga_x_ev93_lxc_unpol],
        [k::exc_pol::gga_x_ev93_exc_pol],
        [k::vxc_pol::gga_x_ev93_vxc_pol],
        [k::fxc_pol::gga_x_ev93_fxc_pol],
        [k::kxc_pol::gga_x_ev93_kxc_pol],
        [k::lxc_pol::gga_x_ev93_lxc_pol],
        params = (PARAM_A1, PARAM_A2, PARAM_A3, PARAM_B1, PARAM_B2, PARAM_B3)
    )
}
