//! Dispatch for `gga_x_optx` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_x_optx as k;

/// libxc's raw integer id for this functional.
pub const ID: u16 = 110;

/// libxc default for `param_gamma`.
pub const PARAM_GAMMA: f64 = 0.006;
/// libxc default for `param_b`.
pub const PARAM_B: f64 = 1.5385818404305593;
/// libxc default for `param_a`.
pub const PARAM_A: f64 = 1.05151;

/// Number of libxc `ext_params` this dispatch accepts at runtime.
pub const N_EXT_PARAMS: usize = 3;

/// libxc `ext_params` names, in libxc's own order.
pub const EXT_PARAM_NAMES: [&str; 3] = ["_a", "_b", "_gamma"];

/// Permutation: libxc `ext_params` index -> this kernel's argument slot.
///
/// `usize::MAX` marks an ext_param the kernel does not consume. Built by
/// *name* in `extract_params.py`, not by position -- the two orders differ for
/// most functionals, because libxc's order is its C params-struct order
/// (`util.c::copy_params` writes `ext_params[i]` into struct slot `i`) while
/// the kernel's is the maple2c argument order.
/// | libxc `ext_params` name | kernel argument |
/// |---|---|
/// | `_a` | `param_a` |
/// | `_b` | `param_b` |
/// | `_gamma` | `param_gamma` |
pub const EXT_TO_KERNEL: [usize; 3] = [2, 1, 0];

/// Compiled-in libxc defaults, in kernel argument order.
pub const DEFAULTS: [f64; 3] = [PARAM_GAMMA, PARAM_B, PARAM_A];

/// Same as [`dispatch`], with an optional caller-supplied `ext_params` array
/// in libxc's own order.
///
/// `None` is exactly [`dispatch`] -- same constants, same bits. `Some(e)`
/// starts from those defaults and overwrites only the slots `e` actually
/// feeds, so an ext_param the kernel ignores cannot disturb one it uses.
pub fn dispatch_with(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
    ext: Option<&[f64]>,
) -> Result<(), LibxcRsError> {
    let mut p = DEFAULTS;
    if let Some(e) = ext {
        if e.len() != N_EXT_PARAMS {
            return Err(LibxcRsError::ExtParamCountMismatch {
                id: libxc_core::model::FunctionalId(ID),
                expected: N_EXT_PARAMS,
                actual: e.len(),
            });
        }
        for (i, &slot) in EXT_TO_KERNEL.iter().enumerate() {
            if slot != usize::MAX {
                p[slot] = e[i];
            }
        }
    }
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_x_optx_exc_unpol],
        [k::vxc_unpol::gga_x_optx_vxc_unpol],
        [k::fxc_unpol::gga_x_optx_fxc_unpol],
        [k::kxc_unpol::gga_x_optx_kxc_unpol],
        [k::lxc_unpol::gga_x_optx_lxc_unpol],
        [k::exc_pol::gga_x_optx_exc_pol],
        [k::vxc_pol::gga_x_optx_vxc_pol],
        [k::fxc_pol::gga_x_optx_fxc_pol],
        [k::kxc_pol::gga_x_optx_kxc_pol],
        [k::lxc_pol::gga_x_optx_lxc_pol],
        params = (p[0], p[1], p[2])
    )
}

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_x_optx_exc_unpol],
        [k::vxc_unpol::gga_x_optx_vxc_unpol],
        [k::fxc_unpol::gga_x_optx_fxc_unpol],
        [k::kxc_unpol::gga_x_optx_kxc_unpol],
        [k::lxc_unpol::gga_x_optx_lxc_unpol],
        [k::exc_pol::gga_x_optx_exc_pol],
        [k::vxc_pol::gga_x_optx_vxc_pol],
        [k::fxc_pol::gga_x_optx_fxc_pol],
        [k::kxc_pol::gga_x_optx_kxc_pol],
        [k::lxc_pol::gga_x_optx_lxc_pol],
        params = (PARAM_GAMMA, PARAM_B, PARAM_A)
    )
}
