//! Dispatch for `gga_k_revapbeint` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_k_apbeint as k;

/// libxc's raw integer id for this functional.
pub const ID: u16 = 53;

/// libxc default for `param_muPBE`.
pub const PARAM_MUPBE: f64 = 0.23899;
/// libxc default for `param_muGE`.
pub const PARAM_MUGE: f64 = 0.18518518518518517;
/// libxc default for `param_alpha`.
pub const PARAM_ALPHA: f64 = 1.6666666666666667;
/// libxc default for `param_kappa`.
pub const PARAM_KAPPA: f64 = 1.245;

/// Number of libxc `ext_params` this dispatch accepts at runtime: none,
/// because its libxc ext_params could not be put in correspondence with the kernel's arguments; see extract_params.py.
pub const N_EXT_PARAMS: usize = 0;

/// Same as [`dispatch`], with an optional caller-supplied `ext_params` array
/// in libxc's own order.
///
/// This functional does not accept runtime ext_params (its libxc ext_params could not be put in correspondence with the kernel's arguments; see extract_params.py), so a non-empty
/// `ext` is rejected rather than guessed at.
pub fn dispatch_with(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
    ext: Option<&[f64]>,
) -> Result<(), LibxcRsError> {
    if let Some(e) = ext
        && !e.is_empty()
    {
        return Err(LibxcRsError::ExtParamCountMismatch {
            id: libxc_core::model::FunctionalId(ID),
            expected: 0,
            actual: e.len(),
        });
    }
    dispatch(input, output, order, spin, thresholds)
}

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_k_apbeint_exc_unpol],
        [k::vxc_unpol::gga_k_apbeint_vxc_unpol],
        [k::fxc_unpol::gga_k_apbeint_fxc_unpol],
        [k::kxc_unpol::gga_k_apbeint_kxc_unpol],
        [k::lxc_unpol::gga_k_apbeint_lxc_unpol],
        [k::exc_pol::gga_k_apbeint_exc_pol],
        [k::vxc_pol::gga_k_apbeint_vxc_pol],
        [k::fxc_pol::gga_k_apbeint_fxc_pol],
        [k::kxc_pol::gga_k_apbeint_kxc_pol],
        [k::lxc_pol::gga_k_apbeint_lxc_pol],
        params = (PARAM_MUPBE, PARAM_MUGE, PARAM_ALPHA, PARAM_KAPPA)
    )
}
