//! Dispatch for `hyb_gga_x_sogga11_x` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_x_sogga11 as k;

/// libxc default for `param_a_1`.
pub const PARAM_A_1: f64 = 3.21638;
/// libxc default for `param_mu`.
pub const PARAM_MU: f64 = 0.12345679012345678;
/// libxc default for `param_kappa`.
pub const PARAM_KAPPA: f64 = 0.552;
/// libxc default for `param_a_2`.
pub const PARAM_A_2: f64 = -3.55605;
/// libxc default for `param_a_3`.
pub const PARAM_A_3: f64 = 7.65852;
/// libxc default for `param_a_4`.
pub const PARAM_A_4: f64 = -11.2830;
/// libxc default for `param_a_5`.
pub const PARAM_A_5: f64 = 5.25813;
/// libxc default for `param_b_1`.
pub const PARAM_B_1: f64 = -2.88595;
/// libxc default for `param_b_2`.
pub const PARAM_B_2: f64 = 3.23617;
/// libxc default for `param_b_3`.
pub const PARAM_B_3: f64 = -2.45393;
/// libxc default for `param_b_4`.
pub const PARAM_B_4: f64 = -3.75495;
/// libxc default for `param_b_5`.
pub const PARAM_B_5: f64 = 3.96613;
/// libxc default for `param_a_0`.
pub const PARAM_A_0: f64 = 0.29925;
/// libxc default for `param_b_0`.
pub const PARAM_B_0: f64 = 0.29925;

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_x_sogga11_exc_unpol],
        [k::vxc_unpol::gga_x_sogga11_vxc_unpol],
        [k::fxc_unpol::gga_x_sogga11_fxc_unpol],
        [k::kxc_unpol::gga_x_sogga11_kxc_unpol],
        [k::lxc_unpol::gga_x_sogga11_lxc_unpol],
        [k::exc_pol::gga_x_sogga11_exc_pol],
        [k::vxc_pol::gga_x_sogga11_vxc_pol],
        [k::fxc_pol::gga_x_sogga11_fxc_pol],
        [k::kxc_pol::gga_x_sogga11_kxc_pol],
        [k::lxc_pol::gga_x_sogga11_lxc_pol],
        params = (PARAM_A_1, PARAM_MU, PARAM_KAPPA, PARAM_A_2, PARAM_A_3, PARAM_A_4, PARAM_A_5, PARAM_B_1, PARAM_B_2, PARAM_B_3, PARAM_B_4, PARAM_B_5, PARAM_A_0, PARAM_B_0)
    )
}
