//! Dispatch for `hyb_mgga_x_m06_2x` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_hyb_mgga_x_m05 as k;

/// libxc default for `param_csi_HF`.
pub const PARAM_CSI_HF: f64 = 1.0;
/// libxc default for `param_a_1`.
pub const PARAM_A_1: f64 = -2.206052e-01;
/// libxc default for `param_a_2`.
pub const PARAM_A_2: f64 = -9.431788e-02;
/// libxc default for `param_a_3`.
pub const PARAM_A_3: f64 = 2.164494e+00;
/// libxc default for `param_a_4`.
pub const PARAM_A_4: f64 = -2.556466e+00;
/// libxc default for `param_a_5`.
pub const PARAM_A_5: f64 = -1.422133e+01;
/// libxc default for `param_a_6`.
pub const PARAM_A_6: f64 = 1.555044e+01;
/// libxc default for `param_a_7`.
pub const PARAM_A_7: f64 = 3.598078e+01;
/// libxc default for `param_a_8`.
pub const PARAM_A_8: f64 = -2.722754e+01;
/// libxc default for `param_a_9`.
pub const PARAM_A_9: f64 = -3.924093e+01;
/// libxc default for `param_a_10`.
pub const PARAM_A_10: f64 = 1.522808e+01;
/// libxc default for `param_a_11`.
pub const PARAM_A_11: f64 = 1.522227e+01;
/// libxc default for `param_a_0`.
pub const PARAM_A_0: f64 = 4.600000e-01;

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::hyb_mgga_x_m05_exc_unpol],
        [k::vxc_unpol::hyb_mgga_x_m05_vxc_unpol],
        [k::fxc_unpol::hyb_mgga_x_m05_fxc_unpol],
        [k::kxc_unpol::hyb_mgga_x_m05_kxc_unpol],
        [k::lxc_unpol::hyb_mgga_x_m05_lxc_unpol],
        [k::exc_pol::hyb_mgga_x_m05_exc_pol],
        [k::vxc_pol::hyb_mgga_x_m05_vxc_pol],
        [k::fxc_pol::hyb_mgga_x_m05_fxc_pol],
        [k::kxc_pol::hyb_mgga_x_m05_kxc_pol],
        [k::lxc_pol::hyb_mgga_x_m05_lxc_pol],
        params = (PARAM_CSI_HF, PARAM_A_1, PARAM_A_2, PARAM_A_3, PARAM_A_4, PARAM_A_5, PARAM_A_6, PARAM_A_7, PARAM_A_8, PARAM_A_9, PARAM_A_10, PARAM_A_11, PARAM_A_0)
    )
}
