//! Dispatch for `hyb_mgga_x_m11` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_x_m11 as k;

/// libxc default for `param_a_1`.
pub const PARAM_A_1: f64 = -1.39046703e+01;
/// libxc default for `param_a_2`.
pub const PARAM_A_2: f64 = 1.18206837e+01;
/// libxc default for `param_a_3`.
pub const PARAM_A_3: f64 = 3.10098465e+01;
/// libxc default for `param_a_4`.
pub const PARAM_A_4: f64 = -5.19625696e+01;
/// libxc default for `param_a_5`.
pub const PARAM_A_5: f64 = 1.55750312e+01;
/// libxc default for `param_a_6`.
pub const PARAM_A_6: f64 = -6.94775730e+00;
/// libxc default for `param_a_7`.
pub const PARAM_A_7: f64 = -1.58465014e+02;
/// libxc default for `param_a_8`.
pub const PARAM_A_8: f64 = -1.48447565e+00;
/// libxc default for `param_a_9`.
pub const PARAM_A_9: f64 = 5.51042124e+01;
/// libxc default for `param_a_10`.
pub const PARAM_A_10: f64 = -1.34714184e+01;
/// libxc default for `param_a_11`.
pub const PARAM_A_11: f64 = 0.00000000e+00;
/// libxc default for `param_a_0`.
pub const PARAM_A_0: f64 = -0.18399900e+00;
/// libxc default for `param_b_1`.
pub const PARAM_B_1: f64 = 1.37137944e+01;
/// libxc default for `param_b_2`.
pub const PARAM_B_2: f64 = -1.27998304e+01;
/// libxc default for `param_b_3`.
pub const PARAM_B_3: f64 = -2.93428814e+01;
/// libxc default for `param_b_4`.
pub const PARAM_B_4: f64 = 5.91075674e+01;
/// libxc default for `param_b_5`.
pub const PARAM_B_5: f64 = -2.27604866e+01;
/// libxc default for `param_b_6`.
pub const PARAM_B_6: f64 = -1.02769340e+01;
/// libxc default for `param_b_7`.
pub const PARAM_B_7: f64 = 1.64752731e+02;
/// libxc default for `param_b_8`.
pub const PARAM_B_8: f64 = 1.85349258e+01;
/// libxc default for `param_b_9`.
pub const PARAM_B_9: f64 = -5.56825639e+01;
/// libxc default for `param_b_10`.
pub const PARAM_B_10: f64 = 7.47980859e+00;
/// libxc default for `param_b_11`.
pub const PARAM_B_11: f64 = 0.00000000e+00;
/// libxc default for `param_b_0`.
pub const PARAM_B_0: f64 = 0.75599900e+00;
/// libxc default for `param_hyb_omega_0`.
pub const PARAM_HYB_OMEGA_0: f64 = 0.25;

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_x_m11_exc_unpol],
        [k::vxc_unpol::mgga_x_m11_vxc_unpol],
        [k::fxc_unpol::mgga_x_m11_fxc_unpol],
        [k::kxc_unpol::mgga_x_m11_kxc_unpol],
        [k::lxc_unpol::mgga_x_m11_lxc_unpol],
        [k::exc_pol::mgga_x_m11_exc_pol],
        [k::vxc_pol::mgga_x_m11_vxc_pol],
        [k::fxc_pol::mgga_x_m11_fxc_pol],
        [k::kxc_pol::mgga_x_m11_kxc_pol],
        [k::lxc_pol::mgga_x_m11_lxc_pol],
        params = (PARAM_A_1, PARAM_A_2, PARAM_A_3, PARAM_A_4, PARAM_A_5, PARAM_A_6, PARAM_A_7, PARAM_A_8, PARAM_A_9, PARAM_A_10, PARAM_A_11, PARAM_A_0, PARAM_B_1, PARAM_B_2, PARAM_B_3, PARAM_B_4, PARAM_B_5, PARAM_B_6, PARAM_B_7, PARAM_B_8, PARAM_B_9, PARAM_B_10, PARAM_B_11, PARAM_B_0, PARAM_HYB_OMEGA_0)
    )
}
