//! Dispatch for `hyb_mgga_x_dldf` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_hyb_mgga_x_dldf as k;



pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::hyb_mgga_x_dldf_exc_unpol],
        [k::vxc_unpol::hyb_mgga_x_dldf_vxc_unpol],
        [k::fxc_unpol::hyb_mgga_x_dldf_fxc_unpol],
        [k::kxc_unpol::hyb_mgga_x_dldf_kxc_unpol],
        [k::lxc_unpol::hyb_mgga_x_dldf_lxc_unpol],
        [k::exc_pol::hyb_mgga_x_dldf_exc_pol],
        [k::vxc_pol::hyb_mgga_x_dldf_vxc_pol],
        [k::fxc_pol::hyb_mgga_x_dldf_fxc_pol],
        [k::kxc_pol::hyb_mgga_x_dldf_kxc_pol],
        [k::lxc_pol::hyb_mgga_x_dldf_lxc_pol],
        params = ()
    )
}
