//! Dispatch for `hyb_mgga_x_bmk` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_x_tau_hcth as k;

/// libxc default for `param_cx_local_1`.
pub const PARAM_CX_LOCAL_1: f64 = 2.77701;
/// libxc default for `param_cx_local_2`.
pub const PARAM_CX_LOCAL_2: f64 = -11.4230;
/// libxc default for `param_cx_local_3`.
pub const PARAM_CX_LOCAL_3: f64 = 11.7167;
/// libxc default for `param_cx_nlocal_1`.
pub const PARAM_CX_NLOCAL_1: f64 = 4.73936;
/// libxc default for `param_cx_nlocal_2`.
pub const PARAM_CX_NLOCAL_2: f64 = -26.6188;
/// libxc default for `param_cx_nlocal_3`.
pub const PARAM_CX_NLOCAL_3: f64 = 22.4891;
/// libxc default for `param_cx_nlocal_0`.
pub const PARAM_CX_NLOCAL_0: f64 = -0.192212;
/// libxc default for `param_cx_local_0`.
pub const PARAM_CX_LOCAL_0: f64 = 0.474302;

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_x_tau_hcth_exc_unpol],
        [k::vxc_unpol::mgga_x_tau_hcth_vxc_unpol],
        [k::fxc_unpol::mgga_x_tau_hcth_fxc_unpol],
        [k::kxc_unpol::mgga_x_tau_hcth_kxc_unpol],
        [k::lxc_unpol::mgga_x_tau_hcth_lxc_unpol],
        [k::exc_pol::mgga_x_tau_hcth_exc_pol],
        [k::vxc_pol::mgga_x_tau_hcth_vxc_pol],
        [k::fxc_pol::mgga_x_tau_hcth_fxc_pol],
        [k::kxc_pol::mgga_x_tau_hcth_kxc_pol],
        [k::lxc_pol::mgga_x_tau_hcth_lxc_pol],
        params = (PARAM_CX_LOCAL_1, PARAM_CX_LOCAL_2, PARAM_CX_LOCAL_3, PARAM_CX_NLOCAL_1, PARAM_CX_NLOCAL_2, PARAM_CX_NLOCAL_3, PARAM_CX_NLOCAL_0, PARAM_CX_LOCAL_0)
    )
}
