//! Dispatch for `hyb_gga_x_lcgau` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_gga_x_lcgau as k;

/// libxc default for `param_hyb_omega_0`.
pub const PARAM_HYB_OMEGA_0: f64 = 0.42;
/// libxc default for `param_hyb_omega_2`.
pub const PARAM_HYB_OMEGA_2: f64 = 4.004542874831487;
/// libxc default for `param_hyb_omega_3`.
pub const PARAM_HYB_OMEGA_3: f64 = 4.004542874831487;
/// libxc default for `param_hyb_coeff_2`.
pub const PARAM_HYB_COEFF_2: f64 = 1.887855926706273;
/// libxc default for `param_hyb_coeff_3`.
pub const PARAM_HYB_COEFF_3: f64 = 0.0;

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::gga_x_lcgau_exc_unpol],
        [k::vxc_unpol::gga_x_lcgau_vxc_unpol],
        [k::fxc_unpol::gga_x_lcgau_fxc_unpol],
        [k::kxc_unpol::gga_x_lcgau_kxc_unpol],
        [k::lxc_unpol::gga_x_lcgau_lxc_unpol],
        [k::exc_pol::gga_x_lcgau_exc_pol],
        [k::vxc_pol::gga_x_lcgau_vxc_pol],
        [k::fxc_pol::gga_x_lcgau_fxc_pol],
        [k::kxc_pol::gga_x_lcgau_kxc_pol],
        [k::lxc_pol::gga_x_lcgau_lxc_pol],
        params = (PARAM_HYB_OMEGA_0, PARAM_HYB_OMEGA_2, PARAM_HYB_OMEGA_3, PARAM_HYB_COEFF_2, PARAM_HYB_COEFF_3)
    )
}
