//! Dispatch for `hyb_gga_xc_wb97x_d` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

use libxc_rkernel_hyb_gga_xc_wb97 as k;

/// libxc default for `param_c_x_1`.
pub const PARAM_C_X_1: f64 = 6.61160e-01;
/// libxc default for `param_c_x_2`.
pub const PARAM_C_X_2: f64 = 5.74541e-01;
/// libxc default for `param_c_x_3`.
pub const PARAM_C_X_3: f64 = -5.25671e+00;
/// libxc default for `param_c_x_4`.
pub const PARAM_C_X_4: f64 = 1.16386e+01;
/// libxc default for `param_c_x_0`.
pub const PARAM_C_X_0: f64 = 7.77964e-01;
/// libxc default for `param_c_ss_1`.
pub const PARAM_C_SS_1: f64 = -6.90539e+00;
/// libxc default for `param_c_ss_2`.
pub const PARAM_C_SS_2: f64 = 3.13343e+01;
/// libxc default for `param_c_ss_3`.
pub const PARAM_C_SS_3: f64 = -5.10533e+01;
/// libxc default for `param_c_ss_4`.
pub const PARAM_C_SS_4: f64 = 2.64423e+01;
/// libxc default for `param_c_ss_0`.
pub const PARAM_C_SS_0: f64 = 1.00000e+00;
/// libxc default for `param_c_ab_1`.
pub const PARAM_C_AB_1: f64 = 1.79413e+00;
/// libxc default for `param_c_ab_2`.
pub const PARAM_C_AB_2: f64 = -1.20477e+01;
/// libxc default for `param_c_ab_3`.
pub const PARAM_C_AB_3: f64 = 1.40847e+01;
/// libxc default for `param_c_ab_4`.
pub const PARAM_C_AB_4: f64 = -8.50809e+00;
/// libxc default for `param_c_ab_0`.
pub const PARAM_C_AB_0: f64 = 1.00000e+00;
/// libxc default for `param_hyb_omega_0`.
pub const PARAM_HYB_OMEGA_0: f64 = 0.2;

pub fn dispatch(
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::hyb_gga_xc_wb97_exc_unpol],
        [k::vxc_unpol::hyb_gga_xc_wb97_vxc_unpol],
        [k::fxc_unpol::hyb_gga_xc_wb97_fxc_unpol],
        [k::kxc_unpol::hyb_gga_xc_wb97_kxc_unpol],
        [k::lxc_unpol::hyb_gga_xc_wb97_lxc_unpol],
        [k::exc_pol::hyb_gga_xc_wb97_exc_pol],
        [k::vxc_pol::hyb_gga_xc_wb97_vxc_pol],
        [k::fxc_pol::hyb_gga_xc_wb97_fxc_pol],
        [k::kxc_pol::hyb_gga_xc_wb97_kxc_pol],
        [k::lxc_pol::hyb_gga_xc_wb97_lxc_pol],
        params = (PARAM_C_X_1, PARAM_C_X_2, PARAM_C_X_3, PARAM_C_X_4, PARAM_C_X_0, PARAM_C_SS_1, PARAM_C_SS_2, PARAM_C_SS_3, PARAM_C_SS_4, PARAM_C_SS_0, PARAM_C_AB_1, PARAM_C_AB_2, PARAM_C_AB_3, PARAM_C_AB_4, PARAM_C_AB_0, PARAM_HYB_OMEGA_0)
    )
}
