//! Dispatch for `hyb_mgga_x_m06_sx` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_x_m06l as k;

/// libxc default for `param_a_1`.
pub const PARAM_A_1: f64 = 3.01264933631367E-02;
/// libxc default for `param_a_2`.
pub const PARAM_A_2: f64 = -1.03366758333673E-01;
/// libxc default for `param_a_3`.
pub const PARAM_A_3: f64 = -1.55653062500239E-01;
/// libxc default for `param_a_4`.
pub const PARAM_A_4: f64 = 7.95768051149902E-03;
/// libxc default for `param_a_5`.
pub const PARAM_A_5: f64 = 8.71986277454856E-02;
/// libxc default for `param_a_6`.
pub const PARAM_A_6: f64 = -8.16152625764469E-01;
/// libxc default for `param_a_7`.
pub const PARAM_A_7: f64 = 6.72773006612420E-01;
/// libxc default for `param_a_8`.
pub const PARAM_A_8: f64 = 5.21127186174968E-01;
/// libxc default for `param_a_9`.
pub const PARAM_A_9: f64 = 3.99466945122217E-01;
/// libxc default for `param_a_10`.
pub const PARAM_A_10: f64 = 5.19400018999204E-01;
/// libxc default for `param_a_11`.
pub const PARAM_A_11: f64 = -9.65261552636835E-01;
/// libxc default for `param_a_0`.
pub const PARAM_A_0: f64 = 9.96501680264007E-01;
/// libxc default for `param_d_0`.
pub const PARAM_D_0: f64 = -3.47792307472902E-01;
/// libxc default for `param_d_1`.
pub const PARAM_D_1: f64 = 0.0;
/// libxc default for `param_d_2`.
pub const PARAM_D_2: f64 = -2.70366787478266E-03;
/// libxc default for `param_d_3`.
pub const PARAM_D_3: f64 = 0.0;
/// libxc default for `param_d_4`.
pub const PARAM_D_4: f64 = 0.0;
/// libxc default for `param_d_5`.
pub const PARAM_D_5: f64 = 0.0;

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_x_m06l_exc_unpol],
        [k::vxc_unpol::mgga_x_m06l_vxc_unpol],
        [k::fxc_unpol::mgga_x_m06l_fxc_unpol],
        [k::kxc_unpol::mgga_x_m06l_kxc_unpol],
        [k::lxc_unpol::mgga_x_m06l_lxc_unpol],
        [k::exc_pol::mgga_x_m06l_exc_pol],
        [k::vxc_pol::mgga_x_m06l_vxc_pol],
        [k::fxc_pol::mgga_x_m06l_fxc_pol],
        [k::kxc_pol::mgga_x_m06l_kxc_pol],
        [k::lxc_pol::mgga_x_m06l_lxc_pol],
        params = (PARAM_A_1, PARAM_A_2, PARAM_A_3, PARAM_A_4, PARAM_A_5, PARAM_A_6, PARAM_A_7, PARAM_A_8, PARAM_A_9, PARAM_A_10, PARAM_A_11, PARAM_A_0, PARAM_D_0, PARAM_D_1, PARAM_D_2, PARAM_D_3, PARAM_D_4, PARAM_D_5)
    )
}
