//! Dispatch for `hyb_mgga_xc_gas22` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_hyb_mgga_xc_gas22 as k;

/// libxc's raw integer id for this functional.
pub const ID: u16 = 658;

/// libxc default for `param_c_x_1`.
pub const PARAM_C_X_1: f64 = 0.936993691972698;
/// libxc default for `param_c_x_2`.
pub const PARAM_C_X_2: f64 = 0.317533683085033;
/// libxc default for `param_c_x_0`.
pub const PARAM_C_X_0: f64 = 0.862139736374172;
/// libxc default for `param_c_ss_0`.
pub const PARAM_C_SS_0: f64 = 1.0;
/// libxc default for `param_c_ss_1`.
pub const PARAM_C_SS_1: f64 = -4.10753796482853;
/// libxc default for `param_c_ss_2`.
pub const PARAM_C_SS_2: f64 = -5.24218990333846;
/// libxc default for `param_c_ss_3`.
pub const PARAM_C_SS_3: f64 = -1.76643208454076;
/// libxc default for `param_c_ss_4`.
pub const PARAM_C_SS_4: f64 = 7.5380689617542;
/// libxc default for `param_c_os_1`.
pub const PARAM_C_OS_1: f64 = 7.98909430970845;
/// libxc default for `param_c_os_2`.
pub const PARAM_C_OS_2: f64 = -7.54815900595292;
/// libxc default for `param_c_os_3`.
pub const PARAM_C_OS_3: f64 = 2.00093961824784;
/// libxc default for `param_c_os_4`.
pub const PARAM_C_OS_4: f64 = -1.76098915061634;
/// libxc default for `param_c_os_0`.
pub const PARAM_C_OS_0: f64 = 0.805124374375355;
/// libxc default for `param_hyb_omega_0`.
pub const PARAM_HYB_OMEGA_0: f64 = 0.3;

/// Number of libxc `ext_params` this dispatch accepts at runtime.
pub const N_EXT_PARAMS: usize = 16;

/// libxc `ext_params` names, in libxc's own order.
pub const EXT_PARAM_NAMES: [&str; 16] = ["_cx00", "_cx01", "_cx10", "_css00", "_css04", "_css10", "_css20", "_css43", "_cos00", "_cos10", "_cos20", "_cos21", "_cos60", "_alpha", "_beta", "_omega"];

/// Permutation: libxc `ext_params` index -> this kernel's argument slot.
///
/// `usize::MAX` marks an ext_param the kernel does not consume. Built by
/// *name* in `extract_params.py`, not by position -- the two orders differ for
/// most functionals, because libxc's order is its C params-struct order
/// (`util.c::copy_params` writes `ext_params[i]` into struct slot `i`) while
/// the kernel's is the maple2c argument order.
/// | libxc `ext_params` name | kernel argument |
/// |---|---|
/// | `_cx00` | `param_c_x_0` |
/// | `_cx01` | `param_c_x_1` |
/// | `_cx10` | `param_c_x_2` |
/// | `_css00` | `param_c_ss_0` |
/// | `_css04` | `param_c_ss_1` |
/// | `_css10` | `param_c_ss_2` |
/// | `_css20` | `param_c_ss_3` |
/// | `_css43` | `param_c_ss_4` |
/// | `_cos00` | `param_c_os_0` |
/// | `_cos10` | `param_c_os_1` |
/// | `_cos20` | `param_c_os_2` |
/// | `_cos21` | `param_c_os_3` |
/// | `_cos60` | `param_c_os_4` |
/// | `_alpha` | *(unused by the kernel)* |
/// | `_beta` | *(unused by the kernel)* |
/// | `_omega` | `param_hyb_omega_0` |
pub const EXT_TO_KERNEL: [usize; 16] = [2, 0, 1, 3, 4, 5, 6, 7, 12, 8, 9, 10, 11, usize::MAX, usize::MAX, 13];

/// Compiled-in libxc defaults, in kernel argument order.
pub const DEFAULTS: [f64; 14] = [PARAM_C_X_1, PARAM_C_X_2, PARAM_C_X_0, PARAM_C_SS_0, PARAM_C_SS_1, PARAM_C_SS_2, PARAM_C_SS_3, PARAM_C_SS_4, PARAM_C_OS_1, PARAM_C_OS_2, PARAM_C_OS_3, PARAM_C_OS_4, PARAM_C_OS_0, PARAM_HYB_OMEGA_0];

/// Same as [`dispatch`], with an optional caller-supplied `ext_params` array
/// in libxc's own order.
///
/// `None` is exactly [`dispatch`] -- same constants, same bits. `Some(e)`
/// starts from those defaults and overwrites only the slots `e` actually
/// feeds, so an ext_param the kernel ignores cannot disturb one it uses.
pub fn dispatch_with(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
    ext: Option<&[f64]>,
) -> Result<(), LibxcRsError> {
    let mut p = DEFAULTS;
    if let Some(e) = ext {
        if e.len() != N_EXT_PARAMS {
            return Err(LibxcRsError::ExtParamCountMismatch {
                id: libxc_core::model::FunctionalId(ID),
                expected: N_EXT_PARAMS,
                actual: e.len(),
            });
        }
        for (i, &slot) in EXT_TO_KERNEL.iter().enumerate() {
            if slot != usize::MAX {
                p[slot] = e[i];
            }
        }
    }
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::hyb_mgga_xc_gas22_exc_unpol],
        [k::vxc_unpol::hyb_mgga_xc_gas22_vxc_unpol],
        [k::fxc_unpol::hyb_mgga_xc_gas22_fxc_unpol],
        [k::kxc_unpol::hyb_mgga_xc_gas22_kxc_unpol],
        [k::lxc_unpol::hyb_mgga_xc_gas22_lxc_unpol],
        [k::exc_pol::hyb_mgga_xc_gas22_exc_pol],
        [k::vxc_pol::hyb_mgga_xc_gas22_vxc_pol],
        [k::fxc_pol::hyb_mgga_xc_gas22_fxc_pol],
        [k::kxc_pol::hyb_mgga_xc_gas22_kxc_pol],
        [k::lxc_pol::hyb_mgga_xc_gas22_lxc_pol],
        params = (p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9], p[10], p[11], p[12], p[13])
    )
}

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::hyb_mgga_xc_gas22_exc_unpol],
        [k::vxc_unpol::hyb_mgga_xc_gas22_vxc_unpol],
        [k::fxc_unpol::hyb_mgga_xc_gas22_fxc_unpol],
        [k::kxc_unpol::hyb_mgga_xc_gas22_kxc_unpol],
        [k::lxc_unpol::hyb_mgga_xc_gas22_lxc_unpol],
        [k::exc_pol::hyb_mgga_xc_gas22_exc_pol],
        [k::vxc_pol::hyb_mgga_xc_gas22_vxc_pol],
        [k::fxc_pol::hyb_mgga_xc_gas22_fxc_pol],
        [k::kxc_pol::hyb_mgga_xc_gas22_kxc_pol],
        [k::lxc_pol::hyb_mgga_xc_gas22_lxc_pol],
        params = (PARAM_C_X_1, PARAM_C_X_2, PARAM_C_X_0, PARAM_C_SS_0, PARAM_C_SS_1, PARAM_C_SS_2, PARAM_C_SS_3, PARAM_C_SS_4, PARAM_C_OS_1, PARAM_C_OS_2, PARAM_C_OS_3, PARAM_C_OS_4, PARAM_C_OS_0, PARAM_HYB_OMEGA_0)
    )
}
