//! Dispatch for `lda_c_upw92` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::LdaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::LdaOutput;

use libxc_rkernel_lda_c_pw as k;

/// libxc default for `param_a_0`.
pub const PARAM_A_0: f64 = 0.0310907;
/// libxc default for `param_alpha1_0`.
pub const PARAM_ALPHA1_0: f64 = 0.227012;
/// libxc default for `param_beta1_0`.
pub const PARAM_BETA1_0: f64 = 7.5957;
/// libxc default for `param_beta2_0`.
pub const PARAM_BETA2_0: f64 = 3.5876;
/// libxc default for `param_beta3_0`.
pub const PARAM_BETA3_0: f64 = 1.76522;
/// libxc default for `param_pp_0`.
pub const PARAM_PP_0: f64 = 1.0;
/// libxc default for `param_beta4_0`.
pub const PARAM_BETA4_0: f64 = 0.523918;
/// libxc default for `param_a_2`.
pub const PARAM_A_2: f64 = 0.0168869;
/// libxc default for `param_alpha1_2`.
pub const PARAM_ALPHA1_2: f64 = 0.11125;
/// libxc default for `param_beta1_2`.
pub const PARAM_BETA1_2: f64 = 10.357;
/// libxc default for `param_beta2_2`.
pub const PARAM_BETA2_2: f64 = 3.6231;
/// libxc default for `param_beta3_2`.
pub const PARAM_BETA3_2: f64 = 0.88026;
/// libxc default for `param_pp_2`.
pub const PARAM_PP_2: f64 = 1.0;
/// libxc default for `param_beta4_2`.
pub const PARAM_BETA4_2: f64 = 0.49671;
/// libxc default for `param_fz20`.
pub const PARAM_FZ20: f64 = 1.709920934161365617563962776245;
/// libxc default for `param_a_1`.
pub const PARAM_A_1: f64 = 0.01554535;
/// libxc default for `param_alpha1_1`.
pub const PARAM_ALPHA1_1: f64 = 0.264193;
/// libxc default for `param_beta1_1`.
pub const PARAM_BETA1_1: f64 = 14.1189;
/// libxc default for `param_beta2_1`.
pub const PARAM_BETA2_1: f64 = 6.1977;
/// libxc default for `param_beta3_1`.
pub const PARAM_BETA3_1: f64 = 4.78287;
/// libxc default for `param_pp_1`.
pub const PARAM_PP_1: f64 = 1.0;
/// libxc default for `param_beta4_1`.
pub const PARAM_BETA4_1: f64 = 0.750424;

pub fn dispatch(
    input: &LdaInput<'_>,
    output: &mut LdaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rlda!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::lda_c_pw_exc_unpol],
        [k::vxc_unpol::lda_c_pw_vxc_unpol],
        [k::fxc_unpol::lda_c_pw_fxc_unpol],
        [k::kxc_unpol::lda_c_pw_kxc_unpol],
        [k::lxc_unpol::lda_c_pw_lxc_unpol],
        [k::exc_pol::lda_c_pw_exc_pol],
        [k::vxc_pol::lda_c_pw_vxc_pol],
        [k::fxc_pol::lda_c_pw_fxc_pol],
        [k::kxc_pol::lda_c_pw_kxc_pol],
        [k::lxc_pol::lda_c_pw_lxc_pol],
        params = (PARAM_A_0, PARAM_ALPHA1_0, PARAM_BETA1_0, PARAM_BETA2_0, PARAM_BETA3_0, PARAM_PP_0, PARAM_BETA4_0, PARAM_A_2, PARAM_ALPHA1_2, PARAM_BETA1_2, PARAM_BETA2_2, PARAM_BETA3_2, PARAM_PP_2, PARAM_BETA4_2, PARAM_FZ20, PARAM_A_1, PARAM_ALPHA1_1, PARAM_BETA1_1, PARAM_BETA2_1, PARAM_BETA3_1, PARAM_PP_1, PARAM_BETA4_1)
    )
}
