//! Dispatch for `lda_c_rc04` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::LdaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::LdaOutput;

use libxc_rkernel_lda_c_rc04 as k;



pub fn dispatch(
    input: &LdaInput<'_>,
    output: &mut LdaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rlda!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::lda_c_rc04_exc_unpol],
        [k::vxc_unpol::lda_c_rc04_vxc_unpol],
        [k::fxc_unpol::lda_c_rc04_fxc_unpol],
        [k::kxc_unpol::lda_c_rc04_kxc_unpol],
        [k::lxc_unpol::lda_c_rc04_lxc_unpol],
        [k::exc_pol::lda_c_rc04_exc_pol],
        [k::vxc_pol::lda_c_rc04_vxc_pol],
        [k::fxc_pol::lda_c_rc04_fxc_pol],
        [k::kxc_pol::lda_c_rc04_kxc_pol],
        [k::lxc_pol::lda_c_rc04_lxc_pol],
        params = ()
    )
}
