//! Dispatch for `lda_c_hl` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::LdaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::LdaOutput;

use libxc_rkernel_lda_c_hl as k;

/// libxc default for `param_hl_c_0`.
pub const PARAM_HL_C_0: f64 = 0.0225;
/// libxc default for `param_hl_r_0`.
pub const PARAM_HL_R_0: f64 = 21.0;
/// libxc default for `param_hl_c_1`.
pub const PARAM_HL_C_1: f64 = 0.0225;
/// libxc default for `param_hl_r_1`.
pub const PARAM_HL_R_1: f64 = 21.0;

pub fn dispatch(
    input: &LdaInput<'_>,
    output: &mut LdaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rlda!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::lda_c_hl_exc_unpol],
        [k::vxc_unpol::lda_c_hl_vxc_unpol],
        [k::fxc_unpol::lda_c_hl_fxc_unpol],
        [k::kxc_unpol::lda_c_hl_kxc_unpol],
        [k::lxc_unpol::lda_c_hl_lxc_unpol],
        [k::exc_pol::lda_c_hl_exc_pol],
        [k::vxc_pol::lda_c_hl_vxc_pol],
        [k::fxc_pol::lda_c_hl_fxc_pol],
        [k::kxc_pol::lda_c_hl_kxc_pol],
        [k::lxc_pol::lda_c_hl_lxc_pol],
        params = (PARAM_HL_C_0, PARAM_HL_R_0, PARAM_HL_C_1, PARAM_HL_R_1)
    )
}
