//! Dispatch for `lda_c_karasiev_mod` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::LdaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::LdaOutput;

use libxc_rkernel_lda_c_chachiyo_mod as k;

/// libxc default for `param_af`.
pub const PARAM_AF: f64 = -0.007772675;
/// libxc default for `param_ap`.
pub const PARAM_AP: f64 = -0.01554535;
/// libxc default for `param_bf`.
pub const PARAM_BF: f64 = 28.3559732;
/// libxc default for `param_bp`.
pub const PARAM_BP: f64 = 21.7392245;
/// libxc default for `param_cf`.
pub const PARAM_CF: f64 = 27.4203609;
/// libxc default for `param_cp`.
pub const PARAM_CP: f64 = 20.4562557;

pub fn dispatch(
    input: &LdaInput<'_>,
    output: &mut LdaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rlda!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::lda_c_chachiyo_mod_exc_unpol],
        [k::vxc_unpol::lda_c_chachiyo_mod_vxc_unpol],
        [k::fxc_unpol::lda_c_chachiyo_mod_fxc_unpol],
        [k::kxc_unpol::lda_c_chachiyo_mod_kxc_unpol],
        [k::lxc_unpol::lda_c_chachiyo_mod_lxc_unpol],
        [k::exc_pol::lda_c_chachiyo_mod_exc_pol],
        [k::vxc_pol::lda_c_chachiyo_mod_vxc_pol],
        [k::fxc_pol::lda_c_chachiyo_mod_fxc_pol],
        [k::kxc_pol::lda_c_chachiyo_mod_kxc_pol],
        [k::lxc_pol::lda_c_chachiyo_mod_lxc_pol],
        params = (PARAM_AF, PARAM_AP, PARAM_BF, PARAM_BP, PARAM_CF, PARAM_CP)
    )
}
