//! Dispatch for `lda_xc_1d_ehwlrg_2` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::LdaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::LdaOutput;

use libxc_rkernel_lda_xc_1d_ehwlrg as k;

/// libxc default for `param_a2`.
pub const PARAM_A2: f64 = 0.68;
/// libxc default for `param_a3`.
pub const PARAM_A3: f64 = -0.38;
/// libxc default for `param_a1`.
pub const PARAM_A1: f64 = -0.74;
/// libxc default for `param_alpha`.
pub const PARAM_ALPHA: f64 = 0.604;

pub fn dispatch(
    input: &LdaInput<'_>,
    output: &mut LdaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rlda!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::lda_xc_1d_ehwlrg_exc_unpol],
        [k::vxc_unpol::lda_xc_1d_ehwlrg_vxc_unpol],
        [k::fxc_unpol::lda_xc_1d_ehwlrg_fxc_unpol],
        [k::kxc_unpol::lda_xc_1d_ehwlrg_kxc_unpol],
        [k::lxc_unpol::lda_xc_1d_ehwlrg_lxc_unpol],
        [k::exc_pol::lda_xc_1d_ehwlrg_exc_pol],
        [k::vxc_pol::lda_xc_1d_ehwlrg_vxc_pol],
        [k::fxc_pol::lda_xc_1d_ehwlrg_fxc_pol],
        [k::kxc_pol::lda_xc_1d_ehwlrg_kxc_pol],
        [k::lxc_pol::lda_xc_1d_ehwlrg_lxc_pol],
        params = (PARAM_A2, PARAM_A3, PARAM_A1, PARAM_ALPHA)
    )
}
