//! Dispatch for `lda_xc_gdsmfb` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::LdaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::LdaOutput;

use libxc_rkernel_lda_xc_ksdt as k;

/// libxc default for `param_T`.
pub const PARAM_T: f64 = 1e-08;
/// libxc default for `param_b_0_1`.
pub const PARAM_B_0_1: f64 = 7.82159531356;
/// libxc default for `param_b_0_2`.
pub const PARAM_B_0_2: f64 = 0.300483986662;
/// libxc default for `param_b_0_0`.
pub const PARAM_B_0_0: f64 = 0.3436902;
/// libxc default for `param_b_0_3`.
pub const PARAM_B_0_3: f64 = 15.8443467125;
/// libxc default for `param_b_0_4`.
pub const PARAM_B_0_4: f64 = 0.7062813835226853;
/// libxc default for `param_c_0_1`.
pub const PARAM_C_0_1: f64 = -0.230130843551;
/// libxc default for `param_c_0_2`.
pub const PARAM_C_0_2: f64 = 1.0;
/// libxc default for `param_c_0_0`.
pub const PARAM_C_0_0: f64 = 0.8759442;
/// libxc default for `param_e_0_1`.
pub const PARAM_E_0_1: f64 = 0.815795138599;
/// libxc default for `param_e_0_2`.
pub const PARAM_E_0_2: f64 = 0.0646844410481;
/// libxc default for `param_e_0_0`.
pub const PARAM_E_0_0: f64 = 0.25388214;
/// libxc default for `param_e_0_3`.
pub const PARAM_E_0_3: f64 = 15.0984620477;
/// libxc default for `param_e_0_4`.
pub const PARAM_E_0_4: f64 = 0.230761357474;
/// libxc default for `param_d_0_1`.
pub const PARAM_D_0_1: f64 = 2.38264734144;
/// libxc default for `param_d_0_2`.
pub const PARAM_D_0_2: f64 = 0.30221237251;
/// libxc default for `param_d_0_0`.
pub const PARAM_D_0_0: f64 = 0.72700876;
/// libxc default for `param_d_0_3`.
pub const PARAM_D_0_3: f64 = 4.39347718395;
/// libxc default for `param_d_0_4`.
pub const PARAM_D_0_4: f64 = 0.729951339845;
/// libxc default for `param_b_1_1`.
pub const PARAM_B_1_1: f64 = 3.04033012073;
/// libxc default for `param_b_1_2`.
pub const PARAM_B_1_2: f64 = 0.0775730131248;
/// libxc default for `param_b_1_0`.
pub const PARAM_B_1_0: f64 = 0.84987704;
/// libxc default for `param_b_1_3`.
pub const PARAM_B_1_3: f64 = 7.57703592489;
/// libxc default for `param_b_1_4`.
pub const PARAM_B_1_4: f64 = 0.22972614201992675;
/// libxc default for `param_c_1_1`.
pub const PARAM_C_1_1: f64 = -0.0307957123308;
/// libxc default for `param_c_1_2`.
pub const PARAM_C_1_2: f64 = 1.0;
/// libxc default for `param_c_1_0`.
pub const PARAM_C_1_0: f64 = 0.91126873;
/// libxc default for `param_e_1_1`.
pub const PARAM_E_1_1: f64 = 0.400994856555;
/// libxc default for `param_e_1_2`.
pub const PARAM_E_1_2: f64 = 2.88773194962;
/// libxc default for `param_e_1_0`.
pub const PARAM_E_1_0: f64 = 0.27454097;
/// libxc default for `param_e_1_3`.
pub const PARAM_E_1_3: f64 = 6.33499237092;
/// libxc default for `param_e_1_4`.
pub const PARAM_E_1_4: f64 = 24.823008753;
/// libxc default for `param_d_1_1`.
pub const PARAM_D_1_1: f64 = 4.92684905511;
/// libxc default for `param_d_1_2`.
pub const PARAM_D_1_2: f64 = 0.0849387225179;
/// libxc default for `param_d_1_0`.
pub const PARAM_D_1_0: f64 = 1.48658718;
/// libxc default for `param_d_1_3`.
pub const PARAM_D_1_3: f64 = 8.3269821188;
/// libxc default for `param_d_1_4`.
pub const PARAM_D_1_4: f64 = 0.218864952126;
/// libxc default for `param_thetaParam`.
pub const PARAM_THETAPARAM: f64 = 0.0;

pub fn dispatch(
    input: &LdaInput<'_>,
    output: &mut LdaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rlda!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::lda_xc_ksdt_exc_unpol],
        [k::vxc_unpol::lda_xc_ksdt_vxc_unpol],
        [k::fxc_unpol::lda_xc_ksdt_fxc_unpol],
        [k::kxc_unpol::lda_xc_ksdt_kxc_unpol],
        [k::lxc_unpol::lda_xc_ksdt_lxc_unpol],
        [k::exc_pol::lda_xc_ksdt_exc_pol],
        [k::vxc_pol::lda_xc_ksdt_vxc_pol],
        [k::fxc_pol::lda_xc_ksdt_fxc_pol],
        [k::kxc_pol::lda_xc_ksdt_kxc_pol],
        [k::lxc_pol::lda_xc_ksdt_lxc_pol],
        params = (PARAM_T, PARAM_B_0_1, PARAM_B_0_2, PARAM_B_0_0, PARAM_B_0_3, PARAM_B_0_4, PARAM_C_0_1, PARAM_C_0_2, PARAM_C_0_0, PARAM_E_0_1, PARAM_E_0_2, PARAM_E_0_0, PARAM_E_0_3, PARAM_E_0_4, PARAM_D_0_1, PARAM_D_0_2, PARAM_D_0_0, PARAM_D_0_3, PARAM_D_0_4, PARAM_B_1_1, PARAM_B_1_2, PARAM_B_1_0, PARAM_B_1_3, PARAM_B_1_4, PARAM_C_1_1, PARAM_C_1_2, PARAM_C_1_0, PARAM_E_1_1, PARAM_E_1_2, PARAM_E_1_0, PARAM_E_1_3, PARAM_E_1_4, PARAM_D_1_1, PARAM_D_1_2, PARAM_D_1_0, PARAM_D_1_3, PARAM_D_1_4, PARAM_THETAPARAM)
    )
}
