//! Dispatch for `lda_k_lp` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::LdaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::LdaOutput;

use libxc_rkernel_lda_k_tf as k;

/// libxc default for `param_ax`.
pub const PARAM_AX: f64 = 1.142427709758666675644309251677891925671;

pub fn dispatch(
    input: &LdaInput<'_>,
    output: &mut LdaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rlda!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::lda_k_tf_exc_unpol],
        [k::vxc_unpol::lda_k_tf_vxc_unpol],
        [k::fxc_unpol::lda_k_tf_fxc_unpol],
        [k::kxc_unpol::lda_k_tf_kxc_unpol],
        [k::lxc_unpol::lda_k_tf_lxc_unpol],
        [k::exc_pol::lda_k_tf_exc_pol],
        [k::vxc_pol::lda_k_tf_vxc_pol],
        [k::fxc_pol::lda_k_tf_fxc_pol],
        [k::kxc_pol::lda_k_tf_kxc_pol],
        [k::lxc_pol::lda_k_tf_lxc_pol],
        params = (PARAM_AX)
    )
}
