//! Dispatch for `lda_xc_corrksdt` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::LdaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::LdaOutput;

use libxc_rkernel_lda_xc_ksdt as k;

/// libxc's raw integer id for this functional.
pub const ID: u16 = 318;

/// libxc default for `param_T`.
pub const PARAM_T: f64 = 1e-08;
/// libxc default for `param_b_0_1`.
pub const PARAM_B_0_1: f64 = 9.141315;
/// libxc default for `param_b_0_2`.
pub const PARAM_B_0_2: f64 = 0.448483;
/// libxc default for `param_b_0_0`.
pub const PARAM_B_0_0: f64 = 0.342554;
/// libxc default for `param_b_0_3`.
pub const PARAM_B_0_3: f64 = 18.553096;
/// libxc default for `param_b_0_4`.
pub const PARAM_B_0_4: f64 = 1.054149997293224;
/// libxc default for `param_c_0_1`.
pub const PARAM_C_0_1: f64 = -0.25632;
/// libxc default for `param_c_0_2`.
pub const PARAM_C_0_2: f64 = 0.953988;
/// libxc default for `param_c_0_0`.
pub const PARAM_C_0_0: f64 = 0.87513;
/// libxc default for `param_e_0_1`.
pub const PARAM_E_0_1: f64 = 0.931933;
/// libxc default for `param_e_0_2`.
pub const PARAM_E_0_2: f64 = 0.115398;
/// libxc default for `param_e_0_0`.
pub const PARAM_E_0_0: f64 = 0.255415;
/// libxc default for `param_e_0_3`.
pub const PARAM_E_0_3: f64 = 17.234117;
/// libxc default for `param_e_0_4`.
pub const PARAM_E_0_4: f64 = 0.451437;
/// libxc default for `param_d_0_1`.
pub const PARAM_D_0_1: f64 = 2.237347;
/// libxc default for `param_d_0_2`.
pub const PARAM_D_0_2: f64 = 0.280748;
/// libxc default for `param_d_0_0`.
pub const PARAM_D_0_0: f64 = 0.725917;
/// libxc default for `param_d_0_3`.
pub const PARAM_D_0_3: f64 = 4.185911;
/// libxc default for `param_d_0_4`.
pub const PARAM_D_0_4: f64 = 0.692183;
/// libxc default for `param_b_1_1`.
pub const PARAM_B_1_1: f64 = 111.598308;
/// libxc default for `param_b_1_2`.
pub const PARAM_B_1_2: f64 = 0.537053;
/// libxc default for `param_b_1_0`.
pub const PARAM_B_1_0: f64 = 0.329001;
/// libxc default for `param_b_1_3`.
pub const PARAM_B_1_3: f64 = 105.086663;
/// libxc default for `param_b_1_4`.
pub const PARAM_B_1_4: f64 = 1.262331946799138;
/// libxc default for `param_c_1_1`.
pub const PARAM_C_1_1: f64 = 0.167952;
/// libxc default for `param_c_1_2`.
pub const PARAM_C_1_2: f64 = 0.08882;
/// libxc default for `param_c_1_0`.
pub const PARAM_C_1_0: f64 = 0.84893;
/// libxc default for `param_e_1_1`.
pub const PARAM_E_1_1: f64 = 19.543945;
/// libxc default for `param_e_1_2`.
pub const PARAM_E_1_2: f64 = 43.400337;
/// libxc default for `param_e_1_0`.
pub const PARAM_E_1_0: f64 = 0.153124;
/// libxc default for `param_e_1_3`.
pub const PARAM_E_1_3: f64 = 120.255145;
/// libxc default for `param_e_1_4`.
pub const PARAM_E_1_4: f64 = 15.662836;
/// libxc default for `param_d_1_1`.
pub const PARAM_D_1_1: f64 = 180.213159;
/// libxc default for `param_d_1_2`.
pub const PARAM_D_1_2: f64 = 134.486231;
/// libxc default for `param_d_1_0`.
pub const PARAM_D_1_0: f64 = 0.55133;
/// libxc default for `param_d_1_3`.
pub const PARAM_D_1_3: f64 = 103.861695;
/// libxc default for `param_d_1_4`.
pub const PARAM_D_1_4: f64 = 17.75071;
/// libxc default for `param_thetaParam`.
pub const PARAM_THETAPARAM: f64 = 0.0;

/// Number of libxc `ext_params` this dispatch accepts at runtime: none,
/// because its libxc ext_params could not be put in correspondence with the kernel's arguments; see extract_params.py.
pub const N_EXT_PARAMS: usize = 0;

/// Same as [`dispatch`], with an optional caller-supplied `ext_params` array
/// in libxc's own order.
///
/// This functional does not accept runtime ext_params (its libxc ext_params could not be put in correspondence with the kernel's arguments; see extract_params.py), so a non-empty
/// `ext` is rejected rather than guessed at.
pub fn dispatch_with(
    input: &LdaInput<'_>,
    output: &mut LdaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
    ext: Option<&[f64]>,
) -> Result<(), LibxcRsError> {
    if let Some(e) = ext
        && !e.is_empty()
    {
        return Err(LibxcRsError::ExtParamCountMismatch {
            id: libxc_core::model::FunctionalId(ID),
            expected: 0,
            actual: e.len(),
        });
    }
    dispatch(input, output, order, spin, thresholds)
}

pub fn dispatch(
    input: &LdaInput<'_>,
    output: &mut LdaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rlda!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::lda_xc_ksdt_exc_unpol],
        [k::vxc_unpol::lda_xc_ksdt_vxc_unpol],
        [k::fxc_unpol::lda_xc_ksdt_fxc_unpol],
        [k::kxc_unpol::lda_xc_ksdt_kxc_unpol],
        [k::lxc_unpol::lda_xc_ksdt_lxc_unpol],
        [k::exc_pol::lda_xc_ksdt_exc_pol],
        [k::vxc_pol::lda_xc_ksdt_vxc_pol],
        [k::fxc_pol::lda_xc_ksdt_fxc_pol],
        [k::kxc_pol::lda_xc_ksdt_kxc_pol],
        [k::lxc_pol::lda_xc_ksdt_lxc_pol],
        params = (PARAM_T, PARAM_B_0_1, PARAM_B_0_2, PARAM_B_0_0, PARAM_B_0_3, PARAM_B_0_4, PARAM_C_0_1, PARAM_C_0_2, PARAM_C_0_0, PARAM_E_0_1, PARAM_E_0_2, PARAM_E_0_0, PARAM_E_0_3, PARAM_E_0_4, PARAM_D_0_1, PARAM_D_0_2, PARAM_D_0_0, PARAM_D_0_3, PARAM_D_0_4, PARAM_B_1_1, PARAM_B_1_2, PARAM_B_1_0, PARAM_B_1_3, PARAM_B_1_4, PARAM_C_1_1, PARAM_C_1_2, PARAM_C_1_0, PARAM_E_1_1, PARAM_E_1_2, PARAM_E_1_0, PARAM_E_1_3, PARAM_E_1_4, PARAM_D_1_1, PARAM_D_1_2, PARAM_D_1_0, PARAM_D_1_3, PARAM_D_1_4, PARAM_THETAPARAM)
    )
}
