//! Dispatch for `mgga_x_m11_l` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_x_m11_l as k;

/// libxc's raw integer id for this functional.
pub const ID: u16 = 226;

/// libxc default for `param_a_1`.
pub const PARAM_A_1: f64 = 1.738124e+01;
/// libxc default for `param_a_2`.
pub const PARAM_A_2: f64 = 1.154007e+00;
/// libxc default for `param_a_3`.
pub const PARAM_A_3: f64 = 6.869556e+01;
/// libxc default for `param_a_4`.
pub const PARAM_A_4: f64 = 1.016864e+02;
/// libxc default for `param_a_5`.
pub const PARAM_A_5: f64 = -5.887467e+00;
/// libxc default for `param_a_6`.
pub const PARAM_A_6: f64 = 4.517409e+01;
/// libxc default for `param_a_7`.
pub const PARAM_A_7: f64 = -2.773149e+00;
/// libxc default for `param_a_8`.
pub const PARAM_A_8: f64 = -2.617211e+01;
/// libxc default for `param_a_9`.
pub const PARAM_A_9: f64 = 0.000000e+00;
/// libxc default for `param_a_10`.
pub const PARAM_A_10: f64 = 0.000000e+00;
/// libxc default for `param_a_11`.
pub const PARAM_A_11: f64 = 0.000000e+00;
/// libxc default for `param_a_0`.
pub const PARAM_A_0: f64 = 8.121131e-01;
/// libxc default for `param_b_1`.
pub const PARAM_B_1: f64 = -1.653877e+01;
/// libxc default for `param_b_2`.
pub const PARAM_B_2: f64 = 6.755753e-01;
/// libxc default for `param_b_3`.
pub const PARAM_B_3: f64 = -7.567572e+01;
/// libxc default for `param_b_4`.
pub const PARAM_B_4: f64 = -1.040272e+02;
/// libxc default for `param_b_5`.
pub const PARAM_B_5: f64 = 1.831853e+01;
/// libxc default for `param_b_6`.
pub const PARAM_B_6: f64 = -5.573352e+01;
/// libxc default for `param_b_7`.
pub const PARAM_B_7: f64 = -3.520210e+00;
/// libxc default for `param_b_8`.
pub const PARAM_B_8: f64 = 3.724276e+01;
/// libxc default for `param_b_9`.
pub const PARAM_B_9: f64 = 0.000000e+00;
/// libxc default for `param_b_10`.
pub const PARAM_B_10: f64 = 0.000000e+00;
/// libxc default for `param_b_11`.
pub const PARAM_B_11: f64 = 0.000000e+00;
/// libxc default for `param_b_0`.
pub const PARAM_B_0: f64 = 1.878869e-01;
/// libxc default for `param_c_1`.
pub const PARAM_C_1: f64 = -1.214016e+02;
/// libxc default for `param_c_2`.
pub const PARAM_C_2: f64 = -1.393573e+02;
/// libxc default for `param_c_3`.
pub const PARAM_C_3: f64 = -2.046649e+00;
/// libxc default for `param_c_4`.
pub const PARAM_C_4: f64 = 2.804098e+01;
/// libxc default for `param_c_5`.
pub const PARAM_C_5: f64 = -1.312258e+01;
/// libxc default for `param_c_6`.
pub const PARAM_C_6: f64 = -6.361819e+00;
/// libxc default for `param_c_7`.
pub const PARAM_C_7: f64 = -8.055758e-01;
/// libxc default for `param_c_8`.
pub const PARAM_C_8: f64 = 3.736551e+00;
/// libxc default for `param_c_9`.
pub const PARAM_C_9: f64 = 0.000000e+00;
/// libxc default for `param_c_10`.
pub const PARAM_C_10: f64 = 0.000000e+00;
/// libxc default for `param_c_11`.
pub const PARAM_C_11: f64 = 0.000000e+00;
/// libxc default for `param_c_0`.
pub const PARAM_C_0: f64 = -4.386615e-01;
/// libxc default for `param_d_1`.
pub const PARAM_D_1: f64 = 1.209465e+02;
/// libxc default for `param_d_2`.
pub const PARAM_D_2: f64 = 1.328252e+02;
/// libxc default for `param_d_3`.
pub const PARAM_D_3: f64 = 1.296355e+01;
/// libxc default for `param_d_4`.
pub const PARAM_D_4: f64 = 5.854866e+00;
/// libxc default for `param_d_5`.
pub const PARAM_D_5: f64 = -3.378162e+00;
/// libxc default for `param_d_6`.
pub const PARAM_D_6: f64 = -4.423393e+01;
/// libxc default for `param_d_7`.
pub const PARAM_D_7: f64 = 6.844475e+00;
/// libxc default for `param_d_8`.
pub const PARAM_D_8: f64 = 1.949541e+01;
/// libxc default for `param_d_9`.
pub const PARAM_D_9: f64 = 0.000000e+00;
/// libxc default for `param_d_10`.
pub const PARAM_D_10: f64 = 0.000000e+00;
/// libxc default for `param_d_11`.
pub const PARAM_D_11: f64 = 0.000000e+00;
/// libxc default for `param_d_0`.
pub const PARAM_D_0: f64 = 1.438662e+00;
/// libxc default for `param_hyb_omega_0`.
pub const PARAM_HYB_OMEGA_0: f64 = 0.25;

/// Number of libxc `ext_params` this dispatch accepts at runtime.
pub const N_EXT_PARAMS: usize = 49;

/// libxc `ext_params` names, in libxc's own order.
pub const EXT_PARAM_NAMES: [&str; 49] = ["_a0", "_a1", "_a2", "_a3", "_a4", "_a5", "_a6", "_a7", "_a8", "_a9", "_a10", "_a11", "_b0", "_b1", "_b2", "_b3", "_b4", "_b5", "_b6", "_b7", "_b8", "_b9", "_b10", "_b11", "_c0", "_c1", "_c2", "_c3", "_c4", "_c5", "_c6", "_c7", "_c8", "_c9", "_c10", "_c11", "_d0", "_d1", "_d2", "_d3", "_d4", "_d5", "_d6", "_d7", "_d8", "_d9", "_d10", "_d11", "_omega"];

/// Permutation: libxc `ext_params` index -> this kernel's argument slot.
///
/// `usize::MAX` marks an ext_param the kernel does not consume. Built by
/// *name* in `extract_params.py`, not by position -- the two orders differ for
/// most functionals, because libxc's order is its C params-struct order
/// (`util.c::copy_params` writes `ext_params[i]` into struct slot `i`) while
/// the kernel's is the maple2c argument order.
/// | libxc `ext_params` name | kernel argument |
/// |---|---|
/// | `_a0` | `param_a_0` |
/// | `_a1` | `param_a_1` |
/// | `_a2` | `param_a_2` |
/// | `_a3` | `param_a_3` |
/// | `_a4` | `param_a_4` |
/// | `_a5` | `param_a_5` |
/// | `_a6` | `param_a_6` |
/// | `_a7` | `param_a_7` |
/// | `_a8` | `param_a_8` |
/// | `_a9` | `param_a_9` |
/// | `_a10` | `param_a_10` |
/// | `_a11` | `param_a_11` |
/// | `_b0` | `param_b_0` |
/// | `_b1` | `param_b_1` |
/// | `_b2` | `param_b_2` |
/// | `_b3` | `param_b_3` |
/// | `_b4` | `param_b_4` |
/// | `_b5` | `param_b_5` |
/// | `_b6` | `param_b_6` |
/// | `_b7` | `param_b_7` |
/// | `_b8` | `param_b_8` |
/// | `_b9` | `param_b_9` |
/// | `_b10` | `param_b_10` |
/// | `_b11` | `param_b_11` |
/// | `_c0` | `param_c_0` |
/// | `_c1` | `param_c_1` |
/// | `_c2` | `param_c_2` |
/// | `_c3` | `param_c_3` |
/// | `_c4` | `param_c_4` |
/// | `_c5` | `param_c_5` |
/// | `_c6` | `param_c_6` |
/// | `_c7` | `param_c_7` |
/// | `_c8` | `param_c_8` |
/// | `_c9` | `param_c_9` |
/// | `_c10` | `param_c_10` |
/// | `_c11` | `param_c_11` |
/// | `_d0` | `param_d_0` |
/// | `_d1` | `param_d_1` |
/// | `_d2` | `param_d_2` |
/// | `_d3` | `param_d_3` |
/// | `_d4` | `param_d_4` |
/// | `_d5` | `param_d_5` |
/// | `_d6` | `param_d_6` |
/// | `_d7` | `param_d_7` |
/// | `_d8` | `param_d_8` |
/// | `_d9` | `param_d_9` |
/// | `_d10` | `param_d_10` |
/// | `_d11` | `param_d_11` |
/// | `_omega` | `param_hyb_omega_0` |
pub const EXT_TO_KERNEL: [usize; 49] = [11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 23, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 35, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 47, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 48];

/// Compiled-in libxc defaults, in kernel argument order.
pub const DEFAULTS: [f64; 49] = [PARAM_A_1, PARAM_A_2, PARAM_A_3, PARAM_A_4, PARAM_A_5, PARAM_A_6, PARAM_A_7, PARAM_A_8, PARAM_A_9, PARAM_A_10, PARAM_A_11, PARAM_A_0, PARAM_B_1, PARAM_B_2, PARAM_B_3, PARAM_B_4, PARAM_B_5, PARAM_B_6, PARAM_B_7, PARAM_B_8, PARAM_B_9, PARAM_B_10, PARAM_B_11, PARAM_B_0, PARAM_C_1, PARAM_C_2, PARAM_C_3, PARAM_C_4, PARAM_C_5, PARAM_C_6, PARAM_C_7, PARAM_C_8, PARAM_C_9, PARAM_C_10, PARAM_C_11, PARAM_C_0, PARAM_D_1, PARAM_D_2, PARAM_D_3, PARAM_D_4, PARAM_D_5, PARAM_D_6, PARAM_D_7, PARAM_D_8, PARAM_D_9, PARAM_D_10, PARAM_D_11, PARAM_D_0, PARAM_HYB_OMEGA_0];

/// Same as [`dispatch`], with an optional caller-supplied `ext_params` array
/// in libxc's own order.
///
/// `None` is exactly [`dispatch`] -- same constants, same bits. `Some(e)`
/// starts from those defaults and overwrites only the slots `e` actually
/// feeds, so an ext_param the kernel ignores cannot disturb one it uses.
pub fn dispatch_with(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
    ext: Option<&[f64]>,
) -> Result<(), LibxcRsError> {
    let mut p = DEFAULTS;
    if let Some(e) = ext {
        if e.len() != N_EXT_PARAMS {
            return Err(LibxcRsError::ExtParamCountMismatch {
                id: libxc_core::model::FunctionalId(ID),
                expected: N_EXT_PARAMS,
                actual: e.len(),
            });
        }
        for (i, &slot) in EXT_TO_KERNEL.iter().enumerate() {
            if slot != usize::MAX {
                p[slot] = e[i];
            }
        }
    }
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_x_m11_l_exc_unpol],
        [k::vxc_unpol::mgga_x_m11_l_vxc_unpol],
        [k::fxc_unpol::mgga_x_m11_l_fxc_unpol],
        [k::kxc_unpol::mgga_x_m11_l_kxc_unpol],
        [k::lxc_unpol::mgga_x_m11_l_lxc_unpol],
        [k::exc_pol::mgga_x_m11_l_exc_pol],
        [k::vxc_pol::mgga_x_m11_l_vxc_pol],
        [k::fxc_pol::mgga_x_m11_l_fxc_pol],
        [k::kxc_pol::mgga_x_m11_l_kxc_pol],
        [k::lxc_pol::mgga_x_m11_l_lxc_pol],
        params = (p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9], p[10], p[11], p[12], p[13], p[14], p[15], p[16], p[17], p[18], p[19], p[20], p[21], p[22], p[23], p[24], p[25], p[26], p[27], p[28], p[29], p[30], p[31], p[32], p[33], p[34], p[35], p[36], p[37], p[38], p[39], p[40], p[41], p[42], p[43], p[44], p[45], p[46], p[47], p[48])
    )
}

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_x_m11_l_exc_unpol],
        [k::vxc_unpol::mgga_x_m11_l_vxc_unpol],
        [k::fxc_unpol::mgga_x_m11_l_fxc_unpol],
        [k::kxc_unpol::mgga_x_m11_l_kxc_unpol],
        [k::lxc_unpol::mgga_x_m11_l_lxc_unpol],
        [k::exc_pol::mgga_x_m11_l_exc_pol],
        [k::vxc_pol::mgga_x_m11_l_vxc_pol],
        [k::fxc_pol::mgga_x_m11_l_fxc_pol],
        [k::kxc_pol::mgga_x_m11_l_kxc_pol],
        [k::lxc_pol::mgga_x_m11_l_lxc_pol],
        params = (PARAM_A_1, PARAM_A_2, PARAM_A_3, PARAM_A_4, PARAM_A_5, PARAM_A_6, PARAM_A_7, PARAM_A_8, PARAM_A_9, PARAM_A_10, PARAM_A_11, PARAM_A_0, PARAM_B_1, PARAM_B_2, PARAM_B_3, PARAM_B_4, PARAM_B_5, PARAM_B_6, PARAM_B_7, PARAM_B_8, PARAM_B_9, PARAM_B_10, PARAM_B_11, PARAM_B_0, PARAM_C_1, PARAM_C_2, PARAM_C_3, PARAM_C_4, PARAM_C_5, PARAM_C_6, PARAM_C_7, PARAM_C_8, PARAM_C_9, PARAM_C_10, PARAM_C_11, PARAM_C_0, PARAM_D_1, PARAM_D_2, PARAM_D_3, PARAM_D_4, PARAM_D_5, PARAM_D_6, PARAM_D_7, PARAM_D_8, PARAM_D_9, PARAM_D_10, PARAM_D_11, PARAM_D_0, PARAM_HYB_OMEGA_0)
    )
}
