//! Dispatch for `mgga_x_r4scan` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_x_r4scan as k;

/// libxc default for `param_c1`.
pub const PARAM_C1: f64 = 0.667;
/// libxc default for `param_c2`.
pub const PARAM_C2: f64 = 0.8;
/// libxc default for `param_d`.
pub const PARAM_D: f64 = 1.24;
/// libxc default for `param_da4`.
pub const PARAM_DA4: f64 = 0.178;
/// libxc default for `param_dp2`.
pub const PARAM_DP2: f64 = 0.361;
/// libxc default for `param_dp4`.
pub const PARAM_DP4: f64 = 0.802;
/// libxc default for `param_eta`.
pub const PARAM_ETA: f64 = 0.001;
/// libxc default for `param_k1`.
pub const PARAM_K1: f64 = 0.065;

pub fn dispatch<'a>(
    input: &'a MggaInput<'a>,
    output: &'a mut MggaOutput<'a>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_x_r4scan_exc_unpol],
        [k::vxc_unpol::mgga_x_r4scan_vxc_unpol],
        [k::fxc_unpol::mgga_x_r4scan_fxc_unpol],
        [k::kxc_unpol::mgga_x_r4scan_kxc_unpol],
        [k::lxc_unpol::mgga_x_r4scan_lxc_unpol],
        [k::exc_pol::mgga_x_r4scan_exc_pol],
        [k::vxc_pol::mgga_x_r4scan_vxc_pol],
        [k::fxc_pol::mgga_x_r4scan_fxc_pol],
        [k::kxc_pol::mgga_x_r4scan_kxc_pol],
        [k::lxc_pol::mgga_x_r4scan_lxc_pol],
        params = (PARAM_C1, PARAM_C2, PARAM_D, PARAM_DA4, PARAM_DP2, PARAM_DP4, PARAM_ETA, PARAM_K1)
    )
}
