//! Dispatch for `mgga_k_rda` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_k_rda as k;

/// libxc's raw integer id for this functional.
pub const ID: u16 = 621;

/// libxc default for `param_A0`.
pub const PARAM_A0: f64 = 0.50616;
/// libxc default for `param_A1`.
pub const PARAM_A1: f64 = 3.04121;
/// libxc default for `param_A2`.
pub const PARAM_A2: f64 = -0.34567;
/// libxc default for `param_A3`.
pub const PARAM_A3: f64 = -1.89738;
/// libxc default for `param_a`.
pub const PARAM_A: f64 = 46.47662;
/// libxc default for `param_b`.
pub const PARAM_B: f64 = 18.80658;
/// libxc default for `param_beta1`.
pub const PARAM_BETA1: f64 = 1.29691;
/// libxc default for `param_beta2`.
pub const PARAM_BETA2: f64 = 0.56184;
/// libxc default for `param_beta3`.
pub const PARAM_BETA3: f64 = 0.21944;
/// libxc default for `param_c`.
pub const PARAM_C: f64 = -0.90346;

/// Number of libxc `ext_params` this dispatch accepts at runtime.
pub const N_EXT_PARAMS: usize = 10;

/// libxc `ext_params` names, in libxc's own order.
pub const EXT_PARAM_NAMES: [&str; 10] = ["_A0", "_A1", "_A2", "_A3", "_beta1", "_beta2", "_beta3", "_a", "_b", "_c"];

/// Permutation: libxc `ext_params` index -> this kernel's argument slot.
///
/// `usize::MAX` marks an ext_param the kernel does not consume. Built by
/// *name* in `extract_params.py`, not by position -- the two orders differ for
/// most functionals, because libxc's order is its C params-struct order
/// (`util.c::copy_params` writes `ext_params[i]` into struct slot `i`) while
/// the kernel's is the maple2c argument order.
/// | libxc `ext_params` name | kernel argument |
/// |---|---|
/// | `_A0` | `param_A0` |
/// | `_A1` | `param_A1` |
/// | `_A2` | `param_A2` |
/// | `_A3` | `param_A3` |
/// | `_beta1` | `param_beta1` |
/// | `_beta2` | `param_beta2` |
/// | `_beta3` | `param_beta3` |
/// | `_a` | `param_a` |
/// | `_b` | `param_b` |
/// | `_c` | `param_c` |
pub const EXT_TO_KERNEL: [usize; 10] = [0, 1, 2, 3, 6, 7, 8, 4, 5, 9];

/// Compiled-in libxc defaults, in kernel argument order.
pub const DEFAULTS: [f64; 10] = [PARAM_A0, PARAM_A1, PARAM_A2, PARAM_A3, PARAM_A, PARAM_B, PARAM_BETA1, PARAM_BETA2, PARAM_BETA3, PARAM_C];

/// Same as [`dispatch`], with an optional caller-supplied `ext_params` array
/// in libxc's own order.
///
/// `None` is exactly [`dispatch`] -- same constants, same bits. `Some(e)`
/// starts from those defaults and overwrites only the slots `e` actually
/// feeds, so an ext_param the kernel ignores cannot disturb one it uses.
pub fn dispatch_with(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
    ext: Option<&[f64]>,
) -> Result<(), LibxcRsError> {
    let mut p = DEFAULTS;
    if let Some(e) = ext {
        if e.len() != N_EXT_PARAMS {
            return Err(LibxcRsError::ExtParamCountMismatch {
                id: libxc_core::model::FunctionalId(ID),
                expected: N_EXT_PARAMS,
                actual: e.len(),
            });
        }
        for (i, &slot) in EXT_TO_KERNEL.iter().enumerate() {
            if slot != usize::MAX {
                p[slot] = e[i];
            }
        }
    }
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_k_rda_exc_unpol],
        [k::vxc_unpol::mgga_k_rda_vxc_unpol],
        [k::fxc_unpol::mgga_k_rda_fxc_unpol],
        [k::kxc_unpol::mgga_k_rda_kxc_unpol],
        [k::lxc_unpol::mgga_k_rda_lxc_unpol],
        [k::exc_pol::mgga_k_rda_exc_pol],
        [k::vxc_pol::mgga_k_rda_vxc_pol],
        [k::fxc_pol::mgga_k_rda_fxc_pol],
        [k::kxc_pol::mgga_k_rda_kxc_pol],
        [k::lxc_pol::mgga_k_rda_lxc_pol],
        params = (p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9])
    )
}

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_k_rda_exc_unpol],
        [k::vxc_unpol::mgga_k_rda_vxc_unpol],
        [k::fxc_unpol::mgga_k_rda_fxc_unpol],
        [k::kxc_unpol::mgga_k_rda_kxc_unpol],
        [k::lxc_unpol::mgga_k_rda_lxc_unpol],
        [k::exc_pol::mgga_k_rda_exc_pol],
        [k::vxc_pol::mgga_k_rda_vxc_pol],
        [k::fxc_pol::mgga_k_rda_fxc_pol],
        [k::kxc_pol::mgga_k_rda_kxc_pol],
        [k::lxc_pol::mgga_k_rda_lxc_pol],
        params = (PARAM_A0, PARAM_A1, PARAM_A2, PARAM_A3, PARAM_A, PARAM_B, PARAM_BETA1, PARAM_BETA2, PARAM_BETA3, PARAM_C)
    )
}
