//! Dispatch for `mgga_c_cc` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_c_cc as k;



pub fn dispatch<'a>(
    input: &'a MggaInput<'a>,
    output: &'a mut MggaOutput<'a>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_c_cc_exc_unpol],
        [k::vxc_unpol::mgga_c_cc_vxc_unpol],
        [k::fxc_unpol::mgga_c_cc_fxc_unpol],
        [k::kxc_unpol::mgga_c_cc_kxc_unpol],
        [k::lxc_unpol::mgga_c_cc_lxc_unpol],
        [k::exc_pol::mgga_c_cc_exc_pol],
        [k::vxc_pol::mgga_c_cc_vxc_pol],
        [k::fxc_pol::mgga_c_cc_fxc_pol],
        [k::kxc_pol::mgga_c_cc_kxc_pol],
        [k::lxc_pol::mgga_c_cc_lxc_pol],
        params = ()
    )
}
