//! Dispatch for `mgga_x_mn12_l` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_x_mn12 as k;

/// libxc default for `param_c_1`.
pub const PARAM_C_1: f64 = -2.270598e+00;
/// libxc default for `param_c_2`.
pub const PARAM_C_2: f64 = -2.613712e+00;
/// libxc default for `param_c_3`.
pub const PARAM_C_3: f64 = 3.993609e+00;
/// libxc default for `param_c_4`.
pub const PARAM_C_4: f64 = 4.635575e+00;
/// libxc default for `param_c_5`.
pub const PARAM_C_5: f64 = 1.250676e+00;
/// libxc default for `param_c_7`.
pub const PARAM_C_7: f64 = -1.301173e+01;
/// libxc default for `param_c_8`.
pub const PARAM_C_8: f64 = -1.777730e+01;
/// libxc default for `param_c_9`.
pub const PARAM_C_9: f64 = -4.627211e+00;
/// libxc default for `param_c_10`.
pub const PARAM_C_10: f64 = 5.976605e+00;
/// libxc default for `param_c_6`.
pub const PARAM_C_6: f64 = 8.444920e-01;
/// libxc default for `param_c_12`.
pub const PARAM_C_12: f64 = -2.040226e+01;
/// libxc default for `param_c_13`.
pub const PARAM_C_13: f64 = -2.382843e+01;
/// libxc default for `param_c_14`.
pub const PARAM_C_14: f64 = 7.119109e+00;
/// libxc default for `param_c_11`.
pub const PARAM_C_11: f64 = 1.142897e+00;
/// libxc default for `param_c_16`.
pub const PARAM_C_16: f64 = -1.622633e+01;
/// libxc default for `param_c_17`.
pub const PARAM_C_17: f64 = 1.482732e+01;
/// libxc default for `param_c_15`.
pub const PARAM_C_15: f64 = -2.335726e+01;
/// libxc default for `param_c_19`.
pub const PARAM_C_19: f64 = 1.020598e+01;
/// libxc default for `param_c_20`.
pub const PARAM_C_20: f64 = 4.407450e+00;
/// libxc default for `param_c_21`.
pub const PARAM_C_21: f64 = -2.008193e+01;
/// libxc default for `param_c_22`.
pub const PARAM_C_22: f64 = -1.253561e+01;
/// libxc default for `param_c_18`.
pub const PARAM_C_18: f64 = 1.449285e+00;
/// libxc default for `param_c_24`.
pub const PARAM_C_24: f64 = 1.656736e+01;
/// libxc default for `param_c_25`.
pub const PARAM_C_25: f64 = 2.000229e+01;
/// libxc default for `param_c_26`.
pub const PARAM_C_26: f64 = -2.513105e+00;
/// libxc default for `param_c_23`.
pub const PARAM_C_23: f64 = -5.435031e+00;
/// libxc default for `param_c_28`.
pub const PARAM_C_28: f64 = -3.825281e+00;
/// libxc default for `param_c_29`.
pub const PARAM_C_29: f64 = -2.500000e+01;
/// libxc default for `param_c_27`.
pub const PARAM_C_27: f64 = 9.658436e+00;
/// libxc default for `param_c_31`.
pub const PARAM_C_31: f64 = -9.951913e+00;
/// libxc default for `param_c_32`.
pub const PARAM_C_32: f64 = 8.731211e-01;
/// libxc default for `param_c_33`.
pub const PARAM_C_33: f64 = 2.210891e+01;
/// libxc default for `param_c_30`.
pub const PARAM_C_30: f64 = -2.070080e+00;
/// libxc default for `param_c_35`.
pub const PARAM_C_35: f64 = 2.499949e+01;
/// libxc default for `param_c_36`.
pub const PARAM_C_36: f64 = 2.500000e+01;
/// libxc default for `param_c_34`.
pub const PARAM_C_34: f64 = 8.822633e+00;
/// libxc default for `param_c_38`.
pub const PARAM_C_38: f64 = -7.406948e-02;
/// libxc default for `param_c_39`.
pub const PARAM_C_39: f64 = -6.788000e-01;
/// libxc default for `param_c_37`.
pub const PARAM_C_37: f64 = 6.851693e-01;
/// libxc default for `param_c_0`.
pub const PARAM_C_0: f64 = 6.735981e-01;

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_x_mn12_exc_unpol],
        [k::vxc_unpol::mgga_x_mn12_vxc_unpol],
        [k::fxc_unpol::mgga_x_mn12_fxc_unpol],
        [k::kxc_unpol::mgga_x_mn12_kxc_unpol],
        [k::lxc_unpol::mgga_x_mn12_lxc_unpol],
        [k::exc_pol::mgga_x_mn12_exc_pol],
        [k::vxc_pol::mgga_x_mn12_vxc_pol],
        [k::fxc_pol::mgga_x_mn12_fxc_pol],
        [k::kxc_pol::mgga_x_mn12_kxc_pol],
        [k::lxc_pol::mgga_x_mn12_lxc_pol],
        params = (PARAM_C_1, PARAM_C_2, PARAM_C_3, PARAM_C_4, PARAM_C_5, PARAM_C_7, PARAM_C_8, PARAM_C_9, PARAM_C_10, PARAM_C_6, PARAM_C_12, PARAM_C_13, PARAM_C_14, PARAM_C_11, PARAM_C_16, PARAM_C_17, PARAM_C_15, PARAM_C_19, PARAM_C_20, PARAM_C_21, PARAM_C_22, PARAM_C_18, PARAM_C_24, PARAM_C_25, PARAM_C_26, PARAM_C_23, PARAM_C_28, PARAM_C_29, PARAM_C_27, PARAM_C_31, PARAM_C_32, PARAM_C_33, PARAM_C_30, PARAM_C_35, PARAM_C_36, PARAM_C_34, PARAM_C_38, PARAM_C_39, PARAM_C_37, PARAM_C_0)
    )
}
