//! Dispatch for `mgga_c_tm` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_c_tpss as k;

/// libxc default for `param_C0_c_0`.
pub const PARAM_C0_C_0: f64 = 0.0;
/// libxc default for `param_C0_c_1`.
pub const PARAM_C0_C_1: f64 = 0.1;
/// libxc default for `param_C0_c_2`.
pub const PARAM_C0_C_2: f64 = 0.32;
/// libxc default for `param_C0_c_3`.
pub const PARAM_C0_C_3: f64 = 0.0;
/// libxc default for `param_beta`.
pub const PARAM_BETA: f64 = 0.06672455060314922;
/// libxc default for `param_d`.
pub const PARAM_D: f64 = 2.8;

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_c_tpss_exc_unpol],
        [k::vxc_unpol::mgga_c_tpss_vxc_unpol],
        [k::fxc_unpol::mgga_c_tpss_fxc_unpol],
        [k::kxc_unpol::mgga_c_tpss_kxc_unpol],
        [k::lxc_unpol::mgga_c_tpss_lxc_unpol],
        [k::exc_pol::mgga_c_tpss_exc_pol],
        [k::vxc_pol::mgga_c_tpss_vxc_pol],
        [k::fxc_pol::mgga_c_tpss_fxc_pol],
        [k::kxc_pol::mgga_c_tpss_kxc_pol],
        [k::lxc_pol::mgga_c_tpss_lxc_pol],
        params = (PARAM_C0_C_0, PARAM_C0_C_1, PARAM_C0_C_2, PARAM_C0_C_3, PARAM_BETA, PARAM_D)
    )
}
