//! Dispatch for `mgga_x_m11_l` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_x_m11_l as k;

/// libxc default for `param_a_1`.
pub const PARAM_A_1: f64 = 1.738124e+01;
/// libxc default for `param_a_2`.
pub const PARAM_A_2: f64 = 1.154007e+00;
/// libxc default for `param_a_3`.
pub const PARAM_A_3: f64 = 6.869556e+01;
/// libxc default for `param_a_4`.
pub const PARAM_A_4: f64 = 1.016864e+02;
/// libxc default for `param_a_5`.
pub const PARAM_A_5: f64 = -5.887467e+00;
/// libxc default for `param_a_6`.
pub const PARAM_A_6: f64 = 4.517409e+01;
/// libxc default for `param_a_7`.
pub const PARAM_A_7: f64 = -2.773149e+00;
/// libxc default for `param_a_8`.
pub const PARAM_A_8: f64 = -2.617211e+01;
/// libxc default for `param_a_9`.
pub const PARAM_A_9: f64 = 0.000000e+00;
/// libxc default for `param_a_10`.
pub const PARAM_A_10: f64 = 0.000000e+00;
/// libxc default for `param_a_11`.
pub const PARAM_A_11: f64 = 0.000000e+00;
/// libxc default for `param_a_0`.
pub const PARAM_A_0: f64 = 8.121131e-01;
/// libxc default for `param_b_1`.
pub const PARAM_B_1: f64 = -1.653877e+01;
/// libxc default for `param_b_2`.
pub const PARAM_B_2: f64 = 6.755753e-01;
/// libxc default for `param_b_3`.
pub const PARAM_B_3: f64 = -7.567572e+01;
/// libxc default for `param_b_4`.
pub const PARAM_B_4: f64 = -1.040272e+02;
/// libxc default for `param_b_5`.
pub const PARAM_B_5: f64 = 1.831853e+01;
/// libxc default for `param_b_6`.
pub const PARAM_B_6: f64 = -5.573352e+01;
/// libxc default for `param_b_7`.
pub const PARAM_B_7: f64 = -3.520210e+00;
/// libxc default for `param_b_8`.
pub const PARAM_B_8: f64 = 3.724276e+01;
/// libxc default for `param_b_9`.
pub const PARAM_B_9: f64 = 0.000000e+00;
/// libxc default for `param_b_10`.
pub const PARAM_B_10: f64 = 0.000000e+00;
/// libxc default for `param_b_11`.
pub const PARAM_B_11: f64 = 0.000000e+00;
/// libxc default for `param_b_0`.
pub const PARAM_B_0: f64 = 1.878869e-01;
/// libxc default for `param_c_1`.
pub const PARAM_C_1: f64 = -1.214016e+02;
/// libxc default for `param_c_2`.
pub const PARAM_C_2: f64 = -1.393573e+02;
/// libxc default for `param_c_3`.
pub const PARAM_C_3: f64 = -2.046649e+00;
/// libxc default for `param_c_4`.
pub const PARAM_C_4: f64 = 2.804098e+01;
/// libxc default for `param_c_5`.
pub const PARAM_C_5: f64 = -1.312258e+01;
/// libxc default for `param_c_6`.
pub const PARAM_C_6: f64 = -6.361819e+00;
/// libxc default for `param_c_7`.
pub const PARAM_C_7: f64 = -8.055758e-01;
/// libxc default for `param_c_8`.
pub const PARAM_C_8: f64 = 3.736551e+00;
/// libxc default for `param_c_9`.
pub const PARAM_C_9: f64 = 0.000000e+00;
/// libxc default for `param_c_10`.
pub const PARAM_C_10: f64 = 0.000000e+00;
/// libxc default for `param_c_11`.
pub const PARAM_C_11: f64 = 0.000000e+00;
/// libxc default for `param_c_0`.
pub const PARAM_C_0: f64 = -4.386615e-01;
/// libxc default for `param_d_1`.
pub const PARAM_D_1: f64 = 1.209465e+02;
/// libxc default for `param_d_2`.
pub const PARAM_D_2: f64 = 1.328252e+02;
/// libxc default for `param_d_3`.
pub const PARAM_D_3: f64 = 1.296355e+01;
/// libxc default for `param_d_4`.
pub const PARAM_D_4: f64 = 5.854866e+00;
/// libxc default for `param_d_5`.
pub const PARAM_D_5: f64 = -3.378162e+00;
/// libxc default for `param_d_6`.
pub const PARAM_D_6: f64 = -4.423393e+01;
/// libxc default for `param_d_7`.
pub const PARAM_D_7: f64 = 6.844475e+00;
/// libxc default for `param_d_8`.
pub const PARAM_D_8: f64 = 1.949541e+01;
/// libxc default for `param_d_9`.
pub const PARAM_D_9: f64 = 0.000000e+00;
/// libxc default for `param_d_10`.
pub const PARAM_D_10: f64 = 0.000000e+00;
/// libxc default for `param_d_11`.
pub const PARAM_D_11: f64 = 0.000000e+00;
/// libxc default for `param_d_0`.
pub const PARAM_D_0: f64 = 1.438662e+00;
/// libxc default for `param_hyb_omega_0`.
pub const PARAM_HYB_OMEGA_0: f64 = 0.25;

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_x_m11_l_exc_unpol],
        [k::vxc_unpol::mgga_x_m11_l_vxc_unpol],
        [k::fxc_unpol::mgga_x_m11_l_fxc_unpol],
        [k::kxc_unpol::mgga_x_m11_l_kxc_unpol],
        [k::lxc_unpol::mgga_x_m11_l_lxc_unpol],
        [k::exc_pol::mgga_x_m11_l_exc_pol],
        [k::vxc_pol::mgga_x_m11_l_vxc_pol],
        [k::fxc_pol::mgga_x_m11_l_fxc_pol],
        [k::kxc_pol::mgga_x_m11_l_kxc_pol],
        [k::lxc_pol::mgga_x_m11_l_lxc_pol],
        params = (PARAM_A_1, PARAM_A_2, PARAM_A_3, PARAM_A_4, PARAM_A_5, PARAM_A_6, PARAM_A_7, PARAM_A_8, PARAM_A_9, PARAM_A_10, PARAM_A_11, PARAM_A_0, PARAM_B_1, PARAM_B_2, PARAM_B_3, PARAM_B_4, PARAM_B_5, PARAM_B_6, PARAM_B_7, PARAM_B_8, PARAM_B_9, PARAM_B_10, PARAM_B_11, PARAM_B_0, PARAM_C_1, PARAM_C_2, PARAM_C_3, PARAM_C_4, PARAM_C_5, PARAM_C_6, PARAM_C_7, PARAM_C_8, PARAM_C_9, PARAM_C_10, PARAM_C_11, PARAM_C_0, PARAM_D_1, PARAM_D_2, PARAM_D_3, PARAM_D_4, PARAM_D_5, PARAM_D_6, PARAM_D_7, PARAM_D_8, PARAM_D_9, PARAM_D_10, PARAM_D_11, PARAM_D_0, PARAM_HYB_OMEGA_0)
    )
}
