//! Dispatch for `mgga_c_m11` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_c_m08 as k;

/// libxc's raw integer id for this functional.
pub const ID: u16 = 76;

/// libxc default for `param_m08_a_1`.
pub const PARAM_M08_A_1: f64 = 0.0000000e+00;
/// libxc default for `param_m08_a_2`.
pub const PARAM_M08_A_2: f64 = -3.8933250e+00;
/// libxc default for `param_m08_a_3`.
pub const PARAM_M08_A_3: f64 = -2.1688455e+00;
/// libxc default for `param_m08_a_4`.
pub const PARAM_M08_A_4: f64 = 9.3497200e+00;
/// libxc default for `param_m08_a_5`.
pub const PARAM_M08_A_5: f64 = -1.9845140e+01;
/// libxc default for `param_m08_a_6`.
pub const PARAM_M08_A_6: f64 = 2.3455253e+00;
/// libxc default for `param_m08_a_7`.
pub const PARAM_M08_A_7: f64 = 7.9246513e+01;
/// libxc default for `param_m08_a_8`.
pub const PARAM_M08_A_8: f64 = 9.6042757e+00;
/// libxc default for `param_m08_a_9`.
pub const PARAM_M08_A_9: f64 = -6.7856719e+01;
/// libxc default for `param_m08_a_10`.
pub const PARAM_M08_A_10: f64 = -9.1841067e+00;
/// libxc default for `param_m08_a_11`.
pub const PARAM_M08_A_11: f64 = 0.0000000e+00;
/// libxc default for `param_m08_a_0`.
pub const PARAM_M08_A_0: f64 = 1.0000000e+00;
/// libxc default for `param_m08_b_1`.
pub const PARAM_M08_B_1: f64 = 4.3730564e-01;
/// libxc default for `param_m08_b_2`.
pub const PARAM_M08_B_2: f64 = -1.6088809e+01;
/// libxc default for `param_m08_b_3`.
pub const PARAM_M08_B_3: f64 = -6.5542437e+01;
/// libxc default for `param_m08_b_4`.
pub const PARAM_M08_B_4: f64 = 3.2057230e+01;
/// libxc default for `param_m08_b_5`.
pub const PARAM_M08_B_5: f64 = 1.8617888e+02;
/// libxc default for `param_m08_b_6`.
pub const PARAM_M08_B_6: f64 = 2.0483468e+01;
/// libxc default for `param_m08_b_7`.
pub const PARAM_M08_B_7: f64 = -7.0853739e+01;
/// libxc default for `param_m08_b_8`.
pub const PARAM_M08_B_8: f64 = 4.4483915e+01;
/// libxc default for `param_m08_b_9`.
pub const PARAM_M08_B_9: f64 = -9.4484747e+01;
/// libxc default for `param_m08_b_10`.
pub const PARAM_M08_B_10: f64 = -1.1459868e+02;
/// libxc default for `param_m08_b_11`.
pub const PARAM_M08_B_11: f64 = 0.0000000e+00;
/// libxc default for `param_m08_b_0`.
pub const PARAM_M08_B_0: f64 = 7.2239798e-01;

/// Number of libxc `ext_params` this dispatch accepts at runtime.
pub const N_EXT_PARAMS: usize = 24;

/// libxc `ext_params` names, in libxc's own order.
pub const EXT_PARAM_NAMES: [&str; 24] = ["_a0", "_a1", "_a2", "_a3", "_a4", "_a5", "_a6", "_a7", "_a8", "_a9", "_a10", "_a11", "_b0", "_b1", "_b2", "_b3", "_b4", "_b5", "_b6", "_b7", "_b8", "_b9", "_b10", "_b11"];

/// Permutation: libxc `ext_params` index -> this kernel's argument slot.
///
/// `usize::MAX` marks an ext_param the kernel does not consume. Built by
/// *name* in `extract_params.py`, not by position -- the two orders differ for
/// most functionals, because libxc's order is its C params-struct order
/// (`util.c::copy_params` writes `ext_params[i]` into struct slot `i`) while
/// the kernel's is the maple2c argument order.
/// | libxc `ext_params` name | kernel argument |
/// |---|---|
/// | `_a0` | `param_m08_a_0` |
/// | `_a1` | `param_m08_a_1` |
/// | `_a2` | `param_m08_a_2` |
/// | `_a3` | `param_m08_a_3` |
/// | `_a4` | `param_m08_a_4` |
/// | `_a5` | `param_m08_a_5` |
/// | `_a6` | `param_m08_a_6` |
/// | `_a7` | `param_m08_a_7` |
/// | `_a8` | `param_m08_a_8` |
/// | `_a9` | `param_m08_a_9` |
/// | `_a10` | `param_m08_a_10` |
/// | `_a11` | `param_m08_a_11` |
/// | `_b0` | `param_m08_b_0` |
/// | `_b1` | `param_m08_b_1` |
/// | `_b2` | `param_m08_b_2` |
/// | `_b3` | `param_m08_b_3` |
/// | `_b4` | `param_m08_b_4` |
/// | `_b5` | `param_m08_b_5` |
/// | `_b6` | `param_m08_b_6` |
/// | `_b7` | `param_m08_b_7` |
/// | `_b8` | `param_m08_b_8` |
/// | `_b9` | `param_m08_b_9` |
/// | `_b10` | `param_m08_b_10` |
/// | `_b11` | `param_m08_b_11` |
pub const EXT_TO_KERNEL: [usize; 24] = [11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 23, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22];

/// Compiled-in libxc defaults, in kernel argument order.
pub const DEFAULTS: [f64; 24] = [PARAM_M08_A_1, PARAM_M08_A_2, PARAM_M08_A_3, PARAM_M08_A_4, PARAM_M08_A_5, PARAM_M08_A_6, PARAM_M08_A_7, PARAM_M08_A_8, PARAM_M08_A_9, PARAM_M08_A_10, PARAM_M08_A_11, PARAM_M08_A_0, PARAM_M08_B_1, PARAM_M08_B_2, PARAM_M08_B_3, PARAM_M08_B_4, PARAM_M08_B_5, PARAM_M08_B_6, PARAM_M08_B_7, PARAM_M08_B_8, PARAM_M08_B_9, PARAM_M08_B_10, PARAM_M08_B_11, PARAM_M08_B_0];

/// Same as [`dispatch`], with an optional caller-supplied `ext_params` array
/// in libxc's own order.
///
/// `None` is exactly [`dispatch`] -- same constants, same bits. `Some(e)`
/// starts from those defaults and overwrites only the slots `e` actually
/// feeds, so an ext_param the kernel ignores cannot disturb one it uses.
pub fn dispatch_with(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
    ext: Option<&[f64]>,
) -> Result<(), LibxcRsError> {
    let mut p = DEFAULTS;
    if let Some(e) = ext {
        if e.len() != N_EXT_PARAMS {
            return Err(LibxcRsError::ExtParamCountMismatch {
                id: libxc_core::model::FunctionalId(ID),
                expected: N_EXT_PARAMS,
                actual: e.len(),
            });
        }
        for (i, &slot) in EXT_TO_KERNEL.iter().enumerate() {
            if slot != usize::MAX {
                p[slot] = e[i];
            }
        }
    }
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_c_m08_exc_unpol],
        [k::vxc_unpol::mgga_c_m08_vxc_unpol],
        [k::fxc_unpol::mgga_c_m08_fxc_unpol],
        [k::kxc_unpol::mgga_c_m08_kxc_unpol],
        [k::lxc_unpol::mgga_c_m08_lxc_unpol],
        [k::exc_pol::mgga_c_m08_exc_pol],
        [k::vxc_pol::mgga_c_m08_vxc_pol],
        [k::fxc_pol::mgga_c_m08_fxc_pol],
        [k::kxc_pol::mgga_c_m08_kxc_pol],
        [k::lxc_pol::mgga_c_m08_lxc_pol],
        params = (p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9], p[10], p[11], p[12], p[13], p[14], p[15], p[16], p[17], p[18], p[19], p[20], p[21], p[22], p[23])
    )
}

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_c_m08_exc_unpol],
        [k::vxc_unpol::mgga_c_m08_vxc_unpol],
        [k::fxc_unpol::mgga_c_m08_fxc_unpol],
        [k::kxc_unpol::mgga_c_m08_kxc_unpol],
        [k::lxc_unpol::mgga_c_m08_lxc_unpol],
        [k::exc_pol::mgga_c_m08_exc_pol],
        [k::vxc_pol::mgga_c_m08_vxc_pol],
        [k::fxc_pol::mgga_c_m08_fxc_pol],
        [k::kxc_pol::mgga_c_m08_kxc_pol],
        [k::lxc_pol::mgga_c_m08_lxc_pol],
        params = (PARAM_M08_A_1, PARAM_M08_A_2, PARAM_M08_A_3, PARAM_M08_A_4, PARAM_M08_A_5, PARAM_M08_A_6, PARAM_M08_A_7, PARAM_M08_A_8, PARAM_M08_A_9, PARAM_M08_A_10, PARAM_M08_A_11, PARAM_M08_A_0, PARAM_M08_B_1, PARAM_M08_B_2, PARAM_M08_B_3, PARAM_M08_B_4, PARAM_M08_B_5, PARAM_M08_B_6, PARAM_M08_B_7, PARAM_M08_B_8, PARAM_M08_B_9, PARAM_M08_B_10, PARAM_M08_B_11, PARAM_M08_B_0)
    )
}
