//! Dispatch for `mgga_c_b94` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_c_b94 as k;

/// libxc's raw integer id for this functional.
pub const ID: u16 = 397;

/// libxc's `XC_FLAGS_NEEDS_TAU` for this functional.
///
/// Set means `work_mgga_inc.c` clamps `tau` up to `tau_threshold`
/// and then clamps `sigma` down to the Fermi-hole curvature bound
/// `8 rho tau`. Clear means libxc evaluates the functional at
/// `tau = 0` and neither clamp applies.
pub const NEEDS_TAU: bool = true;

/// Whether the kernel has to be handed `tau = 0` to reproduce
/// libxc, rather than the caller's `tau`.
///
/// Only ever true when [`NEEDS_TAU`] is false, and then only when
/// this kernel actually reads `tau` -- see
/// `crate::screen::Screen::zero_tau`.
pub const ZERO_TAU: bool = false;

/// libxc default for `param_cab`.
pub const PARAM_CAB: f64 = 0.63;
/// libxc default for `param_css`.
pub const PARAM_CSS: f64 = 0.88;
/// libxc default for `param_gamma`.
pub const PARAM_GAMMA: f64 = 1.0;

/// The derivative orders libxc implements for this functional (its
/// `XC_FLAGS_HAVE_*`). libxc ships a maple2c function for exactly these, so
/// this kernel tree has fewer than the usual ten modules; any other order is
/// refused, as libxc refuses it.
pub const CLAIMED: &[DerivativeOrder] = &[DerivativeOrder::Exc, DerivativeOrder::Vxc, DerivativeOrder::Fxc, DerivativeOrder::Kxc];

/// `XC_FLAGS_HAVE_EXC`. Clear for a potential-only functional (`XC_NO_EXC`):
/// its kernels take no `zk`, so `zk` is neither demanded nor written.
pub const HAVE_EXC: bool = true;

/// `crate::ten_arm_dispatch_rmgga` for a tree with only the [`CLAIMED`]
/// modules. Same invocation; the slot list is for the reader, and each arm
/// names its kernel directly.
macro_rules! partial_dispatch {
    (
        $input:expr, $output:expr, $order:expr, $spin:expr, $thresholds:expr,
        needs_tau = $needs_tau:expr, zero_tau = $zero_tau:expr,
        $( [ $($slot:tt)* ], )*
        params = ( $( $scalar:expr ),* $(,)? )
    ) => {{
        use crate::sweep_mgga::{min_chunk, par_sweep};
        use libxc_core::dims::Dimensions;

        // Refused before `prepare` takes the caller's buffers.
        if !CLAIMED.contains(&$order) {
            return Err(LibxcRsError::UnsupportedDerivativeOrder {
                id: libxc_core::model::FunctionalId(ID),
                order: $order,
                max: CLAIMED[CLAIMED.len() - 1],
            });
        }
        let d = Dimensions::mgga($spin);
        let dt = $thresholds.density;
        let zt = $thresholds.zeta;
        // libxc screens and clamps every point before the maple2c body sees
        // it (`work_mgga_inc.c`), potential-only functionals included.
        let sc = crate::screen::Screen::new($thresholds, $needs_tau, $zero_tau);
        let chunk = crate::mgga::prepare_for($input, $output, $order, &d, HAVE_EXC)?;

        match ($order, $spin) {
            (DerivativeOrder::Exc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), &sc, &|c: &mut crate::sweep_mgga::MggaChunk<'_, '_>| {
                k::exc_unpol::mgga_c_b94_exc_unpol(
                        c.rho, c.sigma, c.lapl, c.tau,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Vxc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), &sc, &|c: &mut crate::sweep_mgga::MggaChunk<'_, '_>| {
                k::vxc_unpol::mgga_c_b94_vxc_unpol(
                        c.rho, c.sigma, c.lapl, c.tau,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vlapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vtau.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Fxc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), &sc, &|c: &mut crate::sweep_mgga::MggaChunk<'_, '_>| {
                k::fxc_unpol::mgga_c_b94_fxc_unpol(
                        c.rho, c.sigma, c.lapl, c.tau,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vlapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vtau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rholapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhotau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmalapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmatau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2tau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Kxc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), &sc, &|c: &mut crate::sweep_mgga::MggaChunk<'_, '_>| {
                k::kxc_unpol::mgga_c_b94_kxc_unpol(
                        c.rho, c.sigma, c.lapl, c.tau,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vlapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vtau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rholapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhotau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmalapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmatau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2tau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2sigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2lapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigmalapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigmatau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rholapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rholapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhotau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma2lapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigmalapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigmalapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigmatau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3lapl3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3lapl2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3lapltau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3tau3.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Exc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), &sc, &|c: &mut crate::sweep_mgga::MggaChunk<'_, '_>| {
                k::exc_pol::mgga_c_b94_exc_pol(
                        c.rho, c.sigma, c.lapl, c.tau,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Vxc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), &sc, &|c: &mut crate::sweep_mgga::MggaChunk<'_, '_>| {
                k::vxc_pol::mgga_c_b94_vxc_pol(
                        c.rho, c.sigma, c.lapl, c.tau,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vlapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vtau.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Fxc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), &sc, &|c: &mut crate::sweep_mgga::MggaChunk<'_, '_>| {
                k::fxc_pol::mgga_c_b94_fxc_pol(
                        c.rho, c.sigma, c.lapl, c.tau,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vlapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vtau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rholapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhotau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmalapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmatau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2tau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Kxc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), &sc, &|c: &mut crate::sweep_mgga::MggaChunk<'_, '_>| {
                k::kxc_pol::mgga_c_b94_kxc_pol(
                        c.rho, c.sigma, c.lapl, c.tau,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vlapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vtau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rholapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhotau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmalapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmatau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2tau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2sigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2lapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigmalapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigmatau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rholapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rholapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhotau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma2lapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigmalapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigmalapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigmatau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3lapl3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3lapl2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3lapltau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3tau3.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            _ => unreachable!("CLAIMED is exactly the set of arms above"),
        }
        Ok(())
    }};
}


/// Number of libxc `ext_params` this dispatch accepts at runtime.
pub const N_EXT_PARAMS: usize = 3;

/// libxc `ext_params` names, in libxc's own order.
pub const EXT_PARAM_NAMES: [&str; 3] = ["_gamma", "_css", "_cab"];

/// Permutation: libxc `ext_params` index -> this kernel's argument slot.
///
/// `usize::MAX` marks an ext_param the kernel does not consume. Built by
/// *name* in `extract_params.py`, not by position -- the two orders differ for
/// most functionals, because libxc's order is its C params-struct order
/// (`util.c::copy_params` writes `ext_params[i]` into struct slot `i`) while
/// the kernel's is the maple2c argument order.
/// | libxc `ext_params` name | kernel argument |
/// |---|---|
/// | `_gamma` | `param_gamma` |
/// | `_css` | `param_css` |
/// | `_cab` | `param_cab` |
pub const EXT_TO_KERNEL: [usize; 3] = [2, 1, 0];

/// Compiled-in libxc defaults, in kernel argument order.
pub const DEFAULTS: [f64; 3] = [PARAM_CAB, PARAM_CSS, PARAM_GAMMA];

/// Number of kernel arguments.
pub const N_PARAMS: usize = 3;

/// The kernel's parameters for a caller-supplied `ext_params` array in
/// libxc's order: [`DEFAULTS`] with only the slots `ext` feeds overwritten
/// (through [`EXT_TO_KERNEL`]). `None` is exactly [`DEFAULTS`]. This is what
/// [`dispatch_with`] passes to the kernel, and what the fused composite
/// dispatch (`crate::fused`) passes for each auxiliary of a mix it evaluates
/// in one loop.
pub fn kernel_params(ext: Option<&[f64]>) -> Result<[f64; N_PARAMS], LibxcRsError> {
    let mut p = DEFAULTS;
    if let Some(e) = ext {
        if e.len() != N_EXT_PARAMS {
            return Err(LibxcRsError::ExtParamCountMismatch {
                id: libxc_core::model::FunctionalId(ID),
                expected: N_EXT_PARAMS,
                actual: e.len(),
            });
        }
        for (i, &slot) in EXT_TO_KERNEL.iter().enumerate() {
            if slot != usize::MAX {
                p[slot] = e[i];
            }
        }
    }
    Ok(p)
}

/// Same as [`dispatch`], with an optional caller-supplied `ext_params` array
/// in libxc's own order.
///
/// `None` is exactly [`dispatch`] -- same constants, same bits. `Some(e)`
/// starts from those defaults and overwrites only the slots `e` actually
/// feeds, so an ext_param the kernel ignores cannot disturb one it uses.
pub fn dispatch_with(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
    ext: Option<&[f64]>,
) -> Result<(), LibxcRsError> {
    let p = kernel_params(ext)?;
    partial_dispatch!(
        input, output, order, spin, thresholds,
        needs_tau = NEEDS_TAU, zero_tau = ZERO_TAU,
        [k::exc_unpol::mgga_c_b94_exc_unpol],
        [k::vxc_unpol::mgga_c_b94_vxc_unpol],
        [k::fxc_unpol::mgga_c_b94_fxc_unpol],
        [k::kxc_unpol::mgga_c_b94_kxc_unpol],
        [k::exc_pol::mgga_c_b94_exc_pol],
        [k::vxc_pol::mgga_c_b94_vxc_pol],
        [k::fxc_pol::mgga_c_b94_fxc_pol],
        [k::kxc_pol::mgga_c_b94_kxc_pol],
        params = (p[0], p[1], p[2])
    )
}

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    partial_dispatch!(
        input, output, order, spin, thresholds,
        needs_tau = NEEDS_TAU, zero_tau = ZERO_TAU,
        [k::exc_unpol::mgga_c_b94_exc_unpol],
        [k::vxc_unpol::mgga_c_b94_vxc_unpol],
        [k::fxc_unpol::mgga_c_b94_fxc_unpol],
        [k::kxc_unpol::mgga_c_b94_kxc_unpol],
        [k::exc_pol::mgga_c_b94_exc_pol],
        [k::vxc_pol::mgga_c_b94_vxc_pol],
        [k::fxc_pol::mgga_c_b94_fxc_pol],
        [k::kxc_pol::mgga_c_b94_kxc_pol],
        params = (PARAM_CAB, PARAM_CSS, PARAM_GAMMA)
    )
}
