//! Dispatch for `mgga_c_m06_2x` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_c_m06l as k;

/// libxc default for `param_css_1`.
pub const PARAM_CSS_1: f64 = -5.528642e+00;
/// libxc default for `param_gamma_ss`.
pub const PARAM_GAMMA_SS: f64 = 0.06;
/// libxc default for `param_css_2`.
pub const PARAM_CSS_2: f64 = 1.347420e+01;
/// libxc default for `param_css_3`.
pub const PARAM_CSS_3: f64 = -3.213623e+01;
/// libxc default for `param_css_4`.
pub const PARAM_CSS_4: f64 = 2.846742e+01;
/// libxc default for `param_css_0`.
pub const PARAM_CSS_0: f64 = 3.097855e-01;
/// libxc default for `param_Fermi_D_cnst`.
pub const PARAM_FERMI_D_CNST: f64 = 1e-10;
/// libxc default for `param_cab_1`.
pub const PARAM_CAB_1: f64 = 3.357972e+01;
/// libxc default for `param_gamma_ab`.
pub const PARAM_GAMMA_AB: f64 = 0.0031;
/// libxc default for `param_cab_2`.
pub const PARAM_CAB_2: f64 = -7.043548e+01;
/// libxc default for `param_cab_3`.
pub const PARAM_CAB_3: f64 = 4.978271e+01;
/// libxc default for `param_cab_4`.
pub const PARAM_CAB_4: f64 = -1.852891e+01;
/// libxc default for `param_cab_0`.
pub const PARAM_CAB_0: f64 = 8.833596e-01;
/// libxc default for `param_dss_0`.
pub const PARAM_DSS_0: f64 = 6.902145e-01;
/// libxc default for `param_alpha_ss`.
pub const PARAM_ALPHA_SS: f64 = 0.00515088;
/// libxc default for `param_dss_1`.
pub const PARAM_DSS_1: f64 = 9.847204e-02;
/// libxc default for `param_dss_2`.
pub const PARAM_DSS_2: f64 = 2.214797e-01;
/// libxc default for `param_dss_3`.
pub const PARAM_DSS_3: f64 = -1.968264e-03;
/// libxc default for `param_dss_4`.
pub const PARAM_DSS_4: f64 = -6.775479e-03;
/// libxc default for `param_dss_5`.
pub const PARAM_DSS_5: f64 = 0.000000e+00;
/// libxc default for `param_dab_0`.
pub const PARAM_DAB_0: f64 = 1.166404e-01;
/// libxc default for `param_alpha_ab`.
pub const PARAM_ALPHA_AB: f64 = 0.00304966;
/// libxc default for `param_dab_1`.
pub const PARAM_DAB_1: f64 = -9.120847e-02;
/// libxc default for `param_dab_2`.
pub const PARAM_DAB_2: f64 = -6.726189e-02;
/// libxc default for `param_dab_3`.
pub const PARAM_DAB_3: f64 = 6.720580e-05;
/// libxc default for `param_dab_4`.
pub const PARAM_DAB_4: f64 = 8.448011e-04;
/// libxc default for `param_dab_5`.
pub const PARAM_DAB_5: f64 = 0.000000e+00;

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_c_m06l_exc_unpol],
        [k::vxc_unpol::mgga_c_m06l_vxc_unpol],
        [k::fxc_unpol::mgga_c_m06l_fxc_unpol],
        [k::kxc_unpol::mgga_c_m06l_kxc_unpol],
        [k::lxc_unpol::mgga_c_m06l_lxc_unpol],
        [k::exc_pol::mgga_c_m06l_exc_pol],
        [k::vxc_pol::mgga_c_m06l_vxc_pol],
        [k::fxc_pol::mgga_c_m06l_fxc_pol],
        [k::kxc_pol::mgga_c_m06l_kxc_pol],
        [k::lxc_pol::mgga_c_m06l_lxc_pol],
        params = (PARAM_CSS_1, PARAM_GAMMA_SS, PARAM_CSS_2, PARAM_CSS_3, PARAM_CSS_4, PARAM_CSS_0, PARAM_FERMI_D_CNST, PARAM_CAB_1, PARAM_GAMMA_AB, PARAM_CAB_2, PARAM_CAB_3, PARAM_CAB_4, PARAM_CAB_0, PARAM_DSS_0, PARAM_ALPHA_SS, PARAM_DSS_1, PARAM_DSS_2, PARAM_DSS_3, PARAM_DSS_4, PARAM_DSS_5, PARAM_DAB_0, PARAM_ALPHA_AB, PARAM_DAB_1, PARAM_DAB_2, PARAM_DAB_3, PARAM_DAB_4, PARAM_DAB_5)
    )
}
