//! Dispatch for `mgga_c_vsxc` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_c_vsxc as k;

/// libxc default for `param_dss_0`.
pub const PARAM_DSS_0: f64 = 3.270912e-01;
/// libxc default for `param_alpha_ss`.
pub const PARAM_ALPHA_SS: f64 = 0.00515088;
/// libxc default for `param_dss_1`.
pub const PARAM_DSS_1: f64 = -3.228915e-02;
/// libxc default for `param_dss_2`.
pub const PARAM_DSS_2: f64 = -2.942406e-02;
/// libxc default for `param_dss_3`.
pub const PARAM_DSS_3: f64 = 2.134222e-03;
/// libxc default for `param_dss_4`.
pub const PARAM_DSS_4: f64 = -5.451559e-03;
/// libxc default for `param_dss_5`.
pub const PARAM_DSS_5: f64 = 1.577575e-02;
/// libxc default for `param_dab_0`.
pub const PARAM_DAB_0: f64 = 7.035010e-01;
/// libxc default for `param_alpha_ab`.
pub const PARAM_ALPHA_AB: f64 = 0.00304966;
/// libxc default for `param_dab_1`.
pub const PARAM_DAB_1: f64 = 7.694574e-03;
/// libxc default for `param_dab_2`.
pub const PARAM_DAB_2: f64 = 5.152765e-02;
/// libxc default for `param_dab_3`.
pub const PARAM_DAB_3: f64 = 3.394308e-05;
/// libxc default for `param_dab_4`.
pub const PARAM_DAB_4: f64 = -1.269420e-03;
/// libxc default for `param_dab_5`.
pub const PARAM_DAB_5: f64 = 1.296118e-03;

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_c_vsxc_exc_unpol],
        [k::vxc_unpol::mgga_c_vsxc_vxc_unpol],
        [k::fxc_unpol::mgga_c_vsxc_fxc_unpol],
        [k::kxc_unpol::mgga_c_vsxc_kxc_unpol],
        [k::lxc_unpol::mgga_c_vsxc_lxc_unpol],
        [k::exc_pol::mgga_c_vsxc_exc_pol],
        [k::vxc_pol::mgga_c_vsxc_vxc_pol],
        [k::fxc_pol::mgga_c_vsxc_fxc_pol],
        [k::kxc_pol::mgga_c_vsxc_kxc_pol],
        [k::lxc_pol::mgga_c_vsxc_lxc_pol],
        params = (PARAM_DSS_0, PARAM_ALPHA_SS, PARAM_DSS_1, PARAM_DSS_2, PARAM_DSS_3, PARAM_DSS_4, PARAM_DSS_5, PARAM_DAB_0, PARAM_ALPHA_AB, PARAM_DAB_1, PARAM_DAB_2, PARAM_DAB_3, PARAM_DAB_4, PARAM_DAB_5)
    )
}
