//! Dispatch for `mgga_x_mbrxh_bg` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_x_mbrxh_bg as k;

/// libxc's raw integer id for this functional.
pub const ID: u16 = 697;



/// Number of libxc `ext_params` this dispatch accepts at runtime: none,
/// because this functional has no ext_params.
pub const N_EXT_PARAMS: usize = 0;

/// Same as [`dispatch`], with an optional caller-supplied `ext_params` array
/// in libxc's own order.
///
/// This functional does not accept runtime ext_params (this functional has no ext_params), so a non-empty
/// `ext` is rejected rather than guessed at.
pub fn dispatch_with(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
    ext: Option<&[f64]>,
) -> Result<(), LibxcRsError> {
    if let Some(e) = ext
        && !e.is_empty()
    {
        return Err(LibxcRsError::ExtParamCountMismatch {
            id: libxc_core::model::FunctionalId(ID),
            expected: 0,
            actual: e.len(),
        });
    }
    dispatch(input, output, order, spin, thresholds)
}

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_x_mbrxh_bg_exc_unpol],
        [k::vxc_unpol::mgga_x_mbrxh_bg_vxc_unpol],
        [k::fxc_unpol::mgga_x_mbrxh_bg_fxc_unpol],
        [k::kxc_unpol::mgga_x_mbrxh_bg_kxc_unpol],
        [k::lxc_unpol::mgga_x_mbrxh_bg_lxc_unpol],
        [k::exc_pol::mgga_x_mbrxh_bg_exc_pol],
        [k::vxc_pol::mgga_x_mbrxh_bg_vxc_pol],
        [k::fxc_pol::mgga_x_mbrxh_bg_fxc_pol],
        [k::kxc_pol::mgga_x_mbrxh_bg_kxc_pol],
        [k::lxc_pol::mgga_x_mbrxh_bg_lxc_pol],
        params = ()
    )
}
