//! Dispatch for `mgga_xc_b97m_v` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_xc_b97mv as k;

/// libxc default for `param_c_x_1`.
pub const PARAM_C_X_1: f64 = 1.308;
/// libxc default for `param_c_x_2`.
pub const PARAM_C_X_2: f64 = 1.901;
/// libxc default for `param_c_x_3`.
pub const PARAM_C_X_3: f64 = 0.416;
/// libxc default for `param_c_x_4`.
pub const PARAM_C_X_4: f64 = 3.070;
/// libxc default for `param_c_x_0`.
pub const PARAM_C_X_0: f64 = 1.000;
/// libxc default for `param_c_ss_1`.
pub const PARAM_C_SS_1: f64 = -1.855;
/// libxc default for `param_c_ss_2`.
pub const PARAM_C_SS_2: f64 = -5.668;
/// libxc default for `param_c_ss_3`.
pub const PARAM_C_SS_3: f64 = -20.497;
/// libxc default for `param_c_ss_4`.
pub const PARAM_C_SS_4: f64 = -20.364;
/// libxc default for `param_c_ss_0`.
pub const PARAM_C_SS_0: f64 = 1.000;
/// libxc default for `param_c_os_1`.
pub const PARAM_C_OS_1: f64 = 1.573;
/// libxc default for `param_c_os_2`.
pub const PARAM_C_OS_2: f64 = -6.298;
/// libxc default for `param_c_os_3`.
pub const PARAM_C_OS_3: f64 = 2.535;
/// libxc default for `param_c_os_4`.
pub const PARAM_C_OS_4: f64 = -6.427;
/// libxc default for `param_c_os_0`.
pub const PARAM_C_OS_0: f64 = 1.000;

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_xc_b97mv_exc_unpol],
        [k::vxc_unpol::mgga_xc_b97mv_vxc_unpol],
        [k::fxc_unpol::mgga_xc_b97mv_fxc_unpol],
        [k::kxc_unpol::mgga_xc_b97mv_kxc_unpol],
        [k::lxc_unpol::mgga_xc_b97mv_lxc_unpol],
        [k::exc_pol::mgga_xc_b97mv_exc_pol],
        [k::vxc_pol::mgga_xc_b97mv_vxc_pol],
        [k::fxc_pol::mgga_xc_b97mv_fxc_pol],
        [k::kxc_pol::mgga_xc_b97mv_kxc_pol],
        [k::lxc_pol::mgga_xc_b97mv_lxc_pol],
        params = (PARAM_C_X_1, PARAM_C_X_2, PARAM_C_X_3, PARAM_C_X_4, PARAM_C_X_0, PARAM_C_SS_1, PARAM_C_SS_2, PARAM_C_SS_3, PARAM_C_SS_4, PARAM_C_SS_0, PARAM_C_OS_1, PARAM_C_OS_2, PARAM_C_OS_3, PARAM_C_OS_4, PARAM_C_OS_0)
    )
}
