//! Dispatch for `mgga_x_mvs` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_x_mvs as k;

/// libxc default for `param_b`.
pub const PARAM_B: f64 = 0.0233;
/// libxc default for `param_c1`.
pub const PARAM_C1: f64 = 0.7438;
/// libxc default for `param_e1`.
pub const PARAM_E1: f64 = -1.6665;
/// libxc default for `param_k0`.
pub const PARAM_K0: f64 = 0.174;

pub fn dispatch<'a>(
    input: &'a MggaInput<'a>,
    output: &'a mut MggaOutput<'a>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_x_mvs_exc_unpol],
        [k::vxc_unpol::mgga_x_mvs_vxc_unpol],
        [k::fxc_unpol::mgga_x_mvs_fxc_unpol],
        [k::kxc_unpol::mgga_x_mvs_kxc_unpol],
        [k::lxc_unpol::mgga_x_mvs_lxc_unpol],
        [k::exc_pol::mgga_x_mvs_exc_pol],
        [k::vxc_pol::mgga_x_mvs_vxc_pol],
        [k::fxc_pol::mgga_x_mvs_fxc_pol],
        [k::kxc_pol::mgga_x_mvs_kxc_pol],
        [k::lxc_pol::mgga_x_mvs_lxc_pol],
        params = (PARAM_B, PARAM_C1, PARAM_E1, PARAM_K0)
    )
}
