//! Dispatch for `mgga_c_rppscan` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_c_rppscan as k;

/// libxc default for `param_eta`.
pub const PARAM_ETA: f64 = 0.001;

pub fn dispatch<'a>(
    input: &'a MggaInput<'a>,
    output: &'a mut MggaOutput<'a>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_c_rppscan_exc_unpol],
        [k::vxc_unpol::mgga_c_rppscan_vxc_unpol],
        [k::fxc_unpol::mgga_c_rppscan_fxc_unpol],
        [k::kxc_unpol::mgga_c_rppscan_kxc_unpol],
        [k::lxc_unpol::mgga_c_rppscan_lxc_unpol],
        [k::exc_pol::mgga_c_rppscan_exc_pol],
        [k::vxc_pol::mgga_c_rppscan_vxc_pol],
        [k::fxc_pol::mgga_c_rppscan_fxc_pol],
        [k::kxc_pol::mgga_c_rppscan_kxc_pol],
        [k::lxc_pol::mgga_c_rppscan_lxc_pol],
        params = (PARAM_ETA)
    )
}
