//! Dispatch for `mgga_x_mtask` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_x_task as k;

/// libxc's raw integer id for this functional.
pub const ID: u16 = 724;

/// libxc default for `param_task_c`.
pub const PARAM_TASK_C: f64 = 4.9479;
/// libxc default for `param_task_bnu_0`.
pub const PARAM_TASK_BNU_0: f64 = -0.639572;
/// libxc default for `param_task_bnu_1`.
pub const PARAM_TASK_BNU_1: f64 = -2.087488;
/// libxc default for `param_task_bnu_2`.
pub const PARAM_TASK_BNU_2: f64 = -0.625;
/// libxc default for `param_task_bnu_3`.
pub const PARAM_TASK_BNU_3: f64 = -0.162512;
/// libxc default for `param_task_bnu_4`.
pub const PARAM_TASK_BNU_4: f64 = 0.014572;
/// libxc default for `param_task_anu_0`.
pub const PARAM_TASK_ANU_0: f64 = 0.924374;
/// libxc default for `param_task_anu_1`.
pub const PARAM_TASK_ANU_1: f64 = -0.09276847;
/// libxc default for `param_task_anu_2`.
pub const PARAM_TASK_ANU_2: f64 = -0.017143;
/// libxc default for `param_task_h0x`.
pub const PARAM_TASK_H0X: f64 = 1.29;
/// libxc default for `param_task_d`.
pub const PARAM_TASK_D: f64 = 10.0;

/// Number of libxc `ext_params` this dispatch accepts at runtime.
pub const N_EXT_PARAMS: usize = 11;

/// libxc `ext_params` names, in libxc's own order.
pub const EXT_PARAM_NAMES: [&str; 11] = ["_c", "_d", "_h0x", "_anu0", "_anu1", "_anu2", "_bnu0", "_bnu1", "_bnu2", "_bnu3", "_bnu4"];

/// Permutation: libxc `ext_params` index -> this kernel's argument slot.
///
/// `usize::MAX` marks an ext_param the kernel does not consume. Built by
/// *name* in `extract_params.py`, not by position -- the two orders differ for
/// most functionals, because libxc's order is its C params-struct order
/// (`util.c::copy_params` writes `ext_params[i]` into struct slot `i`) while
/// the kernel's is the maple2c argument order.
/// | libxc `ext_params` name | kernel argument |
/// |---|---|
/// | `_c` | `param_task_c` |
/// | `_d` | `param_task_d` |
/// | `_h0x` | `param_task_h0x` |
/// | `_anu0` | `param_task_anu_0` |
/// | `_anu1` | `param_task_anu_1` |
/// | `_anu2` | `param_task_anu_2` |
/// | `_bnu0` | `param_task_bnu_0` |
/// | `_bnu1` | `param_task_bnu_1` |
/// | `_bnu2` | `param_task_bnu_2` |
/// | `_bnu3` | `param_task_bnu_3` |
/// | `_bnu4` | `param_task_bnu_4` |
pub const EXT_TO_KERNEL: [usize; 11] = [0, 10, 9, 6, 7, 8, 1, 2, 3, 4, 5];

/// Compiled-in libxc defaults, in kernel argument order.
pub const DEFAULTS: [f64; 11] = [PARAM_TASK_C, PARAM_TASK_BNU_0, PARAM_TASK_BNU_1, PARAM_TASK_BNU_2, PARAM_TASK_BNU_3, PARAM_TASK_BNU_4, PARAM_TASK_ANU_0, PARAM_TASK_ANU_1, PARAM_TASK_ANU_2, PARAM_TASK_H0X, PARAM_TASK_D];

/// Same as [`dispatch`], with an optional caller-supplied `ext_params` array
/// in libxc's own order.
///
/// `None` is exactly [`dispatch`] -- same constants, same bits. `Some(e)`
/// starts from those defaults and overwrites only the slots `e` actually
/// feeds, so an ext_param the kernel ignores cannot disturb one it uses.
pub fn dispatch_with(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
    ext: Option<&[f64]>,
) -> Result<(), LibxcRsError> {
    let mut p = DEFAULTS;
    if let Some(e) = ext {
        if e.len() != N_EXT_PARAMS {
            return Err(LibxcRsError::ExtParamCountMismatch {
                id: libxc_core::model::FunctionalId(ID),
                expected: N_EXT_PARAMS,
                actual: e.len(),
            });
        }
        for (i, &slot) in EXT_TO_KERNEL.iter().enumerate() {
            if slot != usize::MAX {
                p[slot] = e[i];
            }
        }
    }
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_x_task_exc_unpol],
        [k::vxc_unpol::mgga_x_task_vxc_unpol],
        [k::fxc_unpol::mgga_x_task_fxc_unpol],
        [k::kxc_unpol::mgga_x_task_kxc_unpol],
        [k::lxc_unpol::mgga_x_task_lxc_unpol],
        [k::exc_pol::mgga_x_task_exc_pol],
        [k::vxc_pol::mgga_x_task_vxc_pol],
        [k::fxc_pol::mgga_x_task_fxc_pol],
        [k::kxc_pol::mgga_x_task_kxc_pol],
        [k::lxc_pol::mgga_x_task_lxc_pol],
        params = (p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9], p[10])
    )
}

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_x_task_exc_unpol],
        [k::vxc_unpol::mgga_x_task_vxc_unpol],
        [k::fxc_unpol::mgga_x_task_fxc_unpol],
        [k::kxc_unpol::mgga_x_task_kxc_unpol],
        [k::lxc_unpol::mgga_x_task_lxc_unpol],
        [k::exc_pol::mgga_x_task_exc_pol],
        [k::vxc_pol::mgga_x_task_vxc_pol],
        [k::fxc_pol::mgga_x_task_fxc_pol],
        [k::kxc_pol::mgga_x_task_kxc_pol],
        [k::lxc_pol::mgga_x_task_lxc_pol],
        params = (PARAM_TASK_C, PARAM_TASK_BNU_0, PARAM_TASK_BNU_1, PARAM_TASK_BNU_2, PARAM_TASK_BNU_3, PARAM_TASK_BNU_4, PARAM_TASK_ANU_0, PARAM_TASK_ANU_1, PARAM_TASK_ANU_2, PARAM_TASK_H0X, PARAM_TASK_D)
    )
}
