//! Dispatch for `mgga_k_rda` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_k_rda as k;

/// libxc default for `param_A0`.
pub const PARAM_A0: f64 = 0.50616;
/// libxc default for `param_A1`.
pub const PARAM_A1: f64 = 3.04121;
/// libxc default for `param_A2`.
pub const PARAM_A2: f64 = -0.34567;
/// libxc default for `param_A3`.
pub const PARAM_A3: f64 = -1.89738;
/// libxc default for `param_a`.
pub const PARAM_A: f64 = 46.47662;
/// libxc default for `param_b`.
pub const PARAM_B: f64 = 18.80658;
/// libxc default for `param_beta1`.
pub const PARAM_BETA1: f64 = 1.29691;
/// libxc default for `param_beta2`.
pub const PARAM_BETA2: f64 = 0.56184;
/// libxc default for `param_beta3`.
pub const PARAM_BETA3: f64 = 0.21944;
/// libxc default for `param_c`.
pub const PARAM_C: f64 = -0.90346;

pub fn dispatch<'a>(
    input: &'a MggaInput<'a>,
    output: &'a mut MggaOutput<'a>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_k_rda_exc_unpol],
        [k::vxc_unpol::mgga_k_rda_vxc_unpol],
        [k::fxc_unpol::mgga_k_rda_fxc_unpol],
        [k::kxc_unpol::mgga_k_rda_kxc_unpol],
        [k::lxc_unpol::mgga_k_rda_lxc_unpol],
        [k::exc_pol::mgga_k_rda_exc_pol],
        [k::vxc_pol::mgga_k_rda_vxc_pol],
        [k::fxc_pol::mgga_k_rda_fxc_pol],
        [k::kxc_pol::mgga_k_rda_kxc_pol],
        [k::lxc_pol::mgga_k_rda_lxc_pol],
        params = (PARAM_A0, PARAM_A1, PARAM_A2, PARAM_A3, PARAM_A, PARAM_B, PARAM_BETA1, PARAM_BETA2, PARAM_BETA3, PARAM_C)
    )
}
