//! Dispatch for `mgga_x_tpss` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_x_tpss as k;

/// libxc default for `param_BLOC_a`.
pub const PARAM_BLOC_A: f64 = 2.0;
/// libxc default for `param_BLOC_b`.
pub const PARAM_BLOC_B: f64 = 0.0;
/// libxc default for `param_b`.
pub const PARAM_B: f64 = 0.40;
/// libxc default for `param_c`.
pub const PARAM_C: f64 = 1.59096;
/// libxc default for `param_e`.
pub const PARAM_E: f64 = 1.537;
/// libxc default for `param_kappa`.
pub const PARAM_KAPPA: f64 = 0.8040;
/// libxc default for `param_mu`.
pub const PARAM_MU: f64 = 0.21951;

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_x_tpss_exc_unpol],
        [k::vxc_unpol::mgga_x_tpss_vxc_unpol],
        [k::fxc_unpol::mgga_x_tpss_fxc_unpol],
        [k::kxc_unpol::mgga_x_tpss_kxc_unpol],
        [k::lxc_unpol::mgga_x_tpss_lxc_unpol],
        [k::exc_pol::mgga_x_tpss_exc_pol],
        [k::vxc_pol::mgga_x_tpss_vxc_pol],
        [k::fxc_pol::mgga_x_tpss_fxc_pol],
        [k::kxc_pol::mgga_x_tpss_kxc_pol],
        [k::lxc_pol::mgga_x_tpss_lxc_pol],
        params = (PARAM_BLOC_A, PARAM_BLOC_B, PARAM_B, PARAM_C, PARAM_E, PARAM_KAPPA, PARAM_MU)
    )
}
