//! Dispatch for `mgga_c_bc95` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_c_bc95 as k;

/// libxc's raw integer id for this functional.
pub const ID: u16 = 240;

/// libxc default for `param_copp`.
pub const PARAM_COPP: f64 = 0.0031;
/// libxc default for `param_css`.
pub const PARAM_CSS: f64 = 0.038;

/// Number of libxc `ext_params` this dispatch accepts at runtime.
pub const N_EXT_PARAMS: usize = 2;

/// libxc `ext_params` names, in libxc's own order.
pub const EXT_PARAM_NAMES: [&str; 2] = ["_css", "_copp"];

/// Permutation: libxc `ext_params` index -> this kernel's argument slot.
///
/// `usize::MAX` marks an ext_param the kernel does not consume. Built by
/// *name* in `extract_params.py`, not by position -- the two orders differ for
/// most functionals, because libxc's order is its C params-struct order
/// (`util.c::copy_params` writes `ext_params[i]` into struct slot `i`) while
/// the kernel's is the maple2c argument order.
/// | libxc `ext_params` name | kernel argument |
/// |---|---|
/// | `_css` | `param_css` |
/// | `_copp` | `param_copp` |
pub const EXT_TO_KERNEL: [usize; 2] = [1, 0];

/// Compiled-in libxc defaults, in kernel argument order.
pub const DEFAULTS: [f64; 2] = [PARAM_COPP, PARAM_CSS];

/// Same as [`dispatch`], with an optional caller-supplied `ext_params` array
/// in libxc's own order.
///
/// `None` is exactly [`dispatch`] -- same constants, same bits. `Some(e)`
/// starts from those defaults and overwrites only the slots `e` actually
/// feeds, so an ext_param the kernel ignores cannot disturb one it uses.
pub fn dispatch_with(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
    ext: Option<&[f64]>,
) -> Result<(), LibxcRsError> {
    let mut p = DEFAULTS;
    if let Some(e) = ext {
        if e.len() != N_EXT_PARAMS {
            return Err(LibxcRsError::ExtParamCountMismatch {
                id: libxc_core::model::FunctionalId(ID),
                expected: N_EXT_PARAMS,
                actual: e.len(),
            });
        }
        for (i, &slot) in EXT_TO_KERNEL.iter().enumerate() {
            if slot != usize::MAX {
                p[slot] = e[i];
            }
        }
    }
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_c_bc95_exc_unpol],
        [k::vxc_unpol::mgga_c_bc95_vxc_unpol],
        [k::fxc_unpol::mgga_c_bc95_fxc_unpol],
        [k::kxc_unpol::mgga_c_bc95_kxc_unpol],
        [k::lxc_unpol::mgga_c_bc95_lxc_unpol],
        [k::exc_pol::mgga_c_bc95_exc_pol],
        [k::vxc_pol::mgga_c_bc95_vxc_pol],
        [k::fxc_pol::mgga_c_bc95_fxc_pol],
        [k::kxc_pol::mgga_c_bc95_kxc_pol],
        [k::lxc_pol::mgga_c_bc95_lxc_pol],
        params = (p[0], p[1])
    )
}

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_c_bc95_exc_unpol],
        [k::vxc_unpol::mgga_c_bc95_vxc_unpol],
        [k::fxc_unpol::mgga_c_bc95_fxc_unpol],
        [k::kxc_unpol::mgga_c_bc95_kxc_unpol],
        [k::lxc_unpol::mgga_c_bc95_lxc_unpol],
        [k::exc_pol::mgga_c_bc95_exc_pol],
        [k::vxc_pol::mgga_c_bc95_vxc_pol],
        [k::fxc_pol::mgga_c_bc95_fxc_pol],
        [k::kxc_pol::mgga_c_bc95_kxc_pol],
        [k::lxc_pol::mgga_c_bc95_lxc_pol],
        params = (PARAM_COPP, PARAM_CSS)
    )
}
