//! Dispatch for `mgga_k_pc07` over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//! Parameter defaults are libxc's `ext_params` values, extracted by
//! tools/translate_rayon/extract_params.py.

use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::MggaOutput;

use libxc_rkernel_mgga_k_pc07 as k;

/// libxc default for `param_a`.
pub const PARAM_A: f64 = 0.5389;
/// libxc default for `param_b`.
pub const PARAM_B: f64 = 3.0;

pub fn dispatch(
    input: &MggaInput<'_>,
    output: &mut MggaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
    thresholds: &Thresholds,
) -> Result<(), LibxcRsError> {
    crate::ten_arm_dispatch_rmgga!(
        input, output, order, spin, thresholds,
        [k::exc_unpol::mgga_k_pc07_exc_unpol],
        [k::vxc_unpol::mgga_k_pc07_vxc_unpol],
        [k::fxc_unpol::mgga_k_pc07_fxc_unpol],
        [k::kxc_unpol::mgga_k_pc07_kxc_unpol],
        [k::lxc_unpol::mgga_k_pc07_lxc_unpol],
        [k::exc_pol::mgga_k_pc07_exc_pol],
        [k::vxc_pol::mgga_k_pc07_vxc_pol],
        [k::fxc_pol::mgga_k_pc07_fxc_pol],
        [k::kxc_pol::mgga_k_pc07_kxc_pol],
        [k::lxc_pol::mgga_k_pc07_lxc_pol],
        params = (PARAM_A, PARAM_B)
    )
}
