//! Fused composite dispatch: a libxc mix evaluated as one kernel.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit. The
//! kernels come from tools/translate_rayon/fuse.py, which documents why the
//! result is bit-identical to the leaf-by-leaf mix.
//!
//! Every entry point here returns `None` -- "not applicable, use the mix" --
//! rather than guessing: when the parent is not one of the composites a fused
//! kernel was emitted for, when its auxiliaries are not the ones the kernel
//! was built from, when the (order, spin) pair has no fused arm, when the legs
//! do not share thresholds, when a parameter the kernel was specialised on has
//! been changed at runtime, or when a buffer the order needs is missing.
//! `Some(Err)` is reserved for the errors the mix would also raise.

use libxc_core::error::LibxcRsError;
use libxc_core::input::GgaInput;
use libxc_core::model::{DerivativeOrder, Spin, Thresholds};
use libxc_core::output::GgaOutput;

/// One auxiliary of a composite, as the fused dispatch needs to see it.
#[derive(Clone, Copy, Debug)]
pub struct FusedLeg<'a> {
    /// libxc id of the auxiliary functional.
    pub id: u16,
    /// Its runtime `ext_params` in libxc order; `None` means the defaults.
    pub ext: Option<&'a [f64]>,
    /// Its thresholds.
    pub thresholds: Thresholds,
}

/// Evaluate `parent` -- a composite of `legs` with `weights` -- through its
/// fused kernel if one applies. `None` means no fused kernel applies and the
/// caller should run the mix.
pub fn try_fused_gga(
    parent: u16,
    legs: &[FusedLeg<'_>],
    weights: &[f64],
    input: &GgaInput<'_>,
    output: &mut GgaOutput<'_>,
    order: DerivativeOrder,
    spin: Spin,
) -> Option<Result<(), LibxcRsError>> {
    #[allow(unused_variables)]
    let (legs, weights, input, output, order, spin) = (legs, weights, input, output, order, spin);
    match parent {
        #[cfg(feature = "fused_hse")]
        427 | 428 | 479 | 480 => fused_hse::dispatch(legs, weights, input, output, order, spin),
        #[cfg(feature = "fused_pbeh")]
        406 | 290 | 456 => fused_pbeh::dispatch(legs, weights, input, output, order, spin),
        _ => None,
    }
}

/// Is there a fused kernel for `parent` at this (order, spin)? Reporting
/// only: the dispatch above still re-checks legs, parameters and buffers.
pub fn has_fused_arm(parent: u16, order: DerivativeOrder, spin: Spin) -> bool {
    #[allow(unused_variables)]
    let (order, spin) = (order, spin);
    match parent {
        #[cfg(feature = "fused_hse")]
        427 | 428 | 479 | 480 => fused_hse::ARMS.contains(&(order, spin)),
        #[cfg(feature = "fused_pbeh")]
        406 | 290 | 456 => fused_pbeh::ARMS.contains(&(order, spin)),
        _ => false,
    }
}

/// `w0*gga_x_wpbeh(param_hyb_omega_0=0.0) + w1*gga_x_wpbeh + w2*gga_c_pbe` in one loop, for hyb_gga_xc_hse03, hyb_gga_xc_hse06, hyb_gga_xc_hse12, hyb_gga_xc_hse12s.
#[cfg(feature = "fused_hse")]
pub mod fused_hse {
    use super::*;
    use libxc_rkernel_fused_hse as k;

    /// libxc ids of the auxiliaries, in `xc_mix_init` order.
    pub const LEG_IDS: [u16; 3] = [524, 524, 130];

    /// Parent functionals routed here.
    pub const PARENT_IDS: [u16; 4] = [427, 428, 479, 480];

    /// The (order, spin) pairs this fused kernel was emitted for; every other
    /// pair falls back to the mix.
    pub const ARMS: [(DerivativeOrder, Spin); 6] = [(DerivativeOrder::Exc, Spin::Unpolarized), (DerivativeOrder::Vxc, Spin::Unpolarized), (DerivativeOrder::Fxc, Spin::Unpolarized), (DerivativeOrder::Exc, Spin::Polarized), (DerivativeOrder::Vxc, Spin::Polarized), (DerivativeOrder::Fxc, Spin::Polarized)];

    pub fn dispatch(
        legs: &[FusedLeg<'_>],
        weights: &[f64],
        input: &GgaInput<'_>,
        output: &mut GgaOutput<'_>,
        order: DerivativeOrder,
        spin: Spin,
    ) -> Option<Result<(), LibxcRsError>> {
        use crate::sweep_gga::{GgaChunk, min_chunk, par_sweep};
        use libxc_core::dims::Dimensions;

        if legs.len() != 3 || weights.len() != 3 {
            return None;
        }
        if legs.iter().zip(LEG_IDS.iter()).any(|(l, &id)| l.id != id) {
            return None;
        }
        if !ARMS.contains(&(order, spin)) {
            return None;
        }
        // One screen serves every leg only if every leg screens alike.
        let t = legs[0].thresholds;
        if legs.iter().any(|l| {
            l.thresholds.density.to_bits() != t.density.to_bits()
                || l.thresholds.zeta.to_bits() != t.zeta.to_bits()
        }) {
            return None;
        }
        // `prepare` requires every buffer of the order and *takes* them, so
        // the check has to come first; the mix tolerates a missing one.
        if !crate::gga::has_required_fields(output, order) {
            return None;
        }
        let p0 = match crate::funcs::gga_x_wpbeh::kernel_params(legs[0].ext) {
            Ok(p) => p,
            Err(e) => return Some(Err(e)),
        };
        let p1 = match crate::funcs::gga_x_wpbeh::kernel_params(legs[1].ext) {
            Ok(p) => p,
            Err(e) => return Some(Err(e)),
        };
        let p2 = match crate::funcs::gga_c_pbe::kernel_params(legs[2].ext) {
            Ok(p) => p,
            Err(e) => return Some(Err(e)),
        };
        // leg 0 (`gga_x_wpbeh`) is specialised on `param_hyb_omega_0 = 0.0`.
        if p0[0].to_bits() != (0.0f64).to_bits() {
            return None;
        }
        let d = Dimensions::gga(spin);
        let dt = t.density;
        let zt = t.zeta;
        let chunk = match crate::gga::prepare(input, output, order, &d) {
            Ok(c) => c,
            Err(e) => return Some(Err(e)),
        };
        match (order, spin) {
            (DerivativeOrder::Exc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut GgaChunk<'_, '_>| {
                k::exc_unpol::fused_hse_exc_unpol(c.rho, c.sigma, c.zk.as_deref_mut().expect("prepare guarantees this buffer"), weights[0], weights[1], weights[2], p1[0], p2[0], p2[1], p2[2], dt, zt)
            }),
            (DerivativeOrder::Vxc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut GgaChunk<'_, '_>| {
                k::vxc_unpol::fused_hse_vxc_unpol(c.rho, c.sigma, c.zk.as_deref_mut().expect("prepare guarantees this buffer"), c.vrho.as_deref_mut().expect("prepare guarantees this buffer"), c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"), weights[0], weights[1], weights[2], p1[0], p2[0], p2[1], p2[2], dt, zt)
            }),
            (DerivativeOrder::Fxc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut GgaChunk<'_, '_>| {
                k::fxc_unpol::fused_hse_fxc_unpol(c.rho, c.sigma, c.zk.as_deref_mut().expect("prepare guarantees this buffer"), c.vrho.as_deref_mut().expect("prepare guarantees this buffer"), c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"), c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"), c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"), c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"), weights[0], weights[1], weights[2], p1[0], p2[0], p2[1], p2[2], dt, zt)
            }),
            (DerivativeOrder::Exc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut GgaChunk<'_, '_>| {
                k::exc_pol::fused_hse_exc_pol(c.rho, c.sigma, c.zk.as_deref_mut().expect("prepare guarantees this buffer"), weights[0], weights[1], weights[2], p1[0], p2[0], p2[1], p2[2], dt, zt)
            }),
            (DerivativeOrder::Vxc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut GgaChunk<'_, '_>| {
                k::vxc_pol::fused_hse_vxc_pol(c.rho, c.sigma, c.zk.as_deref_mut().expect("prepare guarantees this buffer"), c.vrho.as_deref_mut().expect("prepare guarantees this buffer"), c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"), weights[0], weights[1], weights[2], p1[0], p2[0], p2[1], p2[2], dt, zt)
            }),
            (DerivativeOrder::Fxc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut GgaChunk<'_, '_>| {
                k::fxc_pol::fused_hse_fxc_pol(c.rho, c.sigma, c.zk.as_deref_mut().expect("prepare guarantees this buffer"), c.vrho.as_deref_mut().expect("prepare guarantees this buffer"), c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"), c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"), c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"), c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"), weights[0], weights[1], weights[2], p1[0], p2[0], p2[1], p2[2], dt, zt)
            }),
            _ => unreachable!("ARMS was checked above"),
        }
        Some(Ok(()))
    }
}

/// `w0*gga_x_pbe + w1*gga_c_pbe` in one loop, for hyb_gga_xc_pbeh, hyb_gga_xc_pbe50, hyb_gga_xc_pbe0_13.
#[cfg(feature = "fused_pbeh")]
pub mod fused_pbeh {
    use super::*;
    use libxc_rkernel_fused_pbeh as k;

    /// libxc ids of the auxiliaries, in `xc_mix_init` order.
    pub const LEG_IDS: [u16; 2] = [101, 130];

    /// Parent functionals routed here.
    pub const PARENT_IDS: [u16; 3] = [406, 290, 456];

    /// The (order, spin) pairs this fused kernel was emitted for; every other
    /// pair falls back to the mix.
    pub const ARMS: [(DerivativeOrder, Spin); 6] = [(DerivativeOrder::Exc, Spin::Unpolarized), (DerivativeOrder::Vxc, Spin::Unpolarized), (DerivativeOrder::Fxc, Spin::Unpolarized), (DerivativeOrder::Exc, Spin::Polarized), (DerivativeOrder::Vxc, Spin::Polarized), (DerivativeOrder::Fxc, Spin::Polarized)];

    pub fn dispatch(
        legs: &[FusedLeg<'_>],
        weights: &[f64],
        input: &GgaInput<'_>,
        output: &mut GgaOutput<'_>,
        order: DerivativeOrder,
        spin: Spin,
    ) -> Option<Result<(), LibxcRsError>> {
        use crate::sweep_gga::{GgaChunk, min_chunk, par_sweep};
        use libxc_core::dims::Dimensions;

        if legs.len() != 2 || weights.len() != 2 {
            return None;
        }
        if legs.iter().zip(LEG_IDS.iter()).any(|(l, &id)| l.id != id) {
            return None;
        }
        if !ARMS.contains(&(order, spin)) {
            return None;
        }
        // One screen serves every leg only if every leg screens alike.
        let t = legs[0].thresholds;
        if legs.iter().any(|l| {
            l.thresholds.density.to_bits() != t.density.to_bits()
                || l.thresholds.zeta.to_bits() != t.zeta.to_bits()
        }) {
            return None;
        }
        // `prepare` requires every buffer of the order and *takes* them, so
        // the check has to come first; the mix tolerates a missing one.
        if !crate::gga::has_required_fields(output, order) {
            return None;
        }
        let p0 = match crate::funcs::gga_x_pbe::kernel_params(legs[0].ext) {
            Ok(p) => p,
            Err(e) => return Some(Err(e)),
        };
        let p1 = match crate::funcs::gga_c_pbe::kernel_params(legs[1].ext) {
            Ok(p) => p,
            Err(e) => return Some(Err(e)),
        };

        let d = Dimensions::gga(spin);
        let dt = t.density;
        let zt = t.zeta;
        let chunk = match crate::gga::prepare(input, output, order, &d) {
            Ok(c) => c,
            Err(e) => return Some(Err(e)),
        };
        match (order, spin) {
            (DerivativeOrder::Exc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut GgaChunk<'_, '_>| {
                k::exc_unpol::fused_pbeh_exc_unpol(c.rho, c.sigma, c.zk.as_deref_mut().expect("prepare guarantees this buffer"), weights[0], weights[1], p0[0], p0[1], p1[0], p1[1], p1[2], dt, zt)
            }),
            (DerivativeOrder::Vxc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut GgaChunk<'_, '_>| {
                k::vxc_unpol::fused_pbeh_vxc_unpol(c.rho, c.sigma, c.zk.as_deref_mut().expect("prepare guarantees this buffer"), c.vrho.as_deref_mut().expect("prepare guarantees this buffer"), c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"), weights[0], weights[1], p0[0], p0[1], p1[0], p1[1], p1[2], dt, zt)
            }),
            (DerivativeOrder::Fxc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut GgaChunk<'_, '_>| {
                k::fxc_unpol::fused_pbeh_fxc_unpol(c.rho, c.sigma, c.zk.as_deref_mut().expect("prepare guarantees this buffer"), c.vrho.as_deref_mut().expect("prepare guarantees this buffer"), c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"), c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"), c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"), c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"), weights[0], weights[1], p0[0], p0[1], p1[0], p1[1], p1[2], dt, zt)
            }),
            (DerivativeOrder::Exc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut GgaChunk<'_, '_>| {
                k::exc_pol::fused_pbeh_exc_pol(c.rho, c.sigma, c.zk.as_deref_mut().expect("prepare guarantees this buffer"), weights[0], weights[1], p0[0], p0[1], p1[0], p1[1], p1[2], dt, zt)
            }),
            (DerivativeOrder::Vxc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut GgaChunk<'_, '_>| {
                k::vxc_pol::fused_pbeh_vxc_pol(c.rho, c.sigma, c.zk.as_deref_mut().expect("prepare guarantees this buffer"), c.vrho.as_deref_mut().expect("prepare guarantees this buffer"), c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"), weights[0], weights[1], p0[0], p0[1], p1[0], p1[1], p1[2], dt, zt)
            }),
            (DerivativeOrder::Fxc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut GgaChunk<'_, '_>| {
                k::fxc_pol::fused_pbeh_fxc_pol(c.rho, c.sigma, c.zk.as_deref_mut().expect("prepare guarantees this buffer"), c.vrho.as_deref_mut().expect("prepare guarantees this buffer"), c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"), c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"), c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"), c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"), weights[0], weights[1], p0[0], p0[1], p1[0], p1[1], p1[2], dt, zt)
            }),
            _ => unreachable!("ARMS was checked above"),
        }
        Some(Ok(()))
    }
}
