//! LDA dispatch over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.

use libxc_core::dims::Dimensions;
use libxc_core::error::LibxcRsError;
use libxc_core::input::LdaInput;
use libxc_core::model::DerivativeOrder;
use libxc_core::output::LdaOutput;

use crate::sweep_lda::LdaChunk;

/// Output fields a LDA evaluation of `order` must be given.
fn required_fields(order: DerivativeOrder) -> &'static [&'static str] {
    match order {
        DerivativeOrder::Exc => &["zk"],
        DerivativeOrder::Vxc => &["zk", "vrho"],
        DerivativeOrder::Fxc => &["zk", "vrho", "v2rho2"],
        DerivativeOrder::Kxc => &["zk", "vrho", "v2rho2", "v3rho3"],
        DerivativeOrder::Lxc => &["zk", "vrho", "v2rho2", "v3rho3", "v4rho4"],
    }
}

/// Validate the caller's buffers and build the chunk view.
///
/// Kernels accumulate with `+=`, so every destination must start at zero --
/// but that zeroing happens per chunk inside `par_sweep`, not here. See the
/// comment on `zero_outputs` for why. Buffers the caller supplied for an order
/// higher than the one requested are still cleared here: they are dropped from
/// the chunk, so the sweep never sees them, and leaving stale values in a
/// buffer the caller handed us would be worse than the cost of clearing it.
pub fn prepare<'inp, 'out>(
    input: &LdaInput<'inp>,
    output: &mut LdaOutput<'out>,
    order: DerivativeOrder,
    d: &Dimensions,
) -> Result<LdaChunk<'inp, 'out>, LibxcRsError> {
    let np = input.np();
    let need = required_fields(order);

    macro_rules! take {
        ($f:ident, $name:literal, $stride:expr) => {{
            let wanted = need.contains(&$name);
            match output.$f.take() {
                Some(b) if wanted => {
                    let expected = np * $stride as usize;
                    if b.len() != expected {
                        return Err(LibxcRsError::OutputBufferSizeMismatch {
                            field: $name, expected, actual: b.len(),
                        });
                    }
                    Some(b)
                }
                Some(b) => { b.fill(0.0); None }
                None if wanted => {
                    return Err(LibxcRsError::OutputBufferSizeMismatch {
                        field: $name, expected: np * $stride as usize, actual: 0,
                    })
                }
                None => None,
            }
        }};
    }

    Ok(LdaChunk {
        np,
        rho: input.rho(),
        zk: take!(zk, "zk", d.zk),
        vrho: take!(vrho, "vrho", d.vrho),
        v2rho2: take!(v2rho2, "v2rho2", d.v2rho2),
        v3rho3: take!(v3rho3, "v3rho3", d.v3rho3),
        v4rho4: take!(v4rho4, "v4rho4", d.v4rho4),
    })
}

/// Dispatch one LDA functional across the grid in parallel.
///
/// Arms are written out rather than folded into a helper macro: `macro_rules!`
/// cannot nest a repetition inside another macro's repetition.
#[macro_export]
macro_rules! ten_arm_dispatch_rlda {
    (
        $input:expr, $output:expr, $order:expr, $spin:expr, $thresholds:expr,
        [$($exc_u:tt)::+],
        [$($vxc_u:tt)::+],
        [$($fxc_u:tt)::+],
        [$($kxc_u:tt)::+],
        [$($lxc_u:tt)::+],
        [$($exc_p:tt)::+],
        [$($vxc_p:tt)::+],
        [$($fxc_p:tt)::+],
        [$($kxc_p:tt)::+],
        [$($lxc_p:tt)::+],
        params = ( $( $scalar:expr ),* $(,)? )
    ) => {{
        use $crate::sweep_lda::{min_chunk, par_sweep};
        use libxc_core::dims::Dimensions;
        use libxc_core::model::{DerivativeOrder, Spin};

        let d = Dimensions::lda($spin);
        let dt = $thresholds.density;
        let zt = $thresholds.zeta;
        let chunk = $crate::lda::prepare($input, $output, $order, &d)?;

        match ($order, $spin) {
            (DerivativeOrder::Exc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_lda::LdaChunk<'_, '_>| {
                $($exc_u)::+(
                        c.rho,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Vxc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_lda::LdaChunk<'_, '_>| {
                $($vxc_u)::+(
                        c.rho,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Fxc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_lda::LdaChunk<'_, '_>| {
                $($fxc_u)::+(
                        c.rho,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Kxc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_lda::LdaChunk<'_, '_>| {
                $($kxc_u)::+(
                        c.rho,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho3.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Lxc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_lda::LdaChunk<'_, '_>| {
                $($lxc_u)::+(
                        c.rho,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho4.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Exc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_lda::LdaChunk<'_, '_>| {
                $($exc_p)::+(
                        c.rho,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Vxc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_lda::LdaChunk<'_, '_>| {
                $($vxc_p)::+(
                        c.rho,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Fxc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_lda::LdaChunk<'_, '_>| {
                $($fxc_p)::+(
                        c.rho,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Kxc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_lda::LdaChunk<'_, '_>| {
                $($kxc_p)::+(
                        c.rho,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho3.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Lxc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_lda::LdaChunk<'_, '_>| {
                $($lxc_p)::+(
                        c.rho,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho4.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
        }
        Ok(())
    }};
}
