//! MGGA dispatch over the rayon kernels.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.

use libxc_core::dims::Dimensions;
use libxc_core::error::LibxcRsError;
use libxc_core::input::MggaInput;
use libxc_core::model::DerivativeOrder;
use libxc_core::output::MggaOutput;

use crate::sweep_mgga::MggaChunk;

/// Output fields a MGGA evaluation of `order` must be given.
fn required_fields(order: DerivativeOrder) -> &'static [&'static str] {
    match order {
        DerivativeOrder::Exc => &["zk"],
        DerivativeOrder::Vxc => &["zk", "vrho", "vsigma", "vlapl", "vtau"],
        DerivativeOrder::Fxc => &["zk", "vrho", "vsigma", "vlapl", "vtau", "v2rho2", "v2rhosigma", "v2rholapl", "v2rhotau", "v2sigma2", "v2sigmalapl", "v2sigmatau", "v2lapl2", "v2lapltau", "v2tau2"],
        DerivativeOrder::Kxc => &["zk", "vrho", "vsigma", "vlapl", "vtau", "v2rho2", "v2rhosigma", "v2rholapl", "v2rhotau", "v2sigma2", "v2sigmalapl", "v2sigmatau", "v2lapl2", "v2lapltau", "v2tau2", "v3rho3", "v3rho2sigma", "v3rho2lapl", "v3rho2tau", "v3rhosigma2", "v3rhosigmalapl", "v3rhosigmatau", "v3rholapl2", "v3rholapltau", "v3rhotau2", "v3sigma3", "v3sigma2lapl", "v3sigma2tau", "v3sigmalapl2", "v3sigmalapltau", "v3sigmatau2", "v3lapl3", "v3lapl2tau", "v3lapltau2", "v3tau3"],
        DerivativeOrder::Lxc => &["zk", "vrho", "vsigma", "vlapl", "vtau", "v2rho2", "v2rhosigma", "v2rholapl", "v2rhotau", "v2sigma2", "v2sigmalapl", "v2sigmatau", "v2lapl2", "v2lapltau", "v2tau2", "v3rho3", "v3rho2sigma", "v3rho2lapl", "v3rho2tau", "v3rhosigma2", "v3rhosigmalapl", "v3rhosigmatau", "v3rholapl2", "v3rholapltau", "v3rhotau2", "v3sigma3", "v3sigma2lapl", "v3sigma2tau", "v3sigmalapl2", "v3sigmalapltau", "v3sigmatau2", "v3lapl3", "v3lapl2tau", "v3lapltau2", "v3tau3", "v4rho4", "v4rho3sigma", "v4rho3lapl", "v4rho3tau", "v4rho2sigma2", "v4rho2sigmalapl", "v4rho2sigmatau", "v4rho2lapl2", "v4rho2lapltau", "v4rho2tau2", "v4rhosigma3", "v4rhosigma2lapl", "v4rhosigma2tau", "v4rhosigmalapl2", "v4rhosigmalapltau", "v4rhosigmatau2", "v4rholapl3", "v4rholapl2tau", "v4rholapltau2", "v4rhotau3", "v4sigma4", "v4sigma3lapl", "v4sigma3tau", "v4sigma2lapl2", "v4sigma2lapltau", "v4sigma2tau2", "v4sigmalapl3", "v4sigmalapl2tau", "v4sigmalapltau2", "v4sigmatau3", "v4lapl4", "v4lapl3tau", "v4lapl2tau2", "v4lapltau3", "v4tau4"],
    }
}

/// Validate the caller's buffers and build the chunk view.
///
/// Kernels accumulate with `+=`, so every destination must start at zero --
/// but that zeroing happens per chunk inside `par_sweep`, not here. See the
/// comment on `zero_outputs` for why. Buffers the caller supplied for an order
/// higher than the one requested are still cleared here: they are dropped from
/// the chunk, so the sweep never sees them, and leaving stale values in a
/// buffer the caller handed us would be worse than the cost of clearing it.
pub fn prepare<'a>(
    input: &'a MggaInput<'a>,
    output: &'a mut MggaOutput<'a>,
    order: DerivativeOrder,
    d: &Dimensions,
) -> Result<MggaChunk<'a>, LibxcRsError> {
    let np = input.np();
    let need = required_fields(order);

    macro_rules! take {
        ($f:ident, $name:literal, $stride:expr) => {{
            let wanted = need.contains(&$name);
            match output.$f.take() {
                Some(b) if wanted => {
                    let expected = np * $stride as usize;
                    if b.len() != expected {
                        return Err(LibxcRsError::OutputBufferSizeMismatch {
                            field: $name, expected, actual: b.len(),
                        });
                    }
                    Some(b)
                }
                Some(b) => { b.fill(0.0); None }
                None if wanted => {
                    return Err(LibxcRsError::OutputBufferSizeMismatch {
                        field: $name, expected: np * $stride as usize, actual: 0,
                    })
                }
                None => None,
            }
        }};
    }

    Ok(MggaChunk {
        np,
        rho: input.rho(),
        sigma: input.sigma(),
        lapl: input.lapl(),
        tau: input.tau(),
        zk: take!(zk, "zk", d.zk),
        vrho: take!(vrho, "vrho", d.vrho),
        vsigma: take!(vsigma, "vsigma", d.vsigma),
        vlapl: take!(vlapl, "vlapl", d.vlapl),
        vtau: take!(vtau, "vtau", d.vtau),
        v2rho2: take!(v2rho2, "v2rho2", d.v2rho2),
        v2rhosigma: take!(v2rhosigma, "v2rhosigma", d.v2rhosigma),
        v2rholapl: take!(v2rholapl, "v2rholapl", d.v2rholapl),
        v2rhotau: take!(v2rhotau, "v2rhotau", d.v2rhotau),
        v2sigma2: take!(v2sigma2, "v2sigma2", d.v2sigma2),
        v2sigmalapl: take!(v2sigmalapl, "v2sigmalapl", d.v2sigmalapl),
        v2sigmatau: take!(v2sigmatau, "v2sigmatau", d.v2sigmatau),
        v2lapl2: take!(v2lapl2, "v2lapl2", d.v2lapl2),
        v2lapltau: take!(v2lapltau, "v2lapltau", d.v2lapltau),
        v2tau2: take!(v2tau2, "v2tau2", d.v2tau2),
        v3rho3: take!(v3rho3, "v3rho3", d.v3rho3),
        v3rho2sigma: take!(v3rho2sigma, "v3rho2sigma", d.v3rho2sigma),
        v3rho2lapl: take!(v3rho2lapl, "v3rho2lapl", d.v3rho2lapl),
        v3rho2tau: take!(v3rho2tau, "v3rho2tau", d.v3rho2tau),
        v3rhosigma2: take!(v3rhosigma2, "v3rhosigma2", d.v3rhosigma2),
        v3rhosigmalapl: take!(v3rhosigmalapl, "v3rhosigmalapl", d.v3rhosigmalapl),
        v3rhosigmatau: take!(v3rhosigmatau, "v3rhosigmatau", d.v3rhosigmatau),
        v3rholapl2: take!(v3rholapl2, "v3rholapl2", d.v3rholapl2),
        v3rholapltau: take!(v3rholapltau, "v3rholapltau", d.v3rholapltau),
        v3rhotau2: take!(v3rhotau2, "v3rhotau2", d.v3rhotau2),
        v3sigma3: take!(v3sigma3, "v3sigma3", d.v3sigma3),
        v3sigma2lapl: take!(v3sigma2lapl, "v3sigma2lapl", d.v3sigma2lapl),
        v3sigma2tau: take!(v3sigma2tau, "v3sigma2tau", d.v3sigma2tau),
        v3sigmalapl2: take!(v3sigmalapl2, "v3sigmalapl2", d.v3sigmalapl2),
        v3sigmalapltau: take!(v3sigmalapltau, "v3sigmalapltau", d.v3sigmalapltau),
        v3sigmatau2: take!(v3sigmatau2, "v3sigmatau2", d.v3sigmatau2),
        v3lapl3: take!(v3lapl3, "v3lapl3", d.v3lapl3),
        v3lapl2tau: take!(v3lapl2tau, "v3lapl2tau", d.v3lapl2tau),
        v3lapltau2: take!(v3lapltau2, "v3lapltau2", d.v3lapltau2),
        v3tau3: take!(v3tau3, "v3tau3", d.v3tau3),
        v4rho4: take!(v4rho4, "v4rho4", d.v4rho4),
        v4rho3sigma: take!(v4rho3sigma, "v4rho3sigma", d.v4rho3sigma),
        v4rho3lapl: take!(v4rho3lapl, "v4rho3lapl", d.v4rho3lapl),
        v4rho3tau: take!(v4rho3tau, "v4rho3tau", d.v4rho3tau),
        v4rho2sigma2: take!(v4rho2sigma2, "v4rho2sigma2", d.v4rho2sigma2),
        v4rho2sigmalapl: take!(v4rho2sigmalapl, "v4rho2sigmalapl", d.v4rho2sigmalapl),
        v4rho2sigmatau: take!(v4rho2sigmatau, "v4rho2sigmatau", d.v4rho2sigmatau),
        v4rho2lapl2: take!(v4rho2lapl2, "v4rho2lapl2", d.v4rho2lapl2),
        v4rho2lapltau: take!(v4rho2lapltau, "v4rho2lapltau", d.v4rho2lapltau),
        v4rho2tau2: take!(v4rho2tau2, "v4rho2tau2", d.v4rho2tau2),
        v4rhosigma3: take!(v4rhosigma3, "v4rhosigma3", d.v4rhosigma3),
        v4rhosigma2lapl: take!(v4rhosigma2lapl, "v4rhosigma2lapl", d.v4rhosigma2lapl),
        v4rhosigma2tau: take!(v4rhosigma2tau, "v4rhosigma2tau", d.v4rhosigma2tau),
        v4rhosigmalapl2: take!(v4rhosigmalapl2, "v4rhosigmalapl2", d.v4rhosigmalapl2),
        v4rhosigmalapltau: take!(v4rhosigmalapltau, "v4rhosigmalapltau", d.v4rhosigmalapltau),
        v4rhosigmatau2: take!(v4rhosigmatau2, "v4rhosigmatau2", d.v4rhosigmatau2),
        v4rholapl3: take!(v4rholapl3, "v4rholapl3", d.v4rholapl3),
        v4rholapl2tau: take!(v4rholapl2tau, "v4rholapl2tau", d.v4rholapl2tau),
        v4rholapltau2: take!(v4rholapltau2, "v4rholapltau2", d.v4rholapltau2),
        v4rhotau3: take!(v4rhotau3, "v4rhotau3", d.v4rhotau3),
        v4sigma4: take!(v4sigma4, "v4sigma4", d.v4sigma4),
        v4sigma3lapl: take!(v4sigma3lapl, "v4sigma3lapl", d.v4sigma3lapl),
        v4sigma3tau: take!(v4sigma3tau, "v4sigma3tau", d.v4sigma3tau),
        v4sigma2lapl2: take!(v4sigma2lapl2, "v4sigma2lapl2", d.v4sigma2lapl2),
        v4sigma2lapltau: take!(v4sigma2lapltau, "v4sigma2lapltau", d.v4sigma2lapltau),
        v4sigma2tau2: take!(v4sigma2tau2, "v4sigma2tau2", d.v4sigma2tau2),
        v4sigmalapl3: take!(v4sigmalapl3, "v4sigmalapl3", d.v4sigmalapl3),
        v4sigmalapl2tau: take!(v4sigmalapl2tau, "v4sigmalapl2tau", d.v4sigmalapl2tau),
        v4sigmalapltau2: take!(v4sigmalapltau2, "v4sigmalapltau2", d.v4sigmalapltau2),
        v4sigmatau3: take!(v4sigmatau3, "v4sigmatau3", d.v4sigmatau3),
        v4lapl4: take!(v4lapl4, "v4lapl4", d.v4lapl4),
        v4lapl3tau: take!(v4lapl3tau, "v4lapl3tau", d.v4lapl3tau),
        v4lapl2tau2: take!(v4lapl2tau2, "v4lapl2tau2", d.v4lapl2tau2),
        v4lapltau3: take!(v4lapltau3, "v4lapltau3", d.v4lapltau3),
        v4tau4: take!(v4tau4, "v4tau4", d.v4tau4),
    })
}

/// Dispatch one MGGA functional across the grid in parallel.
///
/// Arms are written out rather than folded into a helper macro: `macro_rules!`
/// cannot nest a repetition inside another macro's repetition.
#[macro_export]
macro_rules! ten_arm_dispatch_rmgga {
    (
        $input:expr, $output:expr, $order:expr, $spin:expr, $thresholds:expr,
        [$($exc_u:tt)::+],
        [$($vxc_u:tt)::+],
        [$($fxc_u:tt)::+],
        [$($kxc_u:tt)::+],
        [$($lxc_u:tt)::+],
        [$($exc_p:tt)::+],
        [$($vxc_p:tt)::+],
        [$($fxc_p:tt)::+],
        [$($kxc_p:tt)::+],
        [$($lxc_p:tt)::+],
        params = ( $( $scalar:expr ),* $(,)? )
    ) => {{
        use $crate::sweep_mgga::{min_chunk, par_sweep};
        use libxc_core::dims::Dimensions;
        use libxc_core::model::{DerivativeOrder, Spin};

        let d = Dimensions::mgga($spin);
        let dt = $thresholds.density;
        let zt = $thresholds.zeta;
        let chunk = $crate::mgga::prepare($input, $output, $order, &d)?;

        match ($order, $spin) {
            (DerivativeOrder::Exc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_mgga::MggaChunk<'_>| {
                $($exc_u)::+(
                        c.rho, c.sigma, c.lapl, c.tau,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Vxc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_mgga::MggaChunk<'_>| {
                $($vxc_u)::+(
                        c.rho, c.sigma, c.lapl, c.tau,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vlapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vtau.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Fxc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_mgga::MggaChunk<'_>| {
                $($fxc_u)::+(
                        c.rho, c.sigma, c.lapl, c.tau,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vlapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vtau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rholapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhotau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmalapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmatau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2tau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Kxc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_mgga::MggaChunk<'_>| {
                $($kxc_u)::+(
                        c.rho, c.sigma, c.lapl, c.tau,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vlapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vtau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rholapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhotau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmalapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmatau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2tau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2sigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2lapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigmalapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigmatau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rholapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rholapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhotau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma2lapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigmalapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigmalapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigmatau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3lapl3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3lapl2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3lapltau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3tau3.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Lxc, Spin::Unpolarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_mgga::MggaChunk<'_>| {
                $($lxc_u)::+(
                        c.rho, c.sigma, c.lapl, c.tau,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vlapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vtau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rholapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhotau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmalapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmatau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2tau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2sigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2lapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigmalapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigmatau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rholapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rholapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhotau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma2lapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigmalapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigmalapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigmatau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3lapl3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3lapl2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3lapltau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3tau3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho4.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho3sigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho3lapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho3tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho2sigmalapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho2sigmatau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho2lapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho2lapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho2tau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rhosigma3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rhosigma2lapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rhosigma2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rhosigmalapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rhosigmalapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rhosigmatau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rholapl3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rholapl2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rholapltau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rhotau3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigma4.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigma3lapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigma3tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigma2lapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigma2lapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigma2tau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigmalapl3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigmalapl2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigmalapltau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigmatau3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4lapl4.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4lapl3tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4lapl2tau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4lapltau3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4tau4.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Exc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_mgga::MggaChunk<'_>| {
                $($exc_p)::+(
                        c.rho, c.sigma, c.lapl, c.tau,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Vxc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_mgga::MggaChunk<'_>| {
                $($vxc_p)::+(
                        c.rho, c.sigma, c.lapl, c.tau,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vlapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vtau.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Fxc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_mgga::MggaChunk<'_>| {
                $($fxc_p)::+(
                        c.rho, c.sigma, c.lapl, c.tau,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vlapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vtau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rholapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhotau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmalapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmatau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2tau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Kxc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_mgga::MggaChunk<'_>| {
                $($kxc_p)::+(
                        c.rho, c.sigma, c.lapl, c.tau,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vlapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vtau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rholapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhotau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmalapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmatau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2tau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2sigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2lapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigmalapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigmatau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rholapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rholapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhotau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma2lapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigmalapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigmalapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigmatau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3lapl3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3lapl2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3lapltau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3tau3.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
            (DerivativeOrder::Lxc, Spin::Polarized) => par_sweep(chunk, &d, min_chunk(), dt, &|c: &mut $crate::sweep_mgga::MggaChunk<'_>| {
                $($lxc_p)::+(
                        c.rho, c.sigma, c.lapl, c.tau,
                        c.zk.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vrho.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vsigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vlapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.vtau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rho2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhosigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rholapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2rhotau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmalapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2sigmatau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2lapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v2tau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2sigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2lapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rho2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigmalapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhosigmatau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rholapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rholapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3rhotau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma2lapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigma2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigmalapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigmalapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3sigmatau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3lapl3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3lapl2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3lapltau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v3tau3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho4.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho3sigma.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho3lapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho3tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho2sigma2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho2sigmalapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho2sigmatau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho2lapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho2lapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rho2tau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rhosigma3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rhosigma2lapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rhosigma2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rhosigmalapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rhosigmalapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rhosigmatau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rholapl3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rholapl2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rholapltau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4rhotau3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigma4.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigma3lapl.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigma3tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigma2lapl2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigma2lapltau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigma2tau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigmalapl3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigmalapl2tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigmalapltau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4sigmatau3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4lapl4.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4lapl3tau.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4lapl2tau2.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4lapltau3.as_deref_mut().expect("prepare guarantees this buffer"),
                        c.v4tau4.as_deref_mut().expect("prepare guarantees this buffer"),
                        $( $scalar, )*
                        dt, zt,
                    )
            }),
        }
        Ok(())
    }};
}
