//! Stride-aware parallel splitting for GGA evaluations.
//!
//! GENERATED by tools/translate_rayon/gen_eval.py -- do not hand-edit.
//!
//! Each array carries its own elements-per-grid-point count (`Dimensions`), so
//! a run of `n` grid points sits at a *different* offset in every array.
//! Splitting them all at one offset compiles fine and silently misaligns every
//! output past the first chunk, so each is split at its own stride.
//!
//! The split is recursive halving through `rayon::join`, which keeps it in safe
//! code: each worker gets genuinely disjoint `&mut` slices, with no raw
//! pointers anywhere.

use libxc_core::dims::Dimensions;

/// One contiguous run of grid points, every array narrowed to it.
pub struct GgaChunk<'inp, 'out> {
    pub np: usize,
    pub rho: &'inp [f64],
    pub sigma: &'inp [f64],
    pub zk: Option<&'out mut [f64]>,
    pub vrho: Option<&'out mut [f64]>,
    pub vsigma: Option<&'out mut [f64]>,
    pub v2rho2: Option<&'out mut [f64]>,
    pub v2rhosigma: Option<&'out mut [f64]>,
    pub v2sigma2: Option<&'out mut [f64]>,
    pub v3rho3: Option<&'out mut [f64]>,
    pub v3rho2sigma: Option<&'out mut [f64]>,
    pub v3rhosigma2: Option<&'out mut [f64]>,
    pub v3sigma3: Option<&'out mut [f64]>,
    pub v4rho4: Option<&'out mut [f64]>,
    pub v4rho3sigma: Option<&'out mut [f64]>,
    pub v4rho2sigma2: Option<&'out mut [f64]>,
    pub v4rhosigma3: Option<&'out mut [f64]>,
    pub v4sigma4: Option<&'out mut [f64]>,
}

#[inline]
fn split_opt<'out>(o: Option<&'out mut [f64]>, at: usize) -> (Option<&'out mut [f64]>, Option<&'out mut [f64]>) {
    match o {
        Some(s) => {
            let (l, r) = s.split_at_mut(at);
            (Some(l), Some(r))
        }
        None => (None, None),
    }
}

impl<'inp, 'out> GgaChunk<'inp, 'out> {
    /// Split at grid point `mid`, narrowing every array at its own stride.
    pub fn split_at(self, mid: usize, d: &Dimensions) -> (GgaChunk<'inp, 'out>, GgaChunk<'inp, 'out>) {
        let (rho_l, rho_r) = self.rho.split_at(mid * d.rho as usize);
        let (sigma_l, sigma_r) = self.sigma.split_at(mid * d.sigma as usize);
        let (o0_l, o0_r) = split_opt(self.zk, mid * d.zk as usize);
        let (o1_l, o1_r) = split_opt(self.vrho, mid * d.vrho as usize);
        let (o2_l, o2_r) = split_opt(self.vsigma, mid * d.vsigma as usize);
        let (o3_l, o3_r) = split_opt(self.v2rho2, mid * d.v2rho2 as usize);
        let (o4_l, o4_r) = split_opt(self.v2rhosigma, mid * d.v2rhosigma as usize);
        let (o5_l, o5_r) = split_opt(self.v2sigma2, mid * d.v2sigma2 as usize);
        let (o6_l, o6_r) = split_opt(self.v3rho3, mid * d.v3rho3 as usize);
        let (o7_l, o7_r) = split_opt(self.v3rho2sigma, mid * d.v3rho2sigma as usize);
        let (o8_l, o8_r) = split_opt(self.v3rhosigma2, mid * d.v3rhosigma2 as usize);
        let (o9_l, o9_r) = split_opt(self.v3sigma3, mid * d.v3sigma3 as usize);
        let (o10_l, o10_r) = split_opt(self.v4rho4, mid * d.v4rho4 as usize);
        let (o11_l, o11_r) = split_opt(self.v4rho3sigma, mid * d.v4rho3sigma as usize);
        let (o12_l, o12_r) = split_opt(self.v4rho2sigma2, mid * d.v4rho2sigma2 as usize);
        let (o13_l, o13_r) = split_opt(self.v4rhosigma3, mid * d.v4rhosigma3 as usize);
        let (o14_l, o14_r) = split_opt(self.v4sigma4, mid * d.v4sigma4 as usize);
        (
            GgaChunk {
                np: mid,
                rho: rho_l,
                sigma: sigma_l,
                zk: o0_l,
                vrho: o1_l,
                vsigma: o2_l,
                v2rho2: o3_l,
                v2rhosigma: o4_l,
                v2sigma2: o5_l,
                v3rho3: o6_l,
                v3rho2sigma: o7_l,
                v3rhosigma2: o8_l,
                v3sigma3: o9_l,
                v4rho4: o10_l,
                v4rho3sigma: o11_l,
                v4rho2sigma2: o12_l,
                v4rhosigma3: o13_l,
                v4sigma4: o14_l,
            },
            GgaChunk {
                np: self.np - mid,
                rho: rho_r,
                sigma: sigma_r,
                zk: o0_r,
                vrho: o1_r,
                vsigma: o2_r,
                v2rho2: o3_r,
                v2rhosigma: o4_r,
                v2sigma2: o5_r,
                v3rho3: o6_r,
                v3rho2sigma: o7_r,
                v3rhosigma2: o8_r,
                v3sigma3: o9_r,
                v4rho4: o10_r,
                v4rho3sigma: o11_r,
                v4rho2sigma2: o12_r,
                v4rhosigma3: o13_r,
                v4sigma4: o14_r,
            },
        )
    }

    /// Reborrow a contiguous window of `len` grid points starting at `start`.
    ///
    /// `split_at` consumes the chunk, which is what the halving sweep wants but
    /// not what density screening wants: there the same chunk has to be visited
    /// as several disjoint windows and then still be available to clean up
    /// afterwards. Reborrowing keeps ownership with the caller. Every array is
    /// narrowed at its own stride, for the same reason `split_at` is.
    fn window(&mut self, start: usize, len: usize, d: &Dimensions) -> GgaChunk<'inp, '_> {
        let end = start + len;
        GgaChunk {
            np: len,
            rho: &self.rho[start * d.rho as usize..end * d.rho as usize],
            sigma: &self.sigma[start * d.sigma as usize..end * d.sigma as usize],
            zk: self.zk.as_deref_mut()
                .map(|s| &mut s[start * d.zk as usize..end * d.zk as usize]),
            vrho: self.vrho.as_deref_mut()
                .map(|s| &mut s[start * d.vrho as usize..end * d.vrho as usize]),
            vsigma: self.vsigma.as_deref_mut()
                .map(|s| &mut s[start * d.vsigma as usize..end * d.vsigma as usize]),
            v2rho2: self.v2rho2.as_deref_mut()
                .map(|s| &mut s[start * d.v2rho2 as usize..end * d.v2rho2 as usize]),
            v2rhosigma: self.v2rhosigma.as_deref_mut()
                .map(|s| &mut s[start * d.v2rhosigma as usize..end * d.v2rhosigma as usize]),
            v2sigma2: self.v2sigma2.as_deref_mut()
                .map(|s| &mut s[start * d.v2sigma2 as usize..end * d.v2sigma2 as usize]),
            v3rho3: self.v3rho3.as_deref_mut()
                .map(|s| &mut s[start * d.v3rho3 as usize..end * d.v3rho3 as usize]),
            v3rho2sigma: self.v3rho2sigma.as_deref_mut()
                .map(|s| &mut s[start * d.v3rho2sigma as usize..end * d.v3rho2sigma as usize]),
            v3rhosigma2: self.v3rhosigma2.as_deref_mut()
                .map(|s| &mut s[start * d.v3rhosigma2 as usize..end * d.v3rhosigma2 as usize]),
            v3sigma3: self.v3sigma3.as_deref_mut()
                .map(|s| &mut s[start * d.v3sigma3 as usize..end * d.v3sigma3 as usize]),
            v4rho4: self.v4rho4.as_deref_mut()
                .map(|s| &mut s[start * d.v4rho4 as usize..end * d.v4rho4 as usize]),
            v4rho3sigma: self.v4rho3sigma.as_deref_mut()
                .map(|s| &mut s[start * d.v4rho3sigma as usize..end * d.v4rho3sigma as usize]),
            v4rho2sigma2: self.v4rho2sigma2.as_deref_mut()
                .map(|s| &mut s[start * d.v4rho2sigma2 as usize..end * d.v4rho2sigma2 as usize]),
            v4rhosigma3: self.v4rhosigma3.as_deref_mut()
                .map(|s| &mut s[start * d.v4rhosigma3 as usize..end * d.v4rhosigma3 as usize]),
            v4sigma4: self.v4sigma4.as_deref_mut()
                .map(|s| &mut s[start * d.v4sigma4 as usize..end * d.v4sigma4 as usize]),
        }
    }
}

use std::sync::atomic::{AtomicUsize, Ordering};

/// Minimum grid points per task; below this, splitting costs more than it saves.
static MIN_CHUNK: AtomicUsize = AtomicUsize::new(2048);

pub fn min_chunk() -> usize {
    MIN_CHUNK.load(Ordering::Relaxed)
}

/// Test hook. Setting this to `usize::MAX` disables splitting, so a dispatch
/// runs as one whole-grid call -- which is exactly the reference the chunked
/// path has to reproduce bit-for-bit.
pub fn set_min_chunk(n: usize) {
    MIN_CHUNK.store(n.max(1), Ordering::Relaxed);
}

/// Clear this chunk's slice of every output the sweep is going to write.
///
/// The kernels accumulate with `+=`, so the destination has to start at zero.
/// Doing that in `prepare` instead -- one `fill(0.0)` per whole output array --
/// costs a full serial pass over every output buffer before any arithmetic
/// starts, and leaves the memory cold: by the time the kernel accumulates into
/// a given cache line, the zero written into it has long been evicted, so each
/// element is fetched from DRAM a second time. Per chunk, the zeroed range is
/// still in L1/L2 when the kernel reads it back, and the clearing itself is
/// spread over every worker instead of running on one thread.
///
/// Bit-exactness is unaffected: the stored value and the order of the
/// accumulations are identical either way, only the moment of the store moves.
#[inline]
fn zero_outputs(chunk: &mut GgaChunk<'_, '_>) {
    if let Some(s) = chunk.zk.as_deref_mut() { s.fill(0.0); }
    if let Some(s) = chunk.vrho.as_deref_mut() { s.fill(0.0); }
    if let Some(s) = chunk.vsigma.as_deref_mut() { s.fill(0.0); }
    if let Some(s) = chunk.v2rho2.as_deref_mut() { s.fill(0.0); }
    if let Some(s) = chunk.v2rhosigma.as_deref_mut() { s.fill(0.0); }
    if let Some(s) = chunk.v2sigma2.as_deref_mut() { s.fill(0.0); }
    if let Some(s) = chunk.v3rho3.as_deref_mut() { s.fill(0.0); }
    if let Some(s) = chunk.v3rho2sigma.as_deref_mut() { s.fill(0.0); }
    if let Some(s) = chunk.v3rhosigma2.as_deref_mut() { s.fill(0.0); }
    if let Some(s) = chunk.v3sigma3.as_deref_mut() { s.fill(0.0); }
    if let Some(s) = chunk.v4rho4.as_deref_mut() { s.fill(0.0); }
    if let Some(s) = chunk.v4rho3sigma.as_deref_mut() { s.fill(0.0); }
    if let Some(s) = chunk.v4rho2sigma2.as_deref_mut() { s.fill(0.0); }
    if let Some(s) = chunk.v4rhosigma3.as_deref_mut() { s.fill(0.0); }
    if let Some(s) = chunk.v4sigma4.as_deref_mut() { s.fill(0.0); }
}

/// Total density at grid point `ip`, the quantity libxc screens on.
#[inline]
fn total_density(rho: &[f64], ip: usize, nc: usize) -> f64 {
    if nc == 1 { rho[ip] } else { rho[ip * 2] + rho[ip * 2 + 1] }
}

/// Clear every output at one grid point.
#[inline]
fn zero_point(chunk: &mut GgaChunk<'_, '_>, ip: usize, d: &Dimensions) {
    if let Some(s) = chunk.zk.as_deref_mut() {
        let w = d.zk as usize;
        s[ip * w..(ip + 1) * w].fill(0.0);
    }
    if let Some(s) = chunk.vrho.as_deref_mut() {
        let w = d.vrho as usize;
        s[ip * w..(ip + 1) * w].fill(0.0);
    }
    if let Some(s) = chunk.vsigma.as_deref_mut() {
        let w = d.vsigma as usize;
        s[ip * w..(ip + 1) * w].fill(0.0);
    }
    if let Some(s) = chunk.v2rho2.as_deref_mut() {
        let w = d.v2rho2 as usize;
        s[ip * w..(ip + 1) * w].fill(0.0);
    }
    if let Some(s) = chunk.v2rhosigma.as_deref_mut() {
        let w = d.v2rhosigma as usize;
        s[ip * w..(ip + 1) * w].fill(0.0);
    }
    if let Some(s) = chunk.v2sigma2.as_deref_mut() {
        let w = d.v2sigma2 as usize;
        s[ip * w..(ip + 1) * w].fill(0.0);
    }
    if let Some(s) = chunk.v3rho3.as_deref_mut() {
        let w = d.v3rho3 as usize;
        s[ip * w..(ip + 1) * w].fill(0.0);
    }
    if let Some(s) = chunk.v3rho2sigma.as_deref_mut() {
        let w = d.v3rho2sigma as usize;
        s[ip * w..(ip + 1) * w].fill(0.0);
    }
    if let Some(s) = chunk.v3rhosigma2.as_deref_mut() {
        let w = d.v3rhosigma2 as usize;
        s[ip * w..(ip + 1) * w].fill(0.0);
    }
    if let Some(s) = chunk.v3sigma3.as_deref_mut() {
        let w = d.v3sigma3 as usize;
        s[ip * w..(ip + 1) * w].fill(0.0);
    }
    if let Some(s) = chunk.v4rho4.as_deref_mut() {
        let w = d.v4rho4 as usize;
        s[ip * w..(ip + 1) * w].fill(0.0);
    }
    if let Some(s) = chunk.v4rho3sigma.as_deref_mut() {
        let w = d.v4rho3sigma as usize;
        s[ip * w..(ip + 1) * w].fill(0.0);
    }
    if let Some(s) = chunk.v4rho2sigma2.as_deref_mut() {
        let w = d.v4rho2sigma2 as usize;
        s[ip * w..(ip + 1) * w].fill(0.0);
    }
    if let Some(s) = chunk.v4rhosigma3.as_deref_mut() {
        let w = d.v4rhosigma3 as usize;
        s[ip * w..(ip + 1) * w].fill(0.0);
    }
    if let Some(s) = chunk.v4sigma4.as_deref_mut() {
        let w = d.v4sigma4 as usize;
        s[ip * w..(ip + 1) * w].fill(0.0);
    }
}

/// Average length an above-threshold run must reach before it is worth calling
/// the kernel on it separately.
///
/// Splitting has a fixed per-call cost (the kernel's prologue, and the loop
/// never getting up to speed). Measured on this tree, splitting a grid whose
/// below-threshold points are scattered individually -- average run ~1.7 points
/// -- cost about 14 ns per call, which turned `gga_x_b88` from 1.98 to 6.84
/// ns/point: worse than doing no screening at all. So a fragmented chunk takes
/// the other route below instead.
const MIN_RUN: usize = 128;

/// Evaluate `f` over the above-threshold points only, leaving the rest zero.
///
/// This reproduces what libxc does at the top of its per-point loop
/// (`work_gga_inc.c`):
///
/// ```c
/// dens = (nspin == XC_POLARIZED) ? rho[2*ip] + rho[2*ip+1] : rho[ip];
/// if(dens < p->dens_threshold)
///   continue;
/// ```
///
/// **It is a correctness fix before it is an optimisation.** Only some kernels
/// carry a `dens_threshold` guard of their own -- the exchange functionals
/// mostly do (`gga_x_b88`: `rho[ip] / 2.0 <= dens_threshold`), the correlation
/// functionals mostly do not (`lda_c_vwn`, `gga_c_lyp`, `mgga_c_r2scan` have
/// none). libxc puts the screen *outside* the maple2c body, so it covers all of
/// them uniformly; this library called the body directly, so for an unguarded
/// functional the empty tail of a molecular grid got the raw formula value
/// where libxc gives exactly 0. Measured against C libxc on a grid with 40% of
/// its points below threshold, `lda_c_vwn` and `gga_c_lyp` came back with a
/// worst relative difference of 1.0 -- a 100% error on `zk` -- while
/// `gga_x_b88` and `mgga_x_scan`, which have the guard, agreed to 1e-15.
///
/// For a screened point the output keeps the zero `zero_outputs` just wrote.
/// That is bit-identical to what a *guarded* kernel would have produced there
/// (its outputs are `piecewise3(guard, 0.0, ..)` terms, which collapse to
/// `+0.0`), so this changes nothing for those functionals and fixes the rest.
/// Verified: with no below-threshold points present, every output fingerprint
/// is unchanged by this function existing.
///
/// Two routes, picked from a single forward pass over `rho`:
///
/// * **Runs.** A real Becke/Lebedev grid orders points by radial shell, so its
///   empty points are contiguous. Each maximal above-threshold run becomes one
///   kernel call and the tail is never touched -- a whole empty chunk costs
///   nothing at all.
/// * **Compute then re-zero.** If the below-threshold points are scattered so
///   finely that runs would average under `MIN_RUN`, splitting costs more than
///   it saves. Then the kernel runs over the whole chunk and the screened
///   points are zeroed afterwards. No arithmetic is saved, but the answer is
///   the same one, which is the part that matters.
fn screened_call<F>(mut chunk: GgaChunk<'_, '_>, d: &Dimensions, dens_threshold: f64, f: &F)
where
    F: Fn(&mut GgaChunk<'_, '_>) + Sync,
{
    let nc = d.rho as usize;
    let np = chunk.np;

    // One pass: how many points are screened out, and into how many runs do the
    // survivors fall.
    let mut below = 0usize;
    let mut runs = 0usize;
    let mut prev_active = false;
    for ip in 0..np {
        let active = total_density(chunk.rho, ip, nc) >= dens_threshold;
        if !active {
            below += 1;
        } else if !prev_active {
            runs += 1;
        }
        prev_active = active;
    }

    // Overwhelmingly the common case: nothing to screen, so this costs one
    // linear read of `rho` that the kernel is about to make anyway.
    if below == 0 {
        f(&mut chunk);
        return;
    }
    // Whole chunk is in the tail: the zeros already written are the answer.
    if below == np {
        return;
    }

    if runs * MIN_RUN <= np - below {
        let mut ip = 0;
        while ip < np {
            if total_density(chunk.rho, ip, nc) < dens_threshold {
                ip += 1;
                continue;
            }
            let start = ip;
            while ip < np && total_density(chunk.rho, ip, nc) >= dens_threshold {
                ip += 1;
            }
            let mut w = chunk.window(start, ip - start, d);
            f(&mut w);
        }
    } else {
        f(&mut chunk);
        for ip in 0..np {
            if total_density(chunk.rho, ip, nc) < dens_threshold {
                zero_point(&mut chunk, ip, d);
            }
        }
    }
}

/// Recursively halve the grid and evaluate each piece in parallel.
pub fn par_sweep<F>(
    mut chunk: GgaChunk<'_, '_>,
    d: &Dimensions,
    min_chunk: usize,
    dens_threshold: f64,
    f: &F,
) where
    F: Fn(&mut GgaChunk<'_, '_>) + Sync,
{
    if chunk.np <= min_chunk {
        zero_outputs(&mut chunk);
        screened_call(chunk, d, dens_threshold, f);
        return;
    }
    let mid = chunk.np / 2;
    let (l, r) = chunk.split_at(mid, d);
    rayon::join(
        || par_sweep(l, d, min_chunk, dens_threshold, f),
        || par_sweep(r, d, min_chunk, dens_threshold, f),
    );
}
