//! MBRXC root-finder for CubeCL kernels.
//!
//! Implements `xc_mgga_x_mbrxc_get_x(Q)` which solves
//!   (1+x)^(5/3) * exp(-2x/3) - rhs * (x - 3) = 0
//! via inlined Brent's method. Called by `mgga_x_mbrxc_bg` and `mgga_x_mggac`.
//!
//! Translated from libxc `mgga_x_mbrxc_bg.c` and `math_brent.c`. Mirrors the
//! structure of `br89.rs`: 60 unrolled Brent iterations because CubeCL does
//! not support dynamic loops, function pointers, or tuple returns from helpers.

#![allow(
    clippy::excessive_precision,
    clippy::too_many_arguments,
    unused_variables,
    non_snake_case,
)]

use cubecl::prelude::*;

/// (32 * pi)^(2/3) — precomputed constant used in the rhs formula.
const POW_32PI_TWO_THIRDS: f64 = 21.620541520507917;

/// Evaluate the MBRXC objective: f(x) = (1+x)^(5/3) * exp(-2x/3) - rhs*(x-3).
#[cube]
fn mbrxc_obj<F: Float>(x: F, rhs: F) -> F {
    let xm3 = x - F::new(3.0);
    let arg = F::new(2.0) * x / F::new(3.0);
    // Guard exp underflow: for arg > ~115, exp(-arg) is below f64 subnormal min.
    let eee = select(arg <= F::cast_from(115.12925464970228_f64), F::exp(-arg), F::new(0.0));
    let one_plus_x = F::new(1.0) + x;
    let pow53 = F::powf(one_plus_x, F::new(5.0) / F::new(3.0));
    pow53 * eee - rhs * xm3
}

/// Solve for x given Q: returns the BR-style cuspless-hole exchange parameter.
#[cube]
pub fn xc_mgga_x_mbrxc_get_x<F: Float>(q_val: F) -> F {
    let tol: F = F::cast_from(5.0e-12_f64);
    let mut result: F = F::new(3.0);

    if F::abs(q_val) >= F::cast_from(5.0e-12_f64) {
        // rhs = (32π)^(2/3) / (6 Q)
        let rhs = F::cast_from(POW_32PI_TWO_THIRDS) / (F::new(6.0) * q_val);

        // Starting interval per libxc/mgga_x_mbrxc_bg.c (lines 36-44):
        //   rhs > 0  →  [3.0,  2/rhs + 3.0]
        //   rhs ≤ 0  →  [-1.0, 3.0]
        let mut a = select(rhs > F::new(0.0), F::new(3.0), F::new(-1.0));
        let mut b = select(rhs > F::new(0.0), F::new(2.0) / rhs + F::new(3.0), F::new(3.0));

        let mut fa = mbrxc_obj::<F>(a, rhs);
        let mut fb = mbrxc_obj::<F>(b, rhs);

        // Ensure |fa| >= |fb|
        let need_swap = F::abs(fa) < F::abs(fb);
        let sa = select(need_swap, b, a);
        let sb = select(need_swap, a, b);
        let sfa = select(need_swap, fb, fa);
        let sfb = select(need_swap, fa, fb);
        a = sa; b = sb; fa = sfa; fb = sfb;

        let mut c = a;
        let mut fc = fa;
        let mut d: F = F::new(0.0);
        let mut mf: F = F::new(1.0); // mflag as F: 1.0 = true

        let mut s: F = F::new(0.0);

        // 60 unrolled Brent iterations
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);
        let use_iqi = fa != fc && fb != fc; let s_iqi = (a*fb*fc/((fa-fb)*(fa-fc)))+(b*fa*fc/((fb-fa)*(fb-fc)))+(c*fa*fb/((fc-fa)*(fc-fb))); let s_sec = b - fb*(b-a)/(fb-fa); s = select(use_iqi, s_iqi, s_sec); let c1 = s < (F::new(3.0)*a+b)*F::new(0.25) || s > b; let c2 = mf > F::new(0.5) && F::abs(s-b) >= F::abs(b-c)*F::new(0.5); let c3 = mf <= F::new(0.5) && F::abs(s-b) >= F::abs(c-d)*F::new(0.5); let c4 = mf > F::new(0.5) && F::abs(b-c) < tol; let c5 = mf <= F::new(0.5) && F::abs(c-d) < tol; let do_bi = c1||c2||c3||c4||c5; s = select(do_bi, (a+b)*F::new(0.5), s); mf = select(do_bi, F::new(1.0), F::new(0.0)); let fs = mbrxc_obj::<F>(s, rhs); d = c; c = b; fc = fb; let rl = fa*fs < F::new(0.0); b = select(rl, s, b); fb = select(rl, fs, fb); a = select(rl, a, s); fa = select(rl, fa, fs); let sw = F::abs(fa) < F::abs(fb); let ta = a; let tb = b; let tfa = fa; let tfb = fb; a = select(sw, tb, ta); fa = select(sw, tfb, tfa); b = select(sw, ta, tb); fb = select(sw, tfa, tfb);

        result = (b + a) * F::new(0.5);
    }

    result
}

#[cfg(test)]
mod tests {
    use std::f64::consts::PI;

    fn mbrxc_get_x_reference(q: f64) -> f64 {
        let tol = 5.0e-12;
        if q.abs() < 5.0e-12 { return 3.0; }
        let rhs = (32.0 * PI).powf(2.0 / 3.0) / (6.0 * q);
        let (mut a, mut b) = if rhs > 0.0 { (3.0_f64, 2.0/rhs + 3.0) } else { (-1.0_f64, 3.0_f64) };
        let obj = |x: f64| -> f64 {
            let arg = 2.0 * x / 3.0;
            let e = if arg > 115.13 { 0.0 } else { (-arg).exp() };
            (1.0 + x).powf(5.0/3.0) * e - rhs * (x - 3.0)
        };
        let mut fa = obj(a); let mut fb = obj(b);
        if fa.abs() < fb.abs() { std::mem::swap(&mut a, &mut b); std::mem::swap(&mut fa, &mut fb); }
        let mut c = a; let mut fc = fa; let mut d = 0.0_f64; let mut mflag = true;
        for _ in 0..500 {
            if (b - a).abs() < tol { return (b + a) / 2.0; }
            let s = if fa != fc && fb != fc {
                (a*fb*fc/((fa-fb)*(fa-fc))) + (b*fa*fc/((fb-fa)*(fb-fc))) + (c*fa*fb/((fc-fa)*(fc-fb)))
            } else { b - fb*(b-a)/(fb-fa) };
            let bi = (s < (3.0*a+b)*0.25 || s > b)
                || (mflag && (s-b).abs() >= (b-c).abs()*0.5)
                || (!mflag && (s-b).abs() >= (c-d).abs()*0.5)
                || (mflag && (b-c).abs() < tol)
                || (!mflag && (c-d).abs() < tol);
            let s = if bi { mflag = true; (a+b)*0.5 } else { mflag = false; s };
            let fs = obj(s); d = c; c = b; fc = fb;
            if fa*fs < 0.0 { b = s; fb = fs; } else { a = s; fa = fs; }
            if fa.abs() < fb.abs() { std::mem::swap(&mut a, &mut b); std::mem::swap(&mut fa, &mut fb); }
        }
        (b + a) / 2.0
    }

    #[test]
    fn small_q_returns_three() {
        assert!((mbrxc_get_x_reference(0.0) - 3.0).abs() < 1e-15);
        assert!((mbrxc_get_x_reference(1e-13) - 3.0).abs() < 1e-15);
    }

    #[test]
    fn root_satisfies_objective() {
        for &q in &[0.01, 0.1, 0.5, 1.0, 5.0, 10.0, 100.0] {
            let x = mbrxc_get_x_reference(q);
            let rhs = (32.0 * PI).powf(2.0 / 3.0) / (6.0 * q);
            let arg = 2.0 * x / 3.0;
            let e = if arg > 115.13 { 0.0 } else { (-arg).exp() };
            let f = (1.0 + x).powf(5.0/3.0) * e - rhs * (x - 3.0);
            assert!(f.abs() < 1e-9, "Q={q}, x={x}, f={f}");
        }
    }

    #[test]
    fn negative_q() {
        for &q in &[-0.01, -0.1, -1.0, -10.0] {
            let x = mbrxc_get_x_reference(q);
            let rhs = (32.0 * PI).powf(2.0 / 3.0) / (6.0 * q);
            let arg = 2.0 * x / 3.0;
            let e = if arg > 115.13 { 0.0 } else { (-arg).exp() };
            let f = (1.0 + x).powf(5.0/3.0) * e - rhs * (x - 3.0);
            assert!(f.abs() < 1e-9, "Q={q}, x={x}, f={f}");
        }
    }
}
