[package]
name = "libxc-kernel-gga"
version = "0.1.0"
edition = "2024"

[dependencies]
cubecl = { version = "0.9.0", default-features = false, features = ["cpu"] }
libxc-kernel-math = { path = "../kernel-math" }
libxc-kernel-gga-1a = { path = "../kernel-gga-1a" }
libxc-kernel-gga-1b = { path = "../kernel-gga-1b" }
libxc-kernel-gga-1c = { path = "../kernel-gga-1c" }
libxc-kernel-gga-1d = { path = "../kernel-gga-1d" }
libxc-kernel-gga-2a = { path = "../kernel-gga-2a" }
libxc-kernel-gga-2b = { path = "../kernel-gga-2b" }
libxc-kernel-gga-2c = { path = "../kernel-gga-2c" }
libxc-kernel-gga-2d = { path = "../kernel-gga-2d" }
libxc-kernel-gga-3a = { path = "../kernel-gga-3a" }
libxc-kernel-gga-3b = { path = "../kernel-gga-3b" }
libxc-kernel-gga-3c = { path = "../kernel-gga-3c" }
libxc-kernel-gga-3d = { path = "../kernel-gga-3d" }
libxc-kernel-gga-3e = { path = "../kernel-gga-3e" }
libxc-kernel-gga-4a = { path = "../kernel-gga-4a" }
libxc-kernel-gga-4b = { path = "../kernel-gga-4b" }
libxc-kernel-gga-4c = { path = "../kernel-gga-4c" }
libxc-kernel-gga-4d = { path = "../kernel-gga-4d" }
libxc-kernel-gga-4e = { path = "../kernel-gga-4e" }
libxc-kernel-gga-4f = { path = "../kernel-gga-4f" }
libxc-kernel-gga-4g = { path = "../kernel-gga-4g" }
libxc-kernel-gga-5a = { path = "../kernel-gga-5a" }
libxc-kernel-gga-5b = { path = "../kernel-gga-5b" }
libxc-kernel-gga-5c = { path = "../kernel-gga-5c" }
libxc-kernel-gga-5d = { path = "../kernel-gga-5d" }
libxc-kernel-gga-5e = { path = "../kernel-gga-5e" }
libxc-kernel-gga-5f = { path = "../kernel-gga-5f" }
libxc-kernel-gga-5g = { path = "../kernel-gga-5g" }
libxc-kernel-gga-6a = { path = "../kernel-gga-6a" }
libxc-kernel-gga-6b = { path = "../kernel-gga-6b" }
libxc-kernel-gga-6c = { path = "../kernel-gga-6c" }
libxc-kernel-gga-6d = { path = "../kernel-gga-6d" }
libxc-kernel-gga-7a = { path = "../kernel-gga-7a" }
libxc-kernel-gga-7b = { path = "../kernel-gga-7b" }
libxc-kernel-gga-7c = { path = "../kernel-gga-7c" }
libxc-kernel-gga-7d = { path = "../kernel-gga-7d" }
libxc-kernel-gga-8a = { path = "../kernel-gga-8a" }
libxc-kernel-gga-8b = { path = "../kernel-gga-8b" }
libxc-kernel-gga-8c = { path = "../kernel-gga-8c" }
libxc-kernel-gga-8d = { path = "../kernel-gga-8d" }
libxc-kernel-gga-9a = { path = "../kernel-gga-9a" }
libxc-kernel-gga-9b = { path = "../kernel-gga-9b" }
libxc-kernel-gga-9c = { path = "../kernel-gga-9c" }
libxc-kernel-gga-10a = { path = "../kernel-gga-10a" }
libxc-kernel-gga-10b = { path = "../kernel-gga-10b" }
libxc-kernel-gga-10c = { path = "../kernel-gga-10c" }
libxc-kernel-gga-10d = { path = "../kernel-gga-10d" }
libxc-kernel-gga-11 = { path = "../kernel-gga-11" }
libxc-kernel-gga-12 = { path = "../kernel-gga-12" }
libxc-kernel-gga-13 = { path = "../kernel-gga-13" }
libxc-kernel-gga-14 = { path = "../kernel-gga-14" }
libxc-kernel-gga-15 = { path = "../kernel-gga-15" }
libxc-kernel-gga-16 = { path = "../kernel-gga-16" }
libxc-kernel-gga-17 = { path = "../kernel-gga-17" }
libxc-kernel-gga-18 = { path = "../kernel-gga-18" }
libxc-kernel-gga-19 = { path = "../kernel-gga-19" }
libxc-kernel-gga-20 = { path = "../kernel-gga-20" }
libxc-kernel-gga-21 = { path = "../kernel-gga-21" }
libxc-kernel-gga-22 = { path = "../kernel-gga-22" }
