//! MGGA_C_TPSS shard sub-crate mgga_c_tpss_p4 (parts 26..=65).
//!
//! Auto-generated by tools/split_per_functional_subcrate.py — do not hand-edit.

#![allow(unused_imports, unused_variables, non_snake_case, clippy::excessive_precision, clippy::too_many_arguments, clippy::needless_return)]

pub mod lxc_pol;

pub use lxc_pol::mgga_c_tpss_lxc_pol_part26_v4rho3sigma_8;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part27_v4rho3sigma_9;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part28_v4rho3sigma_10;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part29_v4rho3sigma_11_v4rho3lapl;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part30_v4rho3tau_0;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part31_v4rho3tau_1;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part32_v4rho3tau_2;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part33_v4rho3tau_3;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part34_v4rho3tau_4;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part35_v4rho3tau_5;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part36_v4rho3tau_6;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part37_v4rho3tau_7;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part38_v4rho2sigma2_0;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part39_v4rho2sigma2_1;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part40_v4rho2sigma2_2;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part41_v4rho2sigma2_3;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part42_v4rho2sigma2_4;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part43_v4rho2sigma2_5;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part44_v4rho2sigma2_6;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part45_v4rho2sigma2_7;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part46_v4rho2sigma2_8;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part47_v4rho2sigma2_9;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part48_v4rho2sigma2_10;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part49_v4rho2sigma2_11;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part50_v4rho2sigma2_12;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part51_v4rho2sigma2_13;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part52_v4rho2sigma2_14;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part53_v4rho2sigma2_15;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part54_v4rho2sigma2_16;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part55_v4rho2sigma2_17_v4rho2sigmalapl;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part56_v4rho2sigmatau_0;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part57_v4rho2sigmatau_1;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part58_v4rho2sigmatau_2_v4rho2sigmatau_3;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part59_v4rho2sigmatau_4;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part60_v4rho2sigmatau_5;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part61_v4rho2sigmatau_6;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part62_v4rho2sigmatau_7;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part63_v4rho2sigmatau_8;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part64_v4rho2sigmatau_9;
pub use lxc_pol::mgga_c_tpss_lxc_pol_part65_v4rho2sigmatau_10;
