[package]
name = "libxc-kernel-gga"
version = "0.1.0"
edition = "2024"

[dependencies]
cubecl = { version = "0.10.0", default-features = false, features = ["cpu"] }
libxc-kernel-math = { path = "../math" }
libxc-kernel-gga-1 = { path = "../gga-1" }
libxc-kernel-gga-2 = { path = "../gga-2" }
libxc-kernel-gga-3 = { path = "../gga-3" }
libxc-kernel-gga-4 = { path = "../gga-4" }
libxc-kernel-gga-5 = { path = "../gga-5" }
libxc-kernel-gga-6 = { path = "../gga-6" }
libxc-kernel-gga-7 = { path = "../gga-7" }
libxc-kernel-gga-8 = { path = "../gga-8" }
